import Link from "next/link";
import Script from "next/script";
import Image from "next/image";
import TableOfContents from "@/components/TableOfContents";
import Breadcrumbs from "@/components/Breadcrumbs";

// FAQ data for rendering and Schema
const faqs = [
  {
    question: "Can a recovery agent arrest me for not paying my personal loan?",
    answer: "No. Defaulting on a personal loan or credit card is a civil dispute, not a criminal offense. A recovery agent has no legal authority to arrest you, and the police will not arrest you for a simple failure to repay a loan due to financial hardship. Any threat of immediate arrest is a scare tactic."
  },
  {
    question: "Are recovery agents allowed to call my relatives or office colleagues?",
    answer: "Absolutely not. Under RBI guidelines and privacy laws, banks and their agents are strictly prohibited from discussing your debt with any third party, including your parents, friends, HR department, or colleagues. Doing so is a violation of your privacy and grounds for a severe legal complaint."
  },
  {
    question: "What time can recovery agents legally call me in India?",
    answer: "According to the Reserve Bank of India (RBI) Fair Practices Code, recovery agents are only permitted to contact borrowers between the hours of 8:00 AM and 7:00 PM. Calls made outside this window constitute harassment."
  },
  {
    question: "Can recovery agents visit my house unannounced?",
    answer: "While agents can visit your registered residential address to inquire about the debt if you are unresponsive, they are supposed to give you prior notice. They cannot force entry into your home, behave aggressively, or cause a public nuisance in your neighborhood."
  },
  {
    question: "What should I do if a recovery agent uses abusive language?",
    answer: "You should immediately start recording the call. Tell the agent firmly that you are recording the conversation and that their abusive language is illegal. Disconnect the call, save the recording, and file a formal grievance with the bank's Nodal Officer attached with the audio evidence."
  },
  {
    question: "Can I file a police complaint against a recovery agent?",
    answer: "Yes. If an agent threatens you with physical violence, uses extreme profanity, stalks you, or tries to extort money through intimidation, you can and should file an FIR at your local police station under sections like 503 (Criminal Intimidation) and 504 of the IPC."
  },
  {
    question: "Is a WhatsApp message claiming to be an 'Arrest Warrant' real?",
    answer: "No. The Indian judicial system does not serve arrest warrants or official court summons via informal WhatsApp messages from unknown mobile numbers. These are almost always fake documents generated by collection agencies to instill panic. Always consult a lawyer to verify any legal document."
  },
  {
    question: "Will taking a loan settlement stop the recovery calls?",
    answer: "Yes. Once you officially enter into a loan settlement agreement with the bank and the terms are finalized in writing, the bank withdraws the account from their collection agencies. Upon completing the settlement payment, you receive a No Dues Certificate, permanently stopping all recovery actions."
  },
  {
    question: "How do I complain to the RBI about recovery agent harassment?",
    answer: "First, you must file a written complaint with your bank's grievance redressal mechanism. If the bank fails to resolve the issue or stop the harassment within 30 days, you can file a complaint online on the official RBI Complaint Management System (CMS) portal."
  },
  {
    question: "Do I have to pay the recovery agent in cash?",
    answer: "No. You should never hand over cash to a recovery agent. Always make payments directly into your loan account via official banking channels (NEFT, RTGS, NetBanking) or via cheque drawn in favor of the bank/loan account. Cash payments given to agents are often misappropriated."
  },
  {
    question: "Can the bank confiscate my property for a personal loan default?",
    answer: "A personal loan is an unsecured loan, meaning it is not backed by collateral. The bank cannot simply come and seize your house, car, or household goods. To attach your property for an unsecured loan, the bank must first file a civil suit in court, win a decree against you, and get a specific execution order from a judge—a lengthy and complex process."
  },
  {
    question: "What is a cease and desist legal notice?",
    answer: "A cease and desist notice is a formal legal document sent by a lawyer on your behalf to the bank and the recovery agency. It legally warns them that their actions constitute illegal harassment, demands that they stop immediately, and states your intention to take them to court or the RBI Ombudsman if they fail to comply."
  },
  {
    question: "Why are credit card recovery agents so aggressive?",
    answer: "Credit card debt is unsecured and carries the highest interest rates. Because there is no collateral to seize, collection agencies rely on psychological pressure and aggressive follow-ups to force you to prioritize their payment over other expenses. This is why legal intervention is often necessary to handle them."
  },
  {
    question: "What if my cheque bounces? Will I go to jail?",
    answer: "If you provided a PDC (Post Dated Cheque) that bounces, the bank can file a case under Section 138 of the Negotiable Instruments Act. This is a criminal offense and can lead to penalties or imprisonment if ignored. However, the court allows you ample time to settle the matter or defend yourself before passing any harsh judgments. You must respond to a Section 138 notice through a lawyer immediately."
  },
  {
    question: "How can AMA Legal Solutions help me with debt resolution?",
    answer: "AMA Legal Solutions acts as your legal buffer. We take over all communications with the harassing banks, send necessary legal notices to ensure your rights are protected, and negotiate aggressively on your behalf to secure a favorable, affordable debt settlement (OTS) that allows you to become debt-free without sacrificing your dignity."
  }
];

const breadcrumbSchema = {
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  "itemListElement": [
    {
      "@type": "ListItem",
      "position": 1,
      "name": "Home",
      "item": "https://www.amalegalsolutions.com"
    },
    {
      "@type": "ListItem",
      "position": 2,
      "name": "What To Do If Recovery Agents Harass You",
      "item": "https://www.amalegalsolutions.com/what-to-do-if-recovery-agents-harass-you"
    }
  ]
};

const articleSchema = {
  "@context": "https://schema.org",
  "@type": "Article",
  "headline": "What Should I Do If Recovery Agents Are Harassing Me? Legal Rights",
  "description": "Facing recovery agent harassment? Learn your legal borrower rights, RBI guidelines, and step-by-step actions to stop abuse. Contact AMA Legal Solutions for debt settlement help.",
  "image": "https://www.amalegalsolutions.com/services/3.png",
  "author": {
    "@type": "Organization",
    "name": "AMA Legal Solutions",
    "url": "https://www.amalegalsolutions.com"
  },
  "publisher": {
    "@type": "Organization",
    "name": "AMA Legal Solutions",
    "logo": {
      "@type": "ImageObject",
      "url": "https://www.amalegalsolutions.com/ama-legal-solutions-logo.png"
    }
  },
  "datePublished": "2026-07-04",
  "dateModified": "2026-07-04"
};

const faqSchema = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  "mainEntity": faqs.map(faq => ({
    "@type": "Question",
    "name": faq.question,
    "acceptedAnswer": {
      "@type": "Answer",
      "text": faq.answer
    }
  }))
};

export const metadata = {
  title: "What Should I Do If Recovery Agents Are Harassing Me? Legal Rights",
  description: "Facing recovery agent harassment? Learn your legal borrower rights, RBI guidelines, and step-by-step actions to stop abuse. Contact AMA Legal Solutions for debt settlement help.",
  keywords: [
    "loan settlement",
    "debt settlement",
    "personal loan settlement",
    "credit card settlement",
    "recovery agent harassment",
    "borrower rights",
    "RBI guidelines",
    "legal notice",
    "loan default",
    "debt resolution",
    "banking lawyer",
    "financial hardship"
  ],
  alternates: {
    canonical: 'https://www.amalegalsolutions.com/what-to-do-if-recovery-agents-harass-you',
  },
};

export default function RecoveryHarassmentPage() {
  const tocSections = [
    { id: "introduction", title: "Introduction" },
    { id: "difference", title: "Legal Recovery vs Harassment" },
    { id: "borrower-rights", title: "Borrower Rights Under RBI" },
    { id: "step-by-step", title: "Step-by-Step Guide" },
    { id: "debt-settlement", title: "Debt Settlement Solution" },
    { id: "mistakes", title: "Mistakes to Avoid" },
    { id: "professional-help", title: "Professional Help" },
    { id: "faqs", title: "FAQs" }
  ];

  const breadcrumbItems = [
    { label: "What To Do If Recovery Agents Harass You", href: "/what-to-do-if-recovery-agents-harass-you" },
  ];

  return (
    <>
      <Script id="breadcrumb-schema" type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }} />
      <Script id="article-schema" type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(articleSchema) }} />
      <Script id="faq-schema" type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />

      <div className="bg-gray-50 min-h-screen font-sans text-gray-800">
        {/* Hero Section */}
        <div className="relative bg-[#1a202c] text-white">
          <div className="absolute inset-0 bg-black opacity-50 z-10"></div>
          <div className="absolute inset-0 bg-cover bg-center z-0" style={{ background: "black" }}></div>
          <div className="relative z-20 container mx-auto px-4 py-12 md:py-32 text-center">
            <h1 className="text-2xl md:text-6xl font-bold mb-4 md:mb-6 leading-tight mt-10">
              What Should I Do If <span className="text-[#D2A02A]">Recovery Agents Are Harassing Me?</span>
            </h1>
            <p className="text-sm md:text-2xl mb-6 md:mb-10 max-w-3xl mx-auto text-gray-200">
              The Complete Legal Guide for Borrowers to understand your rights, stop the abuse, and find permanent debt resolution.
            </p>
            <Link href="/contact">
              <button className="bg-[#D2A02A] hover:bg-[#b88a22] text-white font-bold py-3 px-6 md:py-4 md:px-10 rounded-full transition-all transform hover:scale-105 shadow-lg text-sm md:text-lg">
                Get Expert Legal Help Now
              </button>
            </Link>
          </div>
        </div>

        <div className="container mx-auto px-4 max-w-[1600px] py-8">
          <Breadcrumbs items={breadcrumbItems} />
          
          <div className="grid grid-cols-1 lg:grid-cols-[220px_1fr_280px] gap-8 items-start">
            <div className="hidden lg:block sticky top-24">
              <TableOfContents sections={tocSections} orientation="vertical" />
            </div>

            <div className="min-w-0">
              <div className="lg:hidden mb-6 sticky top-20 z-10">
                <TableOfContents sections={tocSections} />
              </div>

              <div className="bg-white p-3 md:p-12 rounded-2xl shadow-sm space-y-6 md:space-y-12">
                
                <section id="introduction" className="scroll-mt-32">
                  <h2 className="text-xl md:text-3xl font-bold text-gray-900 mb-4 md:mb-6">You Are Not Alone, and You Have Rights</h2>
                  <p className="text-sm md:text-lg leading-relaxed mb-3 md:mb-6 text-gray-700">
                    Falling into loan default due to financial hardship is incredibly stressful. Whether it is a sudden job loss, a medical emergency, a business failure, or unforeseen family expenses, financial difficulties can happen to anyone. However, the anxiety of debt is often overshadowed by a much more immediate and terrifying problem: <strong>recovery agent harassment</strong>.
                  </p>
                  <p className="text-sm md:text-lg leading-relaxed mb-3 md:mb-6 text-gray-700">
                    If you are receiving dozens of abusive calls a day, if agents are threatening you, visiting your workplace to humiliate you, or calling your friends and family members, you might feel trapped and hopeless.
                  </p>
                  <div className="bg-white border-l-4 border-red-500 shadow-sm p-6 md:p-8 rounded-r-xl mb-10">
                    <p className="text-lg md:text-xl font-medium leading-relaxed text-gray-800">
                      <strong>Important Rule:</strong> Defaulting on a loan is a civil matter, not a criminal offense, and you have strong borrower rights protected by the Reserve Bank of India (RBI) and the Indian legal system. No bank, NBFC, or third-party collection agency has the right to abuse, threaten, or humiliate you to recover debt.
                    </p>
                  </div>
                  <h3 className="text-lg md:text-2xl font-bold text-gray-800 mb-3">Featured Quick Guide</h3>
                  <div className="bg-blue-50 border-l-4 border-blue-500 p-4 md:p-6 mb-4 md:mb-8 rounded-r-lg">
                    <p className="text-sm md:text-lg text-blue-900 font-semibold mb-2">
                      What should I do if recovery agents are harassing me?
                    </p>
                    <p className="text-sm md:text-lg text-blue-900">
                      If recovery agents are harassing you, you should first firmly tell them to stop and start recording all phone calls. Under RBI guidelines, agents cannot call outside the hours of 8 AM to 7 PM, use abusive language, or contact your friends, family, or employer. Immediately file a formal written complaint with your bank's grievance redressal officer. If the harassment continues, you should file a complaint with the RBI Ombudsman, register a police FIR for criminal intimidation, and hire a banking lawyer to send a formal cease-and-desist legal notice to the bank.
                    </p>
                  </div>
                </section>

                <section id="difference" className="scroll-mt-32">
                  <h2 className="text-xl md:text-3xl font-bold text-gray-900 mb-4 md:mb-6">Understanding the Difference Between Legal Recovery and Illegal Harassment</h2>
                  <p className="text-lg leading-relaxed mb-6 text-gray-700">
                    When you default on a personal loan or credit card, the lending institution has a legal right to recover their money. They are allowed to send you reminders, call you to ask for payment, and send legal notices for loan default. However, there is a very strict, legally defined line between "recovery" and "harassment."
                  </p>
                  <h3 className="text-lg md:text-2xl font-bold text-gray-800 mb-3">What Constitutes Harassment by Recovery Agents?</h3>
                  <ul className="space-y-4 text-lg text-gray-700 mb-6">
                    <li className="flex items-start bg-gray-50 p-4 rounded-lg border-l-4 border-[#D2A02A]">
                      <span className="flex-shrink-0 w-6 h-6 bg-red-100 text-red-600 rounded-full flex items-center justify-center mr-4 mt-1">
                        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"></path></svg>
                      </span>
                      <div>
                        <strong>Calling at Unreasonable Hours:</strong> RBI guidelines strictly prohibit recovery agents from calling borrowers before 8:00 AM or after 7:00 PM.
                      </div>
                    </li>
                    <li className="flex items-start bg-gray-50 p-4 rounded-lg border-l-4 border-[#D2A02A]">
                      <span className="flex-shrink-0 w-6 h-6 bg-red-100 text-red-600 rounded-full flex items-center justify-center mr-4 mt-1">
                        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"></path></svg>
                      </span>
                      <div>
                        <strong>Using Abusive or Threatening Language:</strong> The use of profanity, verbal abuse, yelling, or threats of physical violence is a criminal offense under the Indian Penal Code (IPC).
                      </div>
                    </li>
                    <li className="flex items-start bg-gray-50 p-4 rounded-lg border-l-4 border-[#D2A02A]">
                      <span className="flex-shrink-0 w-6 h-6 bg-red-100 text-red-600 rounded-full flex items-center justify-center mr-4 mt-1">
                        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"></path></svg>
                      </span>
                      <div>
                        <strong>Contacting Friends, Family, or Employers:</strong> Recovery agents have no legal right to discuss your financial matters with third parties. Calling your emergency contacts, family members, or HR department to shame you is illegal.
                      </div>
                    </li>
                    <li className="flex items-start bg-gray-50 p-4 rounded-lg border-l-4 border-[#D2A02A]">
                      <span className="flex-shrink-0 w-6 h-6 bg-red-100 text-red-600 rounded-full flex items-center justify-center mr-4 mt-1">
                        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"></path></svg>
                      </span>
                      <div>
                        <strong>Workplace Visits to Cause Humiliation:</strong> While agents can visit your registered address if you are unreachable, causing a scene at your workplace to intentionally humiliate you is strictly forbidden.
                      </div>
                    </li>
                    <li className="flex items-start bg-gray-50 p-4 rounded-lg border-l-4 border-[#D2A02A]">
                      <span className="flex-shrink-0 w-6 h-6 bg-red-100 text-red-600 rounded-full flex items-center justify-center mr-4 mt-1">
                        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"></path></svg>
                      </span>
                      <div>
                        <strong>Impersonating Legal Authorities:</strong> If a caller claims to be a police officer, an advocate from the High Court, or a CBI official to scare you into paying, this is fraud and impersonation.
                      </div>
                    </li>
                    <li className="flex items-start bg-gray-50 p-4 rounded-lg border-l-4 border-[#D2A02A]">
                      <span className="flex-shrink-0 w-6 h-6 bg-red-100 text-red-600 rounded-full flex items-center justify-center mr-4 mt-1">
                        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"></path></svg>
                      </span>
                      <div>
                        <strong>Social Media Shaming:</strong> Morphing your photos, messaging your connections on LinkedIn or Facebook, or posting about your debt online is severe harassment and cybercrime.
                      </div>
                    </li>
                  </ul>
                  <div className="overflow-x-auto mt-6">
                    <table className="w-full border-collapse border border-gray-200 rounded-lg overflow-hidden">
                      <thead>
                        <tr className="bg-gray-100">
                          <th className="p-4 text-left border-b border-gray-200 text-green-700">Legal Debt Collection (Allowed)</th>
                          <th className="p-4 text-left border-b border-gray-200 text-red-700">Illegal Harassment (Not Allowed)</th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr className="border-b border-gray-100">
                          <td className="p-4 bg-white text-gray-700">Calling between 8:00 AM and 7:00 PM.</td>
                          <td className="p-4 bg-gray-50 text-gray-700">Calling late at night, early morning, or continuously 50+ times a day.</td>
                        </tr>
                        <tr className="border-b border-gray-100">
                          <td className="p-4 bg-white text-gray-700">Professional, polite reminders about pending dues.</td>
                          <td className="p-4 bg-gray-50 text-gray-700">Using swear words, shouting, or making death threats.</td>
                        </tr>
                        <tr className="border-b border-gray-100">
                          <td className="p-4 bg-white text-gray-700">Discussing the debt solely with the borrower.</td>
                          <td className="p-4 bg-gray-50 text-gray-700">Calling relatives, friends, or colleagues to shame the borrower.</td>
                        </tr>
                        <tr className="border-b border-gray-100">
                          <td className="p-4 bg-white text-gray-700">Visiting the borrower's registered home address respectfully.</td>
                          <td className="p-4 bg-gray-50 text-gray-700">Showing up unannounced at the borrower's workplace, causing a scene.</td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                </section>

                <section id="borrower-rights" className="scroll-mt-32">
                  <h2 className="text-xl md:text-3xl font-bold text-gray-900 mb-4 md:mb-6">Know Your Borrower Rights Under RBI Guidelines</h2>
                  <p className="text-lg leading-relaxed mb-6 text-gray-700">
                    As a borrower facing financial hardship, you are shielded by the following rights:
                  </p>
                  <div className="space-y-6">
                    <div className="bg-white p-6 rounded-xl border border-gray-200 shadow-sm">
                      <h4 className="font-bold text-lg mb-2 text-[#D2A02A]">1. The Right to Privacy and Confidentiality</h4>
                      <p className="text-gray-600 text-sm">Banks are bound by a duty of confidentiality. They cannot publicly disclose your debt or share your financial information with unauthorized third parties. When recovery agents call your relatives or employer, the bank is in direct violation of this right.</p>
                    </div>
                    <div className="bg-white p-6 rounded-xl border border-gray-200 shadow-sm">
                      <h4 className="font-bold text-lg mb-2 text-[#D2A02A]">2. The Right to Respectful Treatment</h4>
                      <p className="text-gray-600 text-sm">The RBI explicitly states in its guidelines on Outsourcing of Financial Services that banks must ensure their recovery agents do not resort to intimidation or harassment, either verbal or physical.</p>
                    </div>
                    <div className="bg-white p-6 rounded-xl border border-gray-200 shadow-sm">
                      <h4 className="font-bold text-lg mb-2 text-[#D2A02A]">3. The Right to Due Process and Notice</h4>
                      <p className="text-gray-600 text-sm">Before a bank can classify your account as an NPA or take severe legal action, they must follow due process. This includes giving you adequate notice and time to respond.</p>
                    </div>
                    <div className="bg-white p-6 rounded-xl border border-gray-200 shadow-sm">
                      <h4 className="font-bold text-lg mb-2 text-[#D2A02A]">4. The Right to Raise a Grievance</h4>
                      <p className="text-gray-600 text-sm">You have the absolute right to file a complaint against the bank for the behavior of its agents. Banks are legally required to have a dedicated Grievance Redressal Mechanism.</p>
                    </div>
                  </div>
                </section>

                
                    {/* Review Snippet */}
                    <div className="my-10 bg-[#1a202c] text-white p-6 md:p-8 rounded-2xl shadow-xl relative overflow-hidden">
                      <div className="absolute top-0 right-0 p-4 opacity-10">
                        <svg className="w-32 h-32" fill="currentColor" viewBox="0 0 24 24"><path d="M14.017 21v-7.391c0-5.704 3.731-9.57 8.983-10.609l.995 2.151c-2.432.917-3.995 3.638-3.995 5.849h4v10h-9.983zm-14.017 0v-7.391c0-5.704 3.748-9.57 9-10.609l.996 2.151c-2.433.917-3.996 3.638-3.996 5.849h3.983v10h-9.983z"/></svg>
                      </div>
                      <div className="relative z-10">
                        <div className="flex text-[#D2A02A] mb-4">
                          {[...Array(5)].map((_, i) => (
                            <svg key={i} className="w-6 h-6 fill-current" viewBox="0 0 20 20"><path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" /></svg>
                          ))}
                        </div>
                        <p className="text-xl md:text-2xl italic mb-6 leading-relaxed">"The agents were calling my office HR and ruining my reputation. The moment AMA Legal Solutions sent the legal notice, the calls completely stopped. I wish I had contacted them sooner."</p>
                        <p className="font-bold text-[#D2A02A] text-lg">- Priya Sharma, Verified Client</p>
                      </div>
                    </div>

                <section id="step-by-step" className="scroll-mt-32">
                  <h2 className="text-xl md:text-3xl font-bold text-gray-900 mb-4 md:mb-6">Step-by-Step Guide: What to Do When Harassment Starts</h2>
                  <div className="relative border-l-2 border-[#D2A02A] ml-4 pl-8 space-y-12">
                    <div className="relative">
                      <div className="absolute -left-10 top-1 w-4 h-4 bg-[#D2A02A] rounded-full border-4 border-white shadow-sm"></div>
                      <h3 className="text-xl font-bold text-gray-900 mb-2">Step 1: Stay Calm and Do Not Get Provoked</h3>
                      <p className="text-gray-700">Recovery agents are trained to provoke you. When you lose your temper, you lose control of the situation. Speak in a calm, firm, and authoritative tone.</p>
                    </div>
                    <div className="relative">
                      <div className="absolute -left-10 top-1 w-4 h-4 bg-[#D2A02A] rounded-full border-4 border-white shadow-sm"></div>
                      <h3 className="text-xl font-bold text-gray-900 mb-2">Step 2: Start Documenting Everything</h3>
                      <p className="text-gray-700">Download an automatic call recorder app and record every single conversation. Take screenshots of abusive WhatsApp messages, SMS texts, and emails. Maintain a log of when they call.</p>
                    </div>
                    <div className="relative">
                      <div className="absolute -left-10 top-1 w-4 h-4 bg-[#D2A02A] rounded-full border-4 border-white shadow-sm"></div>
                      <h3 className="text-xl font-bold text-gray-900 mb-2">Step 3: Ask for Identity and Authorization</h3>
                      <p className="text-gray-700">Politely but firmly ask for their full name, ID card, agency name, DRA certification, and an official authorization letter from the bank. Most rogue agents will disconnect immediately.</p>
                    </div>
                    <div className="relative">
                      <div className="absolute -left-10 top-1 w-4 h-4 bg-[#D2A02A] rounded-full border-4 border-white shadow-sm"></div>
                      <h3 className="text-xl font-bold text-gray-900 mb-2">Step 4: Send a Formal Complaint to the Bank</h3>
                      <p className="text-gray-700">Write a detailed email to the Grievance Redressal Officer of your bank with proof, stating that you will approach the RBI Ombudsman if the harassment does not stop.</p>
                    </div>
                    <div className="relative">
                      <div className="absolute -left-10 top-1 w-4 h-4 bg-[#D2A02A] rounded-full border-4 border-white shadow-sm"></div>
                      <h3 className="text-xl font-bold text-gray-900 mb-2">Step 5: File a Police Complaint (FIR)</h3>
                      <p className="text-gray-700">If agents threaten physical harm or use extreme vulgarity, dial 112 or visit your local police station to file an FIR under sections like 503 and 506 IPC.</p>
                    </div>
                    <div className="relative">
                      <div className="absolute -left-10 top-1 w-4 h-4 bg-[#D2A02A] rounded-full border-4 border-white shadow-sm"></div>
                      <h3 className="text-xl font-bold text-gray-900 mb-2">Step 6: Escalate to the RBI Ombudsman</h3>
                      <p className="text-gray-700">If the bank does not resolve your complaint within 30 days, file a complaint on the RBI Complaint Management System (CMS) portal.</p>
                    </div>
                    <div className="relative">
                      <div className="absolute -left-10 top-1 w-4 h-4 bg-[#D2A02A] rounded-full border-4 border-white shadow-sm"></div>
                      <h3 className="text-xl font-bold text-gray-900 mb-2">Step 7: Send a Legal Notice Through a Lawyer</h3>
                      <p className="text-gray-700">Have an expert banking lawyer send a formal Cease and Desist Legal Notice to the bank. The bank will typically instantly revoke the collection agency's mandate.</p>
                    </div>
                  </div>
                </section>

                <section id="debt-settlement" className="scroll-mt-32">
                  <h2 className="text-xl md:text-3xl font-bold text-gray-900 mb-4 md:mb-6">Dealing with Harassment Through Debt Settlement</h2>
                  <p className="text-lg leading-relaxed mb-6 text-gray-700">
                    While stopping the harassment is the immediate priority, the underlying issue—your unpaid debt—still needs to be resolved. <strong>Debt Settlement (Loan Settlement)</strong> is a formal agreement where the bank agrees to accept a lump-sum payment that is significantly lower than your actual outstanding balance in cases of genuine hardship.
                  </p>
                  <p className="text-lg leading-relaxed mb-6 text-gray-700">
                    Once you engage a legal firm like AMA Legal Solutions, all communication is redirected to your legal representatives. Once the settlement amount is paid and a No Dues Certificate (NDC) is issued, no recovery agent can ever contact you regarding that account again.
                  </p>
                </section>

                <section id="mistakes" className="scroll-mt-32">
                  <h2 className="text-xl md:text-3xl font-bold text-gray-900 mb-4 md:mb-6">Common Mistakes Borrowers Make</h2>
                  <div className="grid md:grid-cols-2 gap-6">
                    <div className="bg-red-50 border border-red-200 p-6 rounded-xl shadow-sm hover:shadow-md transition">
                      <div className="flex items-center mb-3">
                        <div className="flex-shrink-0 w-10 h-10 bg-red-100 text-red-600 rounded-full flex items-center justify-center mr-4">
                          <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12"></path></svg>
                        </div>
                        <h4 className="font-bold text-red-900 text-lg">Paying Agents Directly</h4>
                      </div>
                      <p className="text-red-800 text-sm">Do not pay agents directly to stop calls. They take the commission, and the principal remains unchanged. Always pay via official bank channels.</p>
                    </div>

                    <div className="bg-red-50 border border-red-200 p-6 rounded-xl shadow-sm hover:shadow-md transition">
                      <div className="flex items-center mb-3">
                        <div className="flex-shrink-0 w-10 h-10 bg-red-100 text-red-600 rounded-full flex items-center justify-center mr-4">
                          <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12"></path></svg>
                        </div>
                        <h4 className="font-bold text-red-900 text-lg">Taking New Loans</h4>
                      </div>
                      <p className="text-red-800 text-sm">Taking high-interest loans from digital apps to pay off old ones leads to a vicious debt trap. Seek a structured legal debt resolution instead.</p>
                    </div>

                    <div className="bg-red-50 border border-red-200 p-6 rounded-xl shadow-sm hover:shadow-md transition">
                      <div className="flex items-center mb-3">
                        <div className="flex-shrink-0 w-10 h-10 bg-red-100 text-red-600 rounded-full flex items-center justify-center mr-4">
                          <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12"></path></svg>
                        </div>
                        <h4 className="font-bold text-red-900 text-lg">Abusing the Agents</h4>
                      </div>
                      <p className="text-red-800 text-sm">Stay completely calm. If you hurl abuses, they will record it and use it to justify their aggressive actions and frame you legally.</p>
                    </div>

                    <div className="bg-red-50 border border-red-200 p-6 rounded-xl shadow-sm hover:shadow-md transition">
                      <div className="flex items-center mb-3">
                        <div className="flex-shrink-0 w-10 h-10 bg-red-100 text-red-600 rounded-full flex items-center justify-center mr-4">
                          <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12"></path></svg>
                        </div>
                        <h4 className="font-bold text-red-900 text-lg">Fearing Fake Notices</h4>
                      </div>
                      <p className="text-red-800 text-sm">A WhatsApp message claiming you will be arrested in 2 hours is almost always fake. The police do not arrest for simple loan defaults.</p>
                    </div>
                  </div>
                </section>

                <section id="professional-help" className="scroll-mt-32">
                  <h2 className="text-xl md:text-3xl font-bold text-gray-900 mb-4 md:mb-6">When Should You Seek Professional Legal Help?</h2>
                  <p className="text-lg leading-relaxed mb-6 text-gray-700">
                    Dealing with major banks, aggressive collection agencies, and complex legal jargon is not something you should do alone. You should seek professional help from an expert banking lawyer immediately if:
                  </p>
                  <ul className="space-y-4 text-lg text-gray-700 mb-6">
                    <li>The harassment becomes unbearable and is affecting your mental health.</li>
                    <li>You receive a formal Legal Notice, Arbitration Notice, or Court Summons.</li>
                    <li>You need to negotiate a formal Loan Settlement or One-Time Settlement (OTS).</li>
                    <li>Agents threaten your physical safety or commit cybercrimes like morphing photos.</li>
                  </ul>
                  <div className="bg-[#1a202c] p-8 rounded-xl text-white mt-8 text-center">
                    <h3 className="text-2xl font-bold mb-4 text-[#D2A02A]">Why Choose AMA Legal Solutions?</h3>
                    <p className="text-lg mb-6">We issue powerful legal notices that force banks to recall their rogue recovery agents immediately and negotiate aggressively to secure a favorable, affordable debt settlement for you.</p>
                    <Link href="/contact">
                      <button className="bg-[#D2A02A] hover:bg-[#b88a22] text-white font-bold py-3 px-8 rounded-full transition-all">
                        Consult with our Legal Experts
                      </button>
                    </Link>
                  </div>
                </section>

                {/* FAQs Section */}
                <section id="faqs" className="scroll-mt-32">
                  <h2 className="text-xl md:text-3xl font-bold text-gray-900 mb-6 md:mb-8">Frequently Asked Questions</h2>
                  <div className="space-y-4 md:space-y-6">
                    {faqs.map((faq, index) => (
                      <div key={index} className="bg-white border border-gray-200 rounded-xl p-4 md:p-6 shadow-sm hover:shadow-md transition-shadow">
                        <h3 className="text-lg md:text-xl font-bold text-gray-900 mb-3">{faq.question}</h3>
                        <p className="text-gray-700 text-sm md:text-base leading-relaxed">{faq.answer}</p>
                      </div>
                    ))}
                  </div>
                </section>
                
              </div>
            </div>

            {/* Right Sidebar */}
            <div className="hidden lg:block space-y-6 sticky top-24">
              <div className="bg-[#1a202c] p-6 rounded-2xl shadow-sm border border-gray-100 text-white">
                <h3 className="text-xl font-bold text-[#D2A02A] mb-4">Stop the Harassment Now</h3>
                <p className="text-sm mb-4 text-gray-300">Don't let recovery agents ruin your peace of mind. Get a cease and desist notice today.</p>
                <Link href="/contact">
                  <button className="w-full bg-[#D2A02A] hover:bg-[#b88a22] text-white font-bold py-3 px-4 rounded-lg transition-colors">
                    Get Legal Help
                  </button>
                </Link>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
