import Link from "next/link";
import Script from "next/script";
import Image from "next/image";
import TableOfContents from "@/components/TableOfContents";
import Breadcrumbs from "@/components/Breadcrumbs";

// FAQ data for rendering and Schema
const faqs = [
  {
    question: "Is my US-registered Living Trust enough to manage my Indian real estate?",
    answer: "Generally, no. While Revocable Living Trusts are excellent for avoiding probate in states like California or Florida, they face significant hurdles in India. Indian Sub-Registrars and banks often do not recognize a foreign trust as a legal owner of immovable property. A jurisdiction-specific Indian will, ideally registered with the local authorities, remains the most effective and legally recognized tool for ensuring a smooth title transfer of Indian land or apartments."
  },
  {
    question: "What specific IRS forms must I file if I inherit property in India?",
    answer: "As a US tax resident, you must file IRS Form 3520 (Annual Return to Report Transactions With Foreign Trusts and Receipt of Certain Foreign Gifts) if the value of the inherited assets from a non-US person exceeds $100,000. Additionally, you may need to report the property's income on your Form 1040 and potentially disclose the asset on Form 8938 (FATCA) depending on your total foreign financial asset value."
  },
  {
    question: "How does the FBAR requirement affect my Indian estate plan?",
    answer: "The Foreign Bank and Financial Accounts (FBAR) requirement is critical. If your collective Indian bank accounts, fixed deposits, or demat accounts exceed $10,000 at any point in the year, you must disclose them to FinCEN. Your estate plan should provide your executor with a clear inventory of these accounts to ensure continuous compliance and avoid the heavy penalties that fall upon non-compliant estates."
  },
  {
    question: "Can my US-born children, who are OCI holders, inherit my family's agricultural land?",
    answer: "Yes, children with OCI status can legally inherit agricultural property, plantations, or farmhouses in India from an Indian resident. However, the process of 'mutation' (updating the revenue records) can be complex for overseas residents. A professionally drafted Indian will simplifies this process by providing the Tehsildar with clear, legally binding instructions, preventing local disputes or encroachments."
  },
  {
    question: "What is the 'Revocation Trap' that US estate lawyers often miss?",
    answer: "The Revocation Trap occurs when a standard US will template includes a clause revoking 'all prior testamentary dispositions.' If you sign such a document after creating an Indian will, you unintentionally nullify your Indian estate plan. Our cross-border drafting uses specific 'territorial carve-outs' to ensure your US and Indian documents coexist harmoniously, each governing its respective jurisdiction without interference."
  },
  {
    question: "Do I need to travel to India to register my will?",
    answer: "In many cases, no. While physical presence at the Sub-Registrar's office is the traditional route, we provide solutions that utilize apostilled documents and consular attestations. Our team handles the ground-level coordination in India, allowing you to secure your assets from the comfort of your home in the USA. This 'zero-travel' approach is a cornerstone of our NRI legal services."
  },
  {
    question: "How are Indian stock market investments (Demat accounts) handled after death?",
    answer: "Indian demat accounts require a two-step process: notifying the Depository Participant (like NSDL or CDSL) and providing a valid will or succession certificate. Without a specific Indian will mentioning these accounts and appointing a local executor, your heirs may face months of frozen assets and repetitive documentation requests from various financial institutions."
  },
  {
    question: "What are the witnessing requirements for an Indian will signed in the US?",
    answer: "An Indian will must be signed in the physical presence of at least two adult witnesses. These witnesses should not be beneficiaries mentioned in the will. To ensure the document is accepted by Indian High Courts during probate, it should be notarized by a US notary and subsequently apostilled by the Secretary of State or attested by the Indian Consulate."
  },
  {
    question: "Is there an inheritance tax in India for US citizens?",
    answer: "India does not currently impose an inheritance or estate tax (it was abolished in 1985). However, as a US citizen or Green Card holder, you are subject to the US federal estate tax system on your worldwide assets. Proper planning ensures that you utilize all available credits and avoid double taxation on any income generated by those inherited Indian assets."
  },
  {
    question: "Who should I appoint as an executor for my assets in India?",
    answer: "Ideally, you should appoint a trusted individual who is a resident of India or a professional legal firm. Dealing with Indian courts, municipal corporations, and banks requires a level of physical presence and local knowledge that a US-based executor will likely lack. This ensures the execution of your will doesn't stall due to logistics."
  },
  {
    question: "How does the Hindu Succession Act impact my estate if I live in the USA?",
    answer: "The Hindu Succession Act governs the distribution of self-acquired and ancestral property for Hindus, Sikhs, Jains, and Buddhists. Even if you live in the US, your share in Indian ancestral property is determined by this Act. Understanding concepts like 'coparcenary rights' is essential to ensure you aren't attempting to will away shares that legally belong to other family members."
  },
  {
    question: "What is the role of an Apostille in the succession process?",
    answer: "An Apostille is an international certification that makes your US-notarized documents legally 'readable' and valid in India under the Hague Convention. For an Indian will signed in the US, obtaining an Apostille from your state's Secretary of State is a vital step to ensure the document is recognized by Indian registrars and courts without further validation."
  },
  {
    question: "Can I manage my Indian bank accounts through my US Power of Attorney?",
    answer: "Most US-style Powers of Attorney (POA) are rejected by Indian banks. They typically require a POA drafted on Indian stamp paper and registered or attested by the Indian Consulate. Including specific banking clauses in your Indian will provides a more permanent and secure solution for your heirs compared to relying on a POA that often expires upon death."
  },
  {
    question: "How often should an NRI update their cross-border will?",
    answer: "A review every 3 to 5 years is recommended. Major life changes-such as birth of children, acquisition of new US real estate, or changes in US tax laws (like the TCJA sunset)-should trigger an immediate update. Additionally, changes in Indian property regulations or FEMA rules can affect how your heirs repatriate their inheritance."
  },
  {
    question: "Why can't I just use a single global will for everything?",
    answer: "Using a single global will often leads to 'Estate Paralysis.' The Indian probate process for a foreign will is significantly longer, more expensive, and more prone to challenges than if you have a local, jurisdiction-specific document. Separate wills allow for parallel administration, meaning your US and Indian estates move toward completion simultaneously rather than sequentially."
  }
];

// Breadcrumb Schema
const breadcrumbSchema = {
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  "itemListElement": [
    { "@type": "ListItem", "position": 1, "name": "Home", "item": "https://www.amalegalsolutions.com" },
    { "@type": "ListItem", "position": 2, "name": "Services", "item": "https://www.amalegalsolutions.com/services" },
    { "@type": "ListItem", "position": 3, "name": "Will Drafting for Indians in USA", "item": "https://www.amalegalsolutions.com/will-drafting-for-indians-living-in-usa" }
  ]
};

// Article Schema
const articleSchema = {
  "@context": "https://schema.org",
  "@type": "Article",
  "headline": "Will Drafting for Indians Living in USA: The Ultimate Cross-Border Legacy Guide",
  "description": "Comprehensive legal strategy for NRIs and OCIs in the USA. Learn to navigate IRS Form 3520, FBAR, Indian succession laws, and separate wills for global assets.",
  "image": "https://www.amalegalsolutions.com/services/will-banner-usa.jpg",
  "author": { "@type": "Organization", "name": "AMA Legal Solutions", "url": "https://www.amalegalsolutions.com" },
  "publisher": {
    "@type": "Organization",
    "name": "AMA Legal Solutions",
    "logo": { "@type": "ImageObject", "url": "https://www.amalegalsolutions.com/ama-legal-solutions-logo.png" }
  },
  "datePublished": "2024-04-20",
  "dateModified": "2025-04-20"
};

// FAQ Schema
const faqSchema = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  "mainEntity": faqs.map(faq => ({
    "@type": "Question",
    "name": faq.question,
    "acceptedAnswer": { "@type": "Answer", "text": faq.answer }
  }))
};

// Review Schema
const reviewSchema = {
  "@context": "https://schema.org",
  "@type": "Product",
  "name": "Will Drafting for Indians in USA",
  "image": "https://www.amalegalsolutions.com/services/will-banner-usa.jpg",
  "description": "Bespoke legal drafting for NRIs in the USA to manage properties and investments in India.",
  "brand": { "@type": "Brand", "name": "AMA Legal Solutions" },
  "aggregateRating": {
    "@type": "AggregateRating",
    "ratingValue": "4.9",
    "reviewCount": "2150"
  },
  "review": [
    {
      "@type": "Review",
      "reviewRating": { "@type": "Rating", "ratingValue": "5" },
      "author": { "@type": "Person", "name": "Dr. Sameer Patel" },
      "reviewBody": "Living in Houston, I was worried about my ancestral land in Gujarat. AMA integrated my Indian will with my US trust perfectly. Their knowledge of IRS 3520 and Indian probate is unparalleled."
    },
    {
      "@type": "Review",
      "reviewRating": { "@type": "Rating", "ratingValue": "5" },
      "author": { "@type": "Person", "name": "Priyanka Sharma" },
      "reviewBody": "The team helped me apostille my will in New York and handled the local registration in Delhi. I never had to fly back. Professional and highly efficient."
    },
    {
      "@type": "Review",
      "reviewRating": { "@type": "Rating", "ratingValue": "5" },
      "author": { "@type": "Person", "name": "Rahul Kapoor" },
      "reviewBody": "Best law firm for Indians in the US. They found a major conflict in my US documents that would have frozen my Indian accounts for years. Truly life-saving service."
    }
  ]
};

export const metadata = {
  title: "Will Drafting for Indians Living in USA | #1 NRI Succession Lawyers",
  description: "Secure your Indian legacy from the USA. Expert will drafting for NRIs and OCIs. Navigate IRS 3520, FBAR, and Indian succession laws with top cross-border attorneys.",
  keywords: [
    "will drafting for indians in usa",
    "nri will for indian property",
    "estate planning for indians in usa",
    "fbar fatca for indian assets",
    "irs form 3520 inheritance",
    "indian succession law for oci",
    "nri inheritance tax usa india"
  ],
  alternates: {
    canonical: 'https://www.amalegalsolutions.com/will-drafting-for-indians-living-in-usa',
  },
};

export default function WillDraftingUSAPage() {
  const tocSections = [
    { id: "introduction", title: "Introduction" },
    { id: "legal-bridging", title: "Global Legal Bridging" },
    { id: "the-double-will", title: "The Double Will Strategy" },
    { id: "state-compliances", title: "US State Compliance" },
    { id: "tax-disclosure", title: "IRS Tax Disclosures" },
    { id: "oci-rights", title: "OCI Succession Rights" },
    { id: "conflict-zones", title: "Legal Conflict Zones" },
    { id: "digital-legacy", title: "Digital Legacy" },
    { id: "secure-execution", title: "Secure Execution" },
    { id: "the-path-forward", title: "The Path Forward" },
    { id: "why-choose-us", title: "Why Choose Us" },
    { id: "testimonials", title: "Client Stories" },
    { id: "faqs", title: "FAQs" },
  ];

  const breadcrumbItems = [
    { label: "Services", href: "/services" },
    { label: "Will Drafting for Indians in USA", href: "/will-drafting-for-indians-living-in-usa" },
  ];

  return (
    <>
      <Script id="breadcrumb-schema" type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }} />
      <Script id="article-schema" type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(articleSchema) }} />
      <Script id="faq-schema" type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />
      <Script id="review-schema" type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(reviewSchema) }} />

      <div className="bg-gray-50 min-h-screen font-sans text-gray-800">
        {/* Hero Section - STRICTLY LIKE CANADIAN PAGE */}
        <div className="relative bg-[#1a202c] text-white">
          <div className="absolute inset-0 bg-black opacity-50 z-10"></div>
          <div 
            className="absolute inset-0 bg-cover bg-center z-0" 
            style={{ background: "black" }}
          ></div>
          <div className="relative z-20 container mx-auto px-4 py-12 md:py-32 text-center">
            <h1 className="text-2xl md:text-6xl font-bold mb-4 md:mb-6 leading-tight mt-10 uppercase tracking-tight">
               Will Drafting for <span className="text-[#D2A02A]">Indians Living in USA</span>
            </h1>
            <p className="text-sm md:text-2xl mb-6 md:mb-10 max-w-4xl mx-auto text-gray-200 leading-relaxed">
              Safeguarding the global legacies of North American Indians. We provide specialized legal architecture to protect your Indian real estate, ancestral wealth, and investments while ensuring full US tax compliance.
            </p>
            <Link href="/contact">
              <button className="bg-[#D2A02A] hover:bg-[#b88a22] text-white font-bold py-3 px-6 md:py-4 md:px-10 rounded-full transition-all transform hover:scale-105 shadow-lg text-sm md:text-lg">
                Book a Technical Consultation
              </button>
            </Link>
          </div>
        </div>

        <div className="container mx-auto px-4 max-w-[1600px] py-8">
          <Breadcrumbs items={breadcrumbItems} />
          
          {/* Mobile App Store Links - STRICTLY LIKE CANADIAN PAGE */}
          <div className="lg:hidden flex flex-col gap-3 mb-6 mt-2">
            <p className="text-sm font-semibold mb-2" style={{ color: 'rgba(210, 158, 13, 0.8)' }}>Modern Estate Management</p>
            <div className="flex gap-4">
              <Link href="https://play.google.com/store/apps/details?id=com.ama.ama_legal_solutions" target="_blank" className="hover:opacity-80 transition-opacity">
                <Image src="/newAssets/appstore.svg" alt="Google Play" width={130} height={36} className="w-[120px] h-auto" />
              </Link>
              <Link href="https://apps.apple.com/in/app/ama-legal-solutions/id6755156186" target="_blank" className="hover:opacity-80 transition-opacity">
                <Image src="/newAssets/playstore.svg" alt="Download on App Store" width={130} height={36} className="w-[120px] h-auto" />
              </Link>
            </div>
          </div>
          
          <div className="grid grid-cols-1 lg:grid-cols-[220px_1fr_280px] gap-8 items-start">
            {/* Left Sidebar - TOC (Desktop) */}
            <div className="hidden lg:block sticky top-24">
              <TableOfContents sections={tocSections} orientation="vertical" />
            </div>

            {/* Main Content Area */}
            <div className="min-w-0">
              {/* TOC (Mobile) */}
              <div className="lg:hidden mb-6 sticky top-20 z-10">
                <TableOfContents sections={tocSections} />
              </div>

              <div className="bg-white p-3 md:p-12 rounded-2xl shadow-sm space-y-6 md:space-y-12">
                
                {/* 1. Introduction */}
                <section id="introduction" className="scroll-mt-32">
                  <h2 className="text-xl md:text-3xl font-bold text-gray-900 mb-4 md:mb-6 text-balance">Securing Your Indian Heritage While Thriving in the United States</h2>
                  <p className="text-sm md:text-lg leading-relaxed mb-3 md:mb-6 text-gray-700">
                    The journey of the Indian diaspora in the USA is a narrative of extraordinary ambition and success. From the bustling tech corridors of Seattle and San Jose to the academic halls of Boston and the financial heart of New York, Indians have built a life defined by prosperity and integration. For many, this success is balanced by a profound connection to their homeland-represented by ancestral properties in Punjab, commercial real estate in Bangalore, or long-held family bank accounts in Mumbai.
                  </p>
                  <p className="text-sm md:text-lg leading-relaxed mb-3 md:mb-6 text-gray-700">
                    However, this dual identity introduces a significant legal vulnerability: the risk of 'Estate Paralysis.' When a US resident passes away without a clear, jurisdiction-specific plan for their Indian holdings, their heirs often find themselves caught in a bureaucratic nightmare. The process of <strong>will drafting for Indians living in USA</strong> is not merely a formality: it is a vital safeguard against the slow-moving Indian legal system and the potential for family disputes that can span decades.
                  </p>
                  <div className="bg-blue-50 border-l-4 border-blue-500 p-4 md:p-6 mb-4 md:mb-8 rounded-r-lg">
                    <p className="text-sm md:text-lg text-blue-900 italic">
                      "True estate protection for NRIs requires more than a simple document; it demands a strategic alignment of US probate efficiency and Indian succession requirements."
                    </p>
                  </div>
                  <p className="text-sm md:text-lg leading-relaxed text-gray-700">
                    At AMA Legal Solutions, we act as the architects of your global legacy. We ensure that your family's inheritance is transmitted with dignity and legal certainty. By addressing the unique challenges of US tax reporting and Indian property laws simultaneously, we create a bulletproof framework that protects your assets and your peace of mind across two continents.
                  </p>
                </section>

                {/* 2. Legal Bridging */}
                <section id="legal-bridging" className="scroll-mt-32">
                  <h2 className="text-xl md:text-3xl font-bold text-gray-900 mb-4 md:mb-6">Global Legal Bridging: Mastering the US-India Divide</h2>
                  <p className="text-sm md:text-lg leading-relaxed mb-6 text-gray-700">
                    Navigating cross-border succession requires a deep understanding of two fundamentally different legal philosophies. In the United States, the system is designed for administrative speed and transparency, governed primarily by state-level probate courts. Tools like the Revocable Living Trust are standard for bypassing court intervention and maintaining privacy for your American assets.
                  </p>
                  <p className="text-sm md:text-lg leading-relaxed mb-6 text-gray-700">
                    In India, the landscape is a complex tapestry of codified statutes like the Indian Succession Act 1925 and religious personal laws. For Hindus, Buddhists, Jains, and Sikhs, the Hindu Succession Act defines the rights of heirs, including the landmark 2005 amendment that granted daughters equal rights in ancestral wealth. For the Muslim diaspora, succession follows the Shariat Act, which imposes strict mandatory shares for heirs, often restricting the freedom to will away more than one-third of the total estate.
                  </p>
                  <div className="bg-gray-900 p-8 md:p-12 rounded-[2rem] text-white">
                        <h4 className="text-[#D2A02A] font-black text-xl md:text-2xl mb-6 uppercase tracking-wider underline decoration-white/20">Jurisdictional Friction Points</h4>
                        <div className="space-y-6">
                            <div className="flex gap-4 items-start">
                                <span className="bg-[#D2A02A] text-gray-900 w-8 h-8 rounded-full flex items-center justify-center font-black flex-shrink-0">A</span>
                                <p className="text-gray-300 text-sm md:text-base leading-relaxed"><strong>Probate Mismatch:</strong> A US court's order is often insufficient for Indian banks or property registrars, who frequently demand an Indian court's probate or a local will.</p>
                            </div>
                            <div className="flex gap-4 items-start">
                                <span className="bg-[#D2A02A] text-gray-900 w-8 h-8 rounded-full flex items-center justify-center font-black flex-shrink-0">B</span>
                                <p className="text-gray-300 text-sm md:text-base leading-relaxed"><strong>Trust Non-Recognition:</strong> Foreign trusts are often viewed with skepticism by Indian revenue officers, making it difficult to transfer real estate titles into a US-based trust.</p>
                            </div>
                            <div className="flex gap-4 items-start">
                                <span className="bg-[#D2A02A] text-gray-900 w-8 h-8 rounded-full flex items-center justify-center font-black flex-shrink-0">C</span>
                                <p className="text-gray-300 text-sm md:text-base leading-relaxed"><strong>Mutation Realities:</strong> Updating government records (Jamabandi or Mutation) requires specific India-compliant documentation and ground-level follow-up.</p>
                            </div>
                        </div>
                   </div>
                </section>

                {/* 3. The Double Will */}
                <section id="the-double-will" className="scroll-mt-32">
                  <h2 className="text-xl md:text-3xl font-bold text-gray-900 mb-4 md:mb-6 text-balance">The Double Will Strategy: A Specialized Approach for NRIs</h2>
                  <p className="text-sm md:text-lg leading-relaxed mb-4 md:mb-8 text-gray-700 font-medium">
                    Industry experts agree that a single 'Worldwide Will' is often an invitation to disaster for cross-border families. The most robust defense is a two-pronged approach.
                  </p>
                  <div className="grid md:grid-cols-2 gap-4 md:gap-8">
                    <div className="bg-white border border-gray-200 rounded-xl p-4 md:p-6 shadow-sm hover:shadow-md transition-shadow">
                      <h3 className="text-base md:text-xl font-bold text-[#D2A02A] mb-2 md:mb-3">Focused Jurisdictions</h3>
                      <p className="text-gray-700 text-xs md:text-base">
                        A separate Indian will allows you to precisely use local terminology (e.g., Khasra, Khatoni, Mahila share) that ensures smooth processing in Indian property offices.
                      </p>
                    </div>
                    <div className="bg-white border border-gray-200 rounded-xl p-4 md:p-6 shadow-sm hover:shadow-md transition-shadow">
                      <h3 className="text-base md:text-xl font-bold text-[#D2A02A] mb-2 md:mb-3">Procedural Parallelism</h3>
                      <p className="text-gray-700 text-xs md:text-base">
                        Your US executor can focus on assets in New Jersey or California, while your Indian executor manages bank accounts in Punjab or Delhi simultaneously, saving years of time.
                      </p>
                    </div>
                    <div className="bg-white border border-gray-200 rounded-xl p-4 md:p-6 shadow-sm hover:shadow-md transition-shadow">
                      <h3 className="text-base md:text-xl font-bold text-[#D2A02A] mb-2 md:mb-3">Legal Sanctity</h3>
                      <p className="text-gray-700 text-xs md:text-base">
                        A registered Indian will enjoys a high presumption of validity in Indian courts, making it a powerful shield against spurious claims by distant relatives or encroachers.
                      </p>
                    </div>
                    <div className="bg-white border border-gray-200 rounded-xl p-4 md:p-6 shadow-sm hover:shadow-md transition-shadow">
                      <h3 className="text-base md:text-xl font-bold text-[#D2A02A] mb-2 md:mb-3">Logistical Efficiency</h3>
                      <p className="text-gray-700 text-xs md:text-base">
                        Appointing an India-based executor for your Indian assets removes the need for your US-based family to travel to India for every bank signature or court hearing.
                      </p>
                    </div>
                  </div>
                </section>

                {/* 4. State Compliances */}
                <section id="state-compliances" className="scroll-mt-32">
                  <h2 className="text-3xl font-bold text-gray-900 mb-6 font-sans">US State Compliances: Variations That Matter</h2>
                  <p className="text-sm md:text-lg leading-relaxed mb-6 text-gray-700">
                    The foundation of your estate plan is built upon the laws of your US home state. From the community property rules of the West Coast to the elective share laws of the East, every jurisdiction requires a unique touch.
                  </p>
                  <div className="overflow-x-auto">
                    <table className="w-full border-collapse border border-gray-200 rounded-xl overflow-hidden shadow-sm">
                      <thead>
                        <tr className="bg-gray-100">
                          <th className="p-4 text-left border-b border-gray-200 text-[#D2A02A] w-1/2 font-black uppercase text-xs tracking-widest">West Coast (WA, CA) & TX</th>
                          <th className="p-4 text-left border-b border-gray-200 text-[#D2A02A] w-1/2 font-black uppercase text-xs tracking-widest">East Coast (NY, NJ, MA, VA)</th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr className="border-b border-gray-100">
                          <td className="p-4 align-top">
                            <ul className="list-disc pl-4 space-y-3 text-gray-700 text-sm md:text-base">
                              <li><strong>Marital Ownership:</strong> Community property rules mean 50% of assets belong to each spouse, influencing how Indian property is willed.</li>
                              <li><strong>Trust Integration:</strong> Heavy reliance on living trusts to maintain privacy and bypass the public probate record.</li>
                              <li><strong>Texas Efficiency:</strong> The Independent Administration option allows for a streamlined probate that is far less burdensome than other states.</li>
                            </ul>
                          </td>
                          <td className="p-4 align-top bg-gray-50">
                            <ul className="list-disc pl-4 space-y-3 text-gray-700 text-sm md:text-base">
                              <li><strong>Spousal Protection:</strong> Elective share rights ensure that a surviving spouse cannot be entirely omitted from an estate plan.</li>
                              <li><strong>Execution Rigor:</strong> Execution and witnessing rules are strictly enforced; even a minor oversight can lead to a will being contested.</li>
                              <li><strong>State Taxes:</strong> Local inheritance or estate taxes in specific states (like NJ) necessitate careful planning for cross-border beneficiaries.</li>
                            </ul>
                          </td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                </section>

                {/* 5. Tax Disclosure */}
                <section id="tax-disclosure" className="scroll-mt-32">
                  <h2 className="text-xl md:text-3xl font-bold text-gray-900 mb-4 md:mb-6">IRS Tax Disclosures: FBAR, FATCA, and the Inheritance Trap</h2>
                  <p className="text-sm md:text-lg leading-relaxed mb-6 text-gray-700">
                    A critical component of <strong>will drafting for Indians living in USA</strong> is aligning the estate with IRS transparency mandates. As a US person, your global wealth is subject to rigorous disclosure standards.
                  </p>
                  <div className="overflow-x-auto mb-8">
                    <table className="w-full text-sm text-left text-gray-500 border border-gray-200 rounded-lg">
                      <thead className="text-xs text-gray-700 uppercase bg-gray-50 font-black">
                        <tr>
                          <th scope="col" className="px-6 py-4">Reporting Obligation</th>
                          <th scope="col" className="px-6 py-4 bg-red-50 text-red-900 italic">Non-Compliance Risk</th>
                          <th scope="col" className="px-6 py-4">Fiduciary Instruction</th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr className="bg-white border-b border-gray-100">
                          <td className="px-6 py-4 font-black text-gray-900">FBAR (FinCEN 114)</td>
                          <td className="px-6 py-4 bg-red-50 text-red-900 font-bold">$12,000+ Base Penalty</td>
                          <td className="px-6 py-4">Mandatory if total foreign accounts exceed $10,000. Your executor must have an inventory of NRE/NRO accounts.</td>
                        </tr>
                        <tr className="bg-white border-b border-gray-100">
                          <td className="px-6 py-4 font-black text-gray-900">IRS Form 3520</td>
                          <td className="px-6 py-4 bg-red-50 text-red-900 font-bold">25% Value Loss</td>
                          <td className="px-6 py-4">Requires reporting of inheritances from non-US persons exceeding $100,000. Failure results in massive asset penalties.</td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                  <p className="text-sm md:text-lg leading-relaxed text-gray-700 italic border-l-4 border-[#D2A02A] pl-6 py-2">
                    Note: FATCA (Form 8938) reporting may also be required if your financial assets exceed higher thresholds, which depend on your marital status and residence abroad.
                  </p>
                </section>

                {/* 6. OCI Rights */}
                <section id="oci-rights" className="scroll-mt-32">
                  <h2 className="text-xl md:text-3xl font-bold text-gray-900 mb-4 md:mb-6">OCI Succession Rights: Navigating RBI and Property Statutes</h2>
                  <p className="text-sm md:text-lg leading-relaxed mb-6 text-gray-700">
                    For OCI holders, the right to inherit property is protected under Section 6 of the Indian Succession Act, but it is subject to the Foreign Exchange Management Act (FEMA) regulations set by the RBI.
                  </p>
                  <div className="grid md:grid-cols-2 gap-4 md:gap-6 mb-8">
                    <div className="bg-white p-6 rounded-xl border border-gray-200 shadow-sm hover:border-[#D2A02A]/40 transition-colors">
                      <h4 className="font-bold text-gray-900 text-lg mb-2 underline decoration-[#D2A02A] decoration-4">Self-Owned Property</h4>
                      <p className="text-gray-600 text-sm leading-relaxed">Assets purchased with your own independent income. You possess unfettered rights to transfer these to US citizens, charities, or any selected heir.</p>
                    </div>
                    <div className="bg-white p-6 rounded-xl border border-gray-200 shadow-sm hover:border-[#D2A02A]/40 transition-colors">
                      <h4 className="font-bold text-gray-900 text-lg mb-2 underline decoration-[#D2A02A] decoration-4">Family Ancestral Land</h4>
                      <p className="text-gray-600 text-sm leading-relaxed">Wealth passed down through the male coparcenary. Your legal authority is strictly limited to your individual interest in the collective family pool.</p>
                    </div>
                  </div>
                  <p className="text-sm md:text-lg leading-relaxed text-gray-700">
                    The complexity arises when US-born children attempt to probate these assets. Without an Indian will that satisfies local revenue officers, the process often stalls at the 'Tehsil' level, inviting encroachment from local residents or extended family members.
                  </p>
                </section>

                {/* 7. Conflict Zones */}
                <section id="conflict-zones" className="scroll-mt-32">
                  <h2 className="text-xl md:text-3xl font-bold text-gray-900 mb-4 md:mb-6">Legal Conflict Zones: The Menace of the Revocation Clause</h2>
                  <p className="text-sm md:text-lg leading-relaxed mb-6 text-gray-700">
                    Perhaps the most pervasive threat in cross-border planning is the innocent-looking 'revocation clause' found in standard American will templates.
                  </p>
                  <div className="bg-red-50 p-6 md:p-10 rounded-2xl border-l-8 border-red-500 my-6 shadow-sm">
                      <h4 className="font-bold text-red-900 text-xl mb-4 uppercase tracking-tighter">Automatic Invalidation Threat:</h4>
                      <p className="text-red-800 text-sm md:text-lg leading-relaxed mb-4">
                        A typical US will states: "I hereby revoke all former wills." If you sign this after establishing an Indian estate plan, you have legally nullified your Indian will. This leaves your Indian property in 'Intestacy'-a legal vacuum that takes years to resolve.
                      </p>
                      <p className="text-red-900 font-bold text-sm md:text-base border-t border-red-200 pt-4 mt-6">
                        The AMA Safeguard: We implement precise 'exclusion clauses' to ensure your US and Indian documents function as a unified, non-conflicting legal shield.
                      </p>
                  </div>
                </section>

                {/* 8. Digital Legacy */}
                <section id="digital-legacy" className="scroll-mt-32">
                  <h2 className="text-xl md:text-3xl font-bold text-gray-900 mb-4 md:mb-6 underline decoration-[#D2A02A]/20">Digital Legacy: Protecting Crypto and Virtual Wealth</h2>
                  <p className="text-sm md:text-lg leading-relaxed mb-6 text-gray-700">
                    In our modern age, wealth is increasingly represented by 0s and 1s. For US residents, significant value may reside in cryptocurrency wallets, Indian stock portals like Zerodha, or private digital archives.
                  </p>
                  <div className="grid md:grid-cols-2 gap-4 list-none p-0">
                     <div className="p-5 bg-gray-50 rounded-xl border border-gray-200 flex items-center gap-4 transition-all hover:bg-white hover:shadow-lg hover:-translate-y-1">
                         <span className="text-3xl">🔑</span>
                         <div>
                            <h4 className="font-bold text-sm md:text-base text-gray-900">Virtual Assets</h4>
                            <p className="text-xs text-gray-500 leading-snug">Specific authorization for executors to manage private keys and crypto exchange holdings.</p>
                         </div>
                     </div>
                     <div className="p-5 bg-gray-50 rounded-xl border border-gray-200 flex items-center gap-4 transition-all hover:bg-white hover:shadow-lg hover:-translate-y-1">
                         <span className="text-3xl">📈</span>
                         <div>
                            <h4 className="font-bold text-sm md:text-base text-gray-900">Indian Demat Accounts</h4>
                            <p className="text-xs text-gray-500 leading-snug">Legal authority to update nominations and manage portfolio transfers on Indian stock exchanges.</p>
                         </div>
                     </div>
                  </div>
                </section>

                {/* 9. Secure Execution */}
                <section id="secure-execution" className="scroll-mt-32">
                   <h2 className="text-xl md:text-3xl font-bold text-gray-900 mb-4 md:mb-6">Execution Protocol: Witnessing, Notarization, and Apostille</h2>
                   <p className="text-sm md:text-lg leading-relaxed mb-6 text-gray-700">
                    A will is only as strong as its execution. For an Indian document signed on American soil, the legal formalities must be impeccable to withstand a challenge in the Indian High Court.
                  </p>
                   <div className="bg-gray-900 p-8 md:p-12 rounded-[2rem] text-white">
                        <h4 className="text-[#D2A02A] font-black text-xl md:text-2xl mb-8 uppercase tracking-widest text-center">The Gold Standard Execution</h4>
                        <div className="space-y-8">
                            <div className="flex gap-6 items-start">
                                <span className="bg-[#D2A02A] text-gray-900 w-10 h-10 rounded-full flex items-center justify-center font-black flex-shrink-0 text-xl shadow-[0_0_15px_rgba(210,160,42,0.4)]">I</span>
                                <p className="text-gray-300 text-sm md:text-base leading-relaxed"><strong>Physical Presence:</strong> Two adult witnesses must observe the signing. India does not yet accept 'digital-only' witnessing for testamentary documents.</p>
                            </div>
                            <div className="flex gap-6 items-start">
                                <span className="bg-[#D2A02A] text-gray-900 w-10 h-10 rounded-full flex items-center justify-center font-black flex-shrink-0 text-xl shadow-[0_0_15px_rgba(210,160,42,0.4)]">II</span>
                                <p className="text-gray-300 text-sm md:text-base leading-relaxed"><strong>State Apostille:</strong> After notarization, the Apostille from the Secretary of State provides international recognition of the document's validity.</p>
                            </div>
                            <div className="flex gap-6 items-start">
                                <span className="bg-[#D2A02A] text-gray-900 w-10 h-10 rounded-full flex items-center justify-center font-black flex-shrink-0 text-xl shadow-[0_0_15px_rgba(210,160,42,0.4)]">III</span>
                                <p className="text-gray-300 text-sm md:text-base leading-relaxed"><strong>Consular Verification:</strong> Optional but highly recommended attestation by the Indian Consulate in SF, NY, or Chicago adds a layer of prima facie legal weight.</p>
                            </div>
                        </div>
                   </div>
                </section>

                {/* 10. The Path Forward */}
                <section id="the-path-forward" className="scroll-mt-32">
                  <h2 className="text-xl md:text-3xl font-bold text-gray-900 mb-4 md:mb-6 italic">The Path Forward: Navigating Two Jurisdictions Simultaneously</h2>
                  <p className="text-sm md:text-lg leading-relaxed mb-8 text-gray-700 italic border-l-4 border-gray-100 pl-6">
                    Probate-the official validation of a will-should be a parallel process across continents, not a sequential one.
                  </p>
                  <div className="space-y-10">
                    <div className="group flex flex-col md:flex-row gap-6 items-start bg-gray-50 p-8 rounded-2xl transition-all hover:bg-white hover:shadow-2xl">
                      <div className="flex-shrink-0 w-16 h-16 bg-gray-900 text-[#D2A02A] rounded-2xl flex items-center justify-center text-3xl font-black group-hover:scale-110 transition-transform">🇺🇸</div>
                      <div>
                        <h3 className="text-xl font-black text-gray-900 mb-2">US Probate Operations</h3>
                        <p className="text-gray-600 text-sm md:text-base leading-relaxed">Used to unlock 401(k) accounts, family homes in Dallas or Chicago, and domestic investment portfolios. Often handled efficiently within months.</p>
                      </div>
                    </div>
                    <div className="group flex flex-col md:flex-row gap-6 items-start bg-gray-50 p-8 rounded-2xl transition-all hover:bg-white hover:shadow-2xl">
                      <div className="flex-shrink-0 w-16 h-16 bg-gray-900 text-[#D2A02A] rounded-2xl flex items-center justify-center text-3xl font-black group-hover:scale-110 transition-transform">🇮🇳</div>
                      <div>
                        <h3 className="text-xl font-black text-gray-900 mb-2">Indian Probate Operations</h3>
                        <p className="text-gray-600 text-sm md:text-base leading-relaxed">Essential for presidency towns and practically required for updating revenue records and unlocking large NRE fixed deposits throughout the country.</p>
                      </div>
                    </div>
                  </div>
                </section>

                {/* 11. Why Choose us */}
                <section id="why-choose-us" className="scroll-mt-32">
                  <h2 className="text-xl md:text-3xl font-bold text-gray-900 mb-4 md:mb-6 uppercase tracking-tight text-center">Why Leading NRIs Choose AMA Legal Solutions</h2>
                  <p className="text-sm md:text-lg leading-relaxed mb-8 text-gray-700 font-medium text-center">
                    Providing the gold standard in cross-border succession since 2012.
                  </p>
                  <div className="grid md:grid-cols-3 gap-6 text-center">
                    <div className="p-8 rounded-2xl bg-gray-50 hover:bg-[#fffdf5] border-t-4 border-transparent hover:border-[#D2A02A] transition-all shadow-sm">
                      <div className="text-5xl mb-6">🏛️</div>
                      <h3 className="font-black text-xl mb-3 text-gray-900">Transatlantic Mastery</h3>
                      <p className="text-gray-600 text-xs md:text-sm leading-relaxed">Our qualified attorneys understand the subtle interplay between US state codes and Indian personal laws.</p>
                    </div>
                    <div className="p-8 rounded-2xl bg-gray-50 hover:bg-[#fffdf5] border-t-4 border-transparent hover:border-[#D2A02A] transition-all shadow-sm">
                      <div className="text-5xl mb-6">✈️</div>
                      <h3 className="font-black text-xl mb-3 text-gray-900">Remote Registration</h3>
                      <p className="text-gray-600 text-xs md:text-sm leading-relaxed">We handle every aspect of the Indian registration process, so you can secure your legacy without leaving the US.</p>
                    </div>
                    <div className="p-8 rounded-2xl bg-gray-50 hover:bg-[#fffdf5] border-t-4 border-transparent hover:border-[#D2A02A] transition-all shadow-sm">
                      <div className="text-5xl mb-6">🛡️</div>
                      <h3 className="font-black text-xl mb-3 text-gray-900">Zero-Conflict Drafting</h3>
                      <p className="text-gray-600 text-xs md:text-sm leading-relaxed">Our drafting ensures your US assets and Indian holdings remain under perfectly aligned, non-revocable plans.</p>
                    </div>
                  </div>
                </section>

                {/* Testimonials */}
                <section id="testimonials" className="scroll-mt-32">
                  <h2 className="text-3xl font-bold text-gray-900 mb-8">Success Stories from the Diaspora</h2>
                  <div className="grid md:grid-cols-2 gap-8">
                    <div className="bg-gray-50 p-8 rounded-xl border border-gray-100 relative group overflow-hidden transition-all hover:bg-white hover:shadow-xl">
                      <div className="absolute top-0 right-0 p-4 bg-[#D2A02A]/10 rounded-bl-3xl opacity-0 group-hover:opacity-100 transition-opacity">
                         <span className="text-2xl">TX</span>
                      </div>
                      <div className="text-4xl text-[#D2A02A] absolute top-4 left-4 opacity-20 font-serif">"</div>
                      <p className="text-gray-700 italic mb-4 relative z-10 leading-relaxed">
                        "Drafting my Indian will from Houston was incredibly simple with AMA. They understood exactly how to integrate it with my Texas property plan. Highly professional cell for US NRIs."
                      </p>
                      <div className="flex items-center">
                        <div className="w-12 h-12 bg-gray-900 text-[#D2A02A] rounded-full flex items-center justify-center font-bold mr-4 shadow-md">S</div>
                        <div>
                          <p className="font-bold text-gray-900">Dr. Sameer Patel</p>
                          <p className="text-sm text-gray-500 font-medium">Physician, Houston</p>
                        </div>
                      </div>
                    </div>
                    <div className="bg-gray-50 p-8 rounded-xl border border-gray-100 relative group overflow-hidden transition-all hover:bg-white hover:shadow-xl">
                      <div className="absolute top-0 right-0 p-4 bg-[#D2A02A]/10 rounded-bl-3xl opacity-0 group-hover:opacity-100 transition-opacity">
                         <span className="text-2xl">NJ</span>
                      </div>
                      <div className="text-4xl text-[#D2A02A] absolute top-4 left-4 opacity-20 font-serif">"</div>
                      <p className="text-gray-700 italic mb-4 relative z-10 leading-relaxed">
                        "Finally, a firm that understands both FBAR compliance and Indian property mutation. They helped my heirs in NJ avoid what could have been a million-dollar tax penalty."
                      </p>
                      <div className="flex items-center">
                        <div className="w-12 h-12 bg-gray-900 text-[#D2A02A] rounded-full flex items-center justify-center font-bold mr-4 shadow-md">K</div>
                        <div>
                          <p className="font-bold text-gray-900">Rahul Kapoor</p>
                          <p className="text-sm text-gray-500 font-medium">Exec, Jersey City</p>
                        </div>
                      </div>
                    </div>
                  </div>
                </section>

                {/* FAQs */}
                <section id="faqs" className="scroll-mt-32 pt-10">
                  <h2 className="text-3xl md:text-4xl font-black text-gray-800 mb-10 border-b-2 border-[#D2A02A]/20 pb-4">
                     Frequently Asked Questions <span className="text-[#D2A02A] text-sm">(NRI SUCCESSION DESK)</span>
                  </h2>
                  <div className="space-y-8">
                    {faqs.map((faq, index) => (
                      <div key={index} className="border-b border-gray-100 pb-8 last:border-0 hover:bg-gray-50/50 p-4 transition-all rounded-xl">
                        <h3 className="text-lg md:text-xl font-black text-gray-900 mb-4 flex items-start leading-tight">
                          <span className="text-[#D2A02A] mr-4 text-2xl font-serif">Q.</span>
                          {faq.question}
                        </h3>
                        <div className="text-gray-700 leading-[1.8] pl-10 text-sm md:text-base font-medium">
                          {faq.answer}
                        </div>
                      </div>
                    ))}
                  </div>
                </section>

                {/* Local Jurisdictions Grid */}
                <section id="jurisdictions" className="scroll-mt-32 pt-10 border-t border-gray-100">
                  <h2 className="text-2xl md:text-4xl font-black text-gray-800 mb-6 uppercase tracking-tight">
                    US Jurisdictions <span className="text-[#D2A02A]">We Serve</span>
                  </h2>
                  <p className="text-gray-600 mb-10 text-sm md:text-lg leading-relaxed max-w-4xl">
                    Our cross-border legal architects provide comprehensive will drafting and estate planning services across all 50 US states, ensuring your Indian assets are protected under the specific inheritance laws of your state of residence.
                  </p>
                  
                  <div className="space-y-12">
                    {[
                      {
                        country: "USA",
                        flag: "🇺🇸",
                        states: ["Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming"]
                      }
                    ].map((item, idx) => (
                      <div key={idx} className="group">
                        <h3 className="text-xl font-black text-gray-900 mb-6 flex items-center gap-3">
                          <span className="text-2xl">{item.flag}</span>
                          All 50 States
                        </h3>
                        <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3">
                          {item.states.map((state, sIdx) => (
                            <div 
                              key={sIdx} 
                              className="bg-gray-50 border border-gray-100 p-3 rounded-xl text-xs md:text-sm font-bold text-gray-700 hover:border-[#D2A02A]/30 hover:bg-white hover:shadow-md transition-all cursor-default"
                            >
                              {state}
                            </div>
                          ))}
                        </div>
                      </div>
                    ))}
                  </div>
                </section>

                {/* Final CTA - STRICTLY LIKE CANADIAN PAGE */}
                <section className="bg-gradient-to-br from-[#1a202c] to-[#2d3748] rounded-[2rem] p-10 md:p-20 text-center text-white relative overflow-hidden shadow-2xl">
                    <div className="absolute top-0 right-0 p-20 bg-[#D2A02A]/10 rounded-full blur-3xl opacity-20"></div>
                  <div className="relative z-10">
                    <h2 className="text-2xl md:text-6xl font-black mb-6 md:mb-8 leading-tight tracking-tighter">Your Legacy Spans Continents.<br /><span className="text-[#D2A02A]">Your Will Should Too.</span></h2>
                    <p className="text-sm md:text-2xl opacity-90 mb-10 md:mb-16 max-w-4xl mx-auto leading-relaxed font-light">
                      Don't leave your hard-earned Indian wealth to the mercy of complex succession laws. Secure your family's future across the USA and India with a professionally architected estate plan today.
                    </p>
                    <div className="flex flex-col sm:flex-row gap-4 md:gap-6 justify-center">
                      <Link href="/contact" className="w-full sm:w-auto">
                        <button className="w-full bg-[#D2A02A] hover:bg-[#b88a22] text-white font-black py-4 px-10 md:py-6 md:px-16 rounded-full transition-all transform hover:scale-105 shadow-[0_20px_50px_rgba(210,160,42,0.3)] text-base md:text-2xl">
                          Start Legal Drafting Now
                        </button>
                      </Link>
                      <a href="tel:+918700343611" className="w-full sm:w-auto">
                        <button className="w-full bg-transparent border-2 border-white/30 hover:border-white hover:bg-white/5 text-white font-black py-4 px-10 md:py-6 md:px-16 rounded-full transition-all text-sm md:text-2xl">
                          Call Expert: +91-8700343611
                        </button>
                      </a>
                    </div>
                    <p className="mt-8 md:mt-12 text-xs md:text-lg opacity-60 font-medium">
                      Confidential Consultation • Global Compliance • Expert Attorneys
                    </p>
                  </div>
                </section>

              </div>
            </div>

            {/* Right Sidebar - STRICTLY LIKE CANADIAN PAGE */}
            <div className="hidden lg:block space-y-8 sticky top-24">
                {/* Contact Card */}
                <div className="bg-white p-8 rounded-[2rem] shadow-xl border border-gray-100 group transition-all hover:border-[#D2A02A]/30">
                  <h3 className="text-2xl font-black text-gray-900 mb-4 tracking-tighter leading-tight italic">Need Urgent<br />Expert Help?</h3>
                  <p className="text-gray-500 mb-8 text-sm leading-relaxed font-medium">
                    Speak directly with our senior cross-border succession desk for immediate clarity on your Indian assets.
                  </p>
                  <a href="tel:+918700343611" className="block w-full bg-[#D2A02A] text-white text-center py-4 rounded-2xl font-black hover:bg-[#b88a22] transition-colors mb-4 shadow-[0_10px_20px_rgba(210,160,42,0.2)]">
                    Call +91-8700343611
                  </a>
                  <Link href="/contact" className="block w-full border-2 border-[#D2A02A] text-[#D2A02A] text-center py-4 rounded-2xl font-black hover:bg-[#D2A02A] hover:text-white transition-all">
                    Request Strategy Call
                  </Link>
                </div>

                {/* Related Pages */}
                <div className="bg-white p-8 rounded-[2rem] shadow-xl border border-gray-100">
                  <h3 className="text-xl font-black text-gray-900 mb-6 flex items-center gap-3">
                    <span className="w-1.5 h-6 bg-[#D2A02A] rounded-full"></span>
                    Resource Links
                  </h3>
                  <ul className="space-y-4">
                    {['Will Drafting for NRI', 'Drafting of Will Guide', 'Simple Will Format', 'Real Estate Legal Help', 'Civil Litigation Services'].map((service, idx) => (
                      <li key={idx} className="group border-b border-gray-50 pb-2 last:border-0 hover:translate-x-1 transition-transform">
                        <Link href={['/will-drafting-for-nri', '/drafting-of-will', '/simple-will-format-download-free-legal-document-sample', '/services/real-estate', '/services/civil'][idx]} className="text-gray-800 hover:text-[#D2A02A] text-sm font-bold transition-colors">
                          {service} →
                        </Link>
                      </li>
                    ))}
                  </ul>
                </div>

                {/* App Download Card */}
                <div className="bg-gray-900 p-8 rounded-[2rem] shadow-2xl border border-gray-800 text-white relative overflow-hidden group">
                  <div className="absolute -right-4 -bottom-4 w-24 h-24 bg-[#D2A02A] rounded-full blur-3xl opacity-10 group-hover:opacity-20 transition-opacity"></div>
                  <h4 className="font-black mb-3 text-lg leading-tight tracking-widest text-[#D2A02A]">AMA CONNECT</h4>
                  <p className="text-[10px] text-gray-400 mb-8 font-black uppercase tracking-widest opacity-80">The NRI Legal Hub</p>
                  <p className="text-xs text-blue-50/70 mb-8 font-medium leading-relaxed">Coordinate your Indian succession matters legally from your smartphone in USA. Track status in real-time.</p>
                  <div className="space-y-4">
                    <Link href="https://play.google.com/store/apps/details?id=com.ama.ama_legal_solutions" target="_blank" className="block transform hover:scale-105 transition-transform">
                      <Image src="/newAssets/appstore.svg" alt="Google Play" width={140} height={40} className="w-full h-auto opacity-90 hover:opacity-100" />
                    </Link>
                    <Link href="https://apps.apple.com/in/app/ama-legal-solutions/id6755156186" target="_blank" className="block transform hover:scale-105 transition-transform">
                      <Image src="/newAssets/playstore.svg" alt="App Store" width={140} height={40} className="w-full h-auto opacity-90 hover:opacity-100" />
                    </Link>
                  </div>
                </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
