module.exports = `
                <section id="rights-under-indian-law" className="scroll-mt-32">
                  <h2 className="text-xl md:text-3xl font-bold text-gray-900 mb-4 md:mb-6">Your Rights Under Indian Law Against Harassment</h2>
                  
                  <h3 className="text-lg md:text-2xl font-bold text-gray-800 mb-3 mt-6">Section 503 and 506 of the Indian Penal Code (IPC)</h3>
                  <p className="text-sm md:text-lg leading-relaxed mb-4 text-gray-700">
                    To effectively protect yourself from credit card recovery harassment, it is vital to know your legal rights under the Indian Penal Code (IPC). When recovery agents cross the line from requesting payment to using threats and intimidation, they commit criminal offenses. Section 503 of the IPC defines 'Criminal Intimidation' as threatening another person with injury to their person, reputation, or property, with the intent to cause alarm or to force them to do an act they are not legally bound to do. When a recovery agent threatens to ruin your career, physically harm you, or publicly humiliate your family, they are explicitly committing criminal intimidation. Section 506 of the IPC prescribes the punishment for this offense, which can include imprisonment for up to two years, a fine, or both. If the threat is to cause death or grievous hurt, the punishment can extend to seven years in prison. Furthermore, if the agents use abusive language or gestures intended to insult the modesty of a woman, they can be charged under Section 509 of the IPC. Knowing these sections empowers you to file strong police complaints. When you visit the police station to file an FIR, specifically request that the complaint be registered under Sections 503, 506, and any other relevant sections of the IPC. Treating the harassment as a criminal act, rather than a civil dispute over a debt, fundamentally changes the legal dynamic and forces the authorities to take strict action against the perpetrators. It is essential to communicate to the police that this is not merely a complaint against a nuisance caller, but a formal report of organized extortion being carried out by individuals operating under the guise of financial services. This clear categorization ensures that your complaint is treated with the gravity it deserves under criminal law.
                  </p>
                  
                  <h3 className="text-lg md:text-2xl font-bold text-gray-800 mb-3 mt-6">The Importance of Documenting Every Threat</h3>
                  <p className="text-sm md:text-lg leading-relaxed mb-4 text-gray-700">
                    The bedrock of any successful legal action against harassment is comprehensive and meticulous documentation. Without solid evidence, it becomes a case of your word against the agency's, making it difficult for the police or the courts to intervene effectively. You must treat every interaction with a recovery agent as potential evidence. The moment you start receiving abusive calls, install a reliable call recording application on your smartphone and ensure that all incoming calls from unknown numbers are recorded. Save these recordings in multiple secure locations, such as cloud storage or an external hard drive. In addition to audio recordings, take clear, high-resolution screenshots of all text messages, WhatsApp chats, and emails that contain threats, abusive language, or unreasonable demands. If the agents send letters or notices, preserve the physical copies and scan them for digital backup. Maintain a detailed logbook or spreadsheet where you record the date, time, duration, phone number, and a brief summary of the conversation for every single call you receive. This systematic logging will prove invaluable when drafting legal notices or filing police complaints, as it demonstrates a clear pattern of systemic harassment. Remember, in legal proceedings, evidence is paramount. By diligently documenting every threat and violation, you build an undeniable case that will compel the authorities to take action and force the bank to cease their illegal recovery tactics immediately. Your documentation is your armor; without it, the legal system struggles to verify claims of abuse against well-resourced financial institutions. With it, you hold the power to hold both the recovery agents and their employing banks accountable under the full weight of Indian law.
                  </p>
                </section>
`;
