
import React from 'react';
import Link from 'next/link';

export const metadata = {
  title: 'Lawyer Opportunities & Legal Guides | AMA Legal Solutions',
  description: 'Explore comprehensive legal guides and opportunities curated by AMA Legal Solutions covering loan settlement, banking complaints, consumer rights, and more.',
};

const keywords = [
  "section 25 payment and settlement act bailable or not",
  "personal loan without cibil and income proof",
  "loan recovery agents harassment complaint",
  "does foreclosure of loan affect cibil",
  "which bank provide personal loan for cibil defaulters",
  "payment credit card standard chartered",
  "punishment for non payment of personal loan in india",
  "loan without income proof and cibil",
  "how to improve cibil score after loan settlement",
  "foreclosure charges for car loan",
  "consumer legal remedies act",
  "personal loan without cibil score and income proof",
  "meaning of settle",
  "suit filed meaning in cibil",
  "notice of arbitration meaning",
  "having multiple forms of debt generally helps your cibil score",
  "foreclosure charges on car loan",
  "bank loan settlement rules",
  "personal loan settlement",
  "personal loan for cibil defaulters from private",
  "letter for settlement of loan",
  "lawyer panel charges",
  "latest rbi guidelines for one time settlement",
  "letter of complaint to the bank manager",
  "car loan foreclosure charges",
  "loan recall notice",
  "letter of settlement of loan",
  "sample letter of complaint to bank manager",
  "arbitration notice meaning",
  "letter for loan settlement",                               
  "personal loan without cibil",
  "sample letter of complaint to bank",
  "loan consultant near me",
  "payment and settlement act section 25",
  "loan and debt consolidation",
  "self defense law in india",
  "letter of complaint to bank manager",
  "loan settlement letter",
  "loan for bad cibil",
  "settlement loan letter",
  "settlement in court",
  "personal loan without cibil check",
  "self defence laws in india",
  "is lawyer panel genuine or fake",
  "sample complaint letter to bank manager",
  "which banks offer debt consolidation loans in india",
  "which banks offer debt consolidation loans for bad credit",
  "suit filed meaning",
  "loan settlement application",
  "how to escape from cheque bounce case",
  "home loan with foreclosure",
  "nbfc personal loan for low cibil score",
  "where complaint against bank",
  "what is unsecured lending",
  "how to settle debt with credit card",
  "loan for debt consolidation",
  "personal loan closure letter format",
  "bank loan recovery rules",
  "bank settlement letter",
  "debt recovery agency in india",
  "suit filed in cibil",
  "what is unsecured loan",
  "murali law firm",
  "complaint letter bank manager",
  "how to stop 7 days loan app harassment",
  "how to get loan without cibil",
  "complaint letter to bank template",
  "extreme urgent loan for cibil defaulters",
  "what are consumer courts",
  "bank notice to customer",
  "complaint letter to bank manager",
  "where to make complaint against bank",
  "personal loan closing letter format",
  "rights of a bank",
  "settlement meaning in tamil",
  "short term loan with bad credit history",
  "what is a moratorium period",
  "complaint letter for bank manager",
  "how to lodge a complaint against a bank",
  "online loans for debt consolidation",
  "prepayment charges for car loan",
  "personal loans for cibil defaulters",
  "best debt consolidation loans in india",
  "meaning of debt trap",
  "how to check active loan on pan card",
  "foreclosure of housing loan",
  "where to file complaint against bank",
  "credit card settlement letter",
  "cibil suit filed",
  "loan overdue meaning",
  "loan waiving meaning",
  "written off loan meaning",
  "how to file complaint against a bank",
  "how to file a complaint against a bank",
  "loan recovery agent near me",
  "overdue loan meaning",
  "restructuring loan meaning",
  "recovery of loans meaning",
  "poor credit score debt consolidation loan",
  "bank complaint letter",
  "request letter to bank manager for loan",
  "cibil non suit filed",
  "instant loan for bad cibil",
  "rbi education loan rules",
  "loan overdue means",
  "loan case",
  "personal loan cibil defaulters",
  "debt recovery agents in india",
  "payday loan in delhi",
  "debt consolidation loan eligibility",
  "complaint against a bank",
  "how to file complaint against bank",
  "how to raise cibil dispute",
  "what is overdue amount",
  "definition of debt trap",
  "loan recovery agency near me",
  "how to get credit card without cibil score",
  "settlement in bank",
  " payday loan company near me",
  "letter for credit card settlement",
  "what is moratorium period",
  "how to make complaint against bank",
  "ots full form in banking",
  "complaint against bank",
  "can i get loan without cibil score",
  "cibil defaulter personal loan",
  "complaint letter format for bank",
  "whats an unsecured loan",
  "bill consolidation loan",
  "foir full form in banking",
  "what is minimum due in credit card",
  "what is debt trap",
  "final settlement payment settlement letter format",
  "what is the minimum payment on credit card",
  "rejected for loan",
  "suit filed cibil",
  "where can i file complaint against bank",
  "personal loan with default",
  "recovery of loan meaning",
  "defaulter of loans means",
  "consolidated loan companies",
  "how to remove written off on credit report",
  "bad debts meaning in hindi",
  "consolidating debt loan",
  "bad cibil loan",
  "is freed a genuine company",
  "debt consolidation loan for low credit",
  "debt consolidation loan application",
  "default on education loan",
  "self defence rules in india",
  "letter format for bank loan",
  "how to clear dpd in cibil report",
  "urgent loan for cibil defaulters",
  "cibil suit filed database",
  "used car loan for cibil defaulters",
  "loan write off meaning",
  "what are unsecured loan",
  "rbi rules for loan recovery",
  "meaning of moratorium period",
  "ots means in banking",
  "loan recovery agent rules",
  "debt meaning in tamil",
  "rbi guidelines for recovery of loans",
  "your cibil score reduces every time you check it",
  "what is unsecured loans",
  "instant loan for cibil defaulters",
  "debt trap meaning in hindi",
  "debt free company list in india",
  "waive off meaning",
  "personal loan defaulter for 10 years",
  "payment of standard chartered bank credit card",
  "raise a dispute in cibil",
  "what is minimum amount due in credit card",
  "loan app harassment",
  "settle a loan",
  "debt recovery agencies",
  "application writing to bank manager",
  "types of unsecured loans",
  "debt consolidation loan india",
  "how to check loan status online",
  "aarthi consultants private limited",
  "loan fraud complaint",
  "home loan for cibil defaulters",
  "rbi guidelines for credit card payment recovery",
  "how to remove written off from cibil",
  "hope fund loan app is rbi approved",
  "grace period for credit card payment",
  "loan recovery agency",
  "loan closing letter sample",
  "what if i pay minimum due of credit card",
  "debt consolidation in india",
  "debt recovery agent jobs",
  "lawyer panel review",
  "debt consolidation loan app",
  "cibil score is not the credit score in india",
  "payday loan in pune",
  "urgent loan with low cibil score",
  "loan close request letter",
  "debt collection agencies near me",
  "bank complaint letter format",
  "how to use credit card wisely",
  "clear credit loan app customer care number",
  "credit card what is minimum amount due",
  "meaning of minimum amount due in credit card",
  "request letter format for loan",
  "rights of banks",
  "what is credit card minimum amount due",
  "credit check score free",
  "restructured loan meaning",
  "debt consolidation loan online"
];

// Helper to slugify keywords
const slugify = (text: string) => {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)+/g, '');
};

export default function LawyerPage() {
  return (
    <main className="min-h-screen bg-[#EBE9E4] py-20 px-6">
      <div className="max-w-7xl mx-auto">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-2">
          {keywords.map((kw, index) => (
            <Link 
              key={index} 
              href={`/lawyer/${slugify(kw)}`}
              className="p-3 bg-white/40 border border-black/5 rounded-lg hover:bg-white/60 transition-all cursor-pointer group"
            >
              <h2 className="text-sm font-medium text-[#30261C] capitalize group-hover:text-[#D29E0D] transition-colors">
                {kw}
              </h2>
            </Link>
          ))}
        </div>
      </div>
    </main>
  );
}
