// src/app/sitemap.xml/route.ts
// import { MetadataRoute } from 'next'
import { db } from '@/lib/firebase'
import { collection, getDocs } from 'firebase/firestore'
import { successStories } from '@/data/success-stories'
import { locationData } from '@/app/lawyer-by-city/locationData'
import fs from 'fs';
import path from 'path';

// Reusable slugify function to perfectly match the dynamic route URLs
const slugify = (text: string) => {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)+/g, '');
};

export async function GET(): Promise<Response> {
  const blogs = await fetchAllBlogs()
  const articles = await fetchAllArticles()

  const baseUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://www.amalegalsolutions.com'

  // Build static routes
  const staticRoutes = [
    '',
    '/about',
    '/lawyer',
    '/ama-legal-solutions',
    '/reputable-debt-relief-agencies-specializing-in-unsecured-loans-in-banglore',
    '/find-reputable-debt-relief-agencies-specializing-in-unsecured-loans-in-bangalore',
    '/steps-to-apply-for-a-loan-settlement-through-a-financial-service-provider',
    '/key-benefits-and-drawbacks-of-persuing-loan-settlement',
    '/how-can-i-initiate-a-full-and-final-settlement-discussion-with-bank',
    '/how-to-check-if-a-loan-settlement-offer-is-genuine-on-digital-platforms',
    '/find-debt-settlement-services-known-for-effective-negotiation',
    '/what-are-the-income-tax-implications-of-a-settled-debt-amount',
    '/where-can-i-locate-government-approved-consumer-credit-counseling-services-in-chennai',
    '/can-i-settle-my-credit-card-dues-using-third-party-loan-settlement-companies',
    '/certified-financial-planners-who-specialize-in-debt-restructuring-and-settlement',
    '/get-contact-details-for-top-rated-debt-resolution-companies-in-india',
    '/ama-legal-solutions-application',
    '/legal-services-in-gurgaon',
    '/sales-job-vacancies-in-gurgaon',
    '/telecaller-vacancies-in-gurgaon',
    '/drafting-of-will',
    '/will-drafting-for-nri',
    '/will-drafting-for-indians-living-in-canada',
    '/will-drafting-for-indians-living-in-usa',
    '/will-drafting-for-indians-living-in-australia',
    '/will-drafting-for-indians-living-in-dubai',
    '/will-drafting-for-indians-living-in-germany',
    '/simple-will-format-download-free-legal-document-sample',
    '/rbi-new-recovery-guidelines-july-2026',
    '/googles-trusted-legal-advisor',
    '/googles-trusted-law-firm',
    '/what-is-a-reasonable-settlement-offer',
    '/get-your-trademark-in-180-days',
    '/expedited-process-for-trademark-registration',
    '/personal-loan-settlement',
    '/business-loan-settlement',
    '/car-loan-settlement',
    '/loan-settlement-services',
    '/credit-card-settlement',
    '/legal-services-in-noida',
    '/legal-services-in-delhi',
    '/legal-services-in-ghaziabad',
    '/got-an-arbitration-notice-dont-worry-we-got-you',
    '/unsecured-loan-settlement',
    '/secured-loan-settlement',
    '/trading-loan-settlement',
    '/legal-notice-to-hospital',
    '/protection-from-hospital-harrassement',
    '/overcharged-at-hospital-send-legal-notice',
    '/workplace-harassment-legal-notice-service',
    '/support-for-loan-settlement-during-medical-emergencies',
    '/loan-settlement-letter-format-noc-format',
    '/home-loan-eligibility-after-settlement',
    '/legal-notice-for-loan-settlement-harassment',
    '/p2p-crypto-scam-unfreeze-bank-account',
    '/2026-lockdown-due-to-scarcity-of-resources',
    '/lpg-cylinder-crisis-india-2026-iran-war',
    '/loan-settlement-for-borrowers-facing-economic-downturn',
    '/loan-settlement-for-borrowers-planning-financial-reset',
    '/amalegalsolutions-plan-for-building-debt-free-future-after-settlement',
    '/how-to-check-active-loan-on-your-name-in-india-step-by-step-guide',
    '/why-does-my-credit-score-drop-even-though-i-pay-on-time',
    '/is-cibil-ruined-forever-after-settlement',
    '/does-loan-settlement-affect-cibil-score',
    '/can-recovery-agents-abuse-you-legally-india',
    '/is-loan-settlement-illegal-in-india-truth',
    '/do-banks-file-fir-for-credit-card-dues',
    '/understanding-90-day-loan-default-india',
    '/how-to-identify-fake-settlement-letter',
    '/how-to-know-if-the-settlement-letter-is-valid',
    '/can-I-go-for-settlement-of-loan-now-and-remove-it-later-when-im-financially-stable',
    '/can-bank-reject-settlement-request',
    '/can-settlement-be-done-in-installments',
    '/can-guarantor-be-liable-after-settlement',
    '/how-to-stop-bajaj-recovery-agent-harassment-instantly',
    '/40L-unsecured-debt-in-india-what-to-do-self-vs-debt-settlement-program',
    '/loan-settlement-before-auction',
    '/loan-settlement-after-npa-classification',
    '/loan-settlement-vs-repayment',
    '/what-happens-after-bank-issues-recall-notice',
    '/how-to-challenge-bank-statement-account-statement',
    '/legal-rights-after-loan-default',
    '/when-to-choose-loan-settlement',
    '/reply-to-recovery-notice-format',
    '/bajaj-recovery-agent-calling-references',
    '/bajaj-recovery-agent-hacked-my-contact-list',
    '/bajaj-recovery-agent-abusing',
    '/can-debt-settlement-hurt-your-credit',
    '/can-loan-repayment-be-done-in-cash',
    '/can-debt-settlement-be-removed-from-credit-report',
    '/can-we-do-home-loan-settlement',
    '/what-happens-after-loan-settlement',
    '/what-are-the-best-loan-settlement-services-near-me',
    '/how-can-I-negotiate-a-personal-loan-settlement-with-lenders',
    '/how-to-check-your-loan-status-without-visiting-the-bank',
    '/top-10-instant-loan-apps-revolutionizing-access-to-credit-in-india',
    '/understanding-non-performing-assets-npa-what-happens-next-your-complete-guide',
    '/zero-balance',
    '/what-is-the-typical-process-for-settling-a-personal-loan-in-india',
    '/app-loan-settlement',
    '/which-companies-offer-professional-debt-settlement-services-for-personal-loans',
    '/compare-different-debt-management-and-settlement-programs-available-to-indian-consumers',
    '/cheque-bounce-notice',
    '/breach-of-contract-notice',
    '/consumer-complaint-notice',
    '/property-eviction-notice',
    '/ip-cease-desist-notice',
    '/debt-recovery-money-recovery-notice',
    '/gst-show-cause-notice-scn',
    '/income-tax-demand-notice',
    '/data-breach-privacy-notice',
    '/demand-notice-for-recovery-of-money',
    '/demand-notice-for-loan-repayment',
    '/notice-for-for-dishonoured-cheque',
    '/notice-for-recovery-of-unpaid-salary',
    '/notice-for-recovery-of-security-deposit',
    '/notice-for-recovery-of-outstanding-business-dues',
    '/notice-for-recovery-of-professional-fees',
    '/notice-for-recovery-from-tenant-landlord',
    '/notice-to-employer-for-wrongful-termination',
    '/notice-to-employer-for-non-payment-of-salary-or-benefits',
    '/notice-to-employer-for-workplace-harassment',
    '/notice-to-employee-for-misconduct',
    '/notice-to-employee-for-breach-of-employment-contract',
    '/notice-to-employee-for-absenteeism-negligence',
    '/notice-for-recovery-of-company-assets-from-employee',
    '/legal-notice-for-illegal-termination',
    '/legal-notice-for-credit-card-recovery-harassment-dues',
    '/legal-notice-against-nbfc',
    '/rbi-guideline-violation-complaint',
    '/debt-settlement-agreement-drafting',
    '/notice-for-cibil-correction-after-settlement',
    '/legal-help-for-loan-defaulters',
    '/one-time-settlement-ots-legal-assistance',
    '/consumer-complaint-against-finance-company',
    '/best-law-firms-in-india-for-corporate-law',
    '/legal-notice-for-partnership-dispute',
    '/legal-notice-for-experience-letter-and-releiving-letter',
    '/lawyer-by-city',
    '/contact',
    '/careers',
    '/careers/business-development-associate',
    '/careers/legal-associate',
    '/careers/sde-intern',
    '/blog',
    '/articles',
    '/ama-live',
    '/ask-me-anything',
    '/locations',
    '/best-advocate-near-me',
    '/best-law-firm-near-me',
    '/legal-services-near-me',
    '/delhi-ncr-law-firm',
    '/job-lost-loan-settlement',
    '/10-lakhs-loan-settlement',
    '/locations/bengaluru',
    '/trademark-registration-agency-near-me',
    '/trademark-registration-office-delhi',
    '/trademark-opposition-procedure',
    '/locations/chennai',
    '/locations/jaipur',
    '/locations/kolkata',
    '/locations/mumbai',
    '/locations/newdelhi',
    '/locations/telangana',
    '/locations/uttar-pradesh',
    '/locations/uttarakhand',
    '/locations/haryana',
    "/locations/punjab",
    "/locations/rajasthan",
    "/locations/chandigarh",
    "/locations/tamil-nadu",
    "/locations/kerala",
    "/locations/mizoram",
    "/services",
    '/services/arbitration',
    '/services/banking-and-finance',
    '/services/civil',
    '/services/corporate',
    '/services/criminal-law',
    '/services/cyber',
    '/services/drafting',
    '/services/entertainment',
    '/services/intellectual-property-rights',
    '/services/litigation',
    '/services/loan-settlement',
    '/services/real-estate',
    '/services/trademark-registration',
    '/services/how-to-register-trademark-with-ipindia',
    '/services/expert-vakil-search-for-trademark-registration',
    '/services/quick-company-registration-and-trademark',
    '/services/comprehensive-guide-trademark-registration-india',
    '/services/trademark-search',
    '/services/trademark-status',
    '/steps-to-trademark-registration',
    '/trademark-registration-fees',
    '/how-much-time-it-takes-to-get-your-trademark-registered',
    '/get-fssai-licence-in-7-days',
    '/how-to-register-fssai-licence',
    '/where-to-register-trademark',
    '/msme-registration',
    '/can-i-register-my-trademark-by-myself',
    '/what-documents-are-required-for-trademark-registration',
    '/is-gst-required-for-trademarks',
    '/is-trademark-registration-mandatory-to-sell-on-amazon',
    '/which-is-better-tm-or-r',
    '/trademark-objection-reply-procedure',
    '/can-i-sell-my-products-without-trademark',
    '/how-can-i-get-trademark-certificate',
    '/validity-of-trademark-registration',
    '/send-legal-notice',
    '/send-legal-notice-haryana',
    '/send-legal-notice-in-delhi',
    '/send-legal-notice-in-gurugram',
    '/send-legal-notice-in-noida',
    '/send-legal-notice-in-punjab',
    '/send-legal-notice-in-uttar-pradesh',
    '/how-can-i-send-legal-notice',
    '/ourhistory',
    '/present',
    '/ourvision',
    '/privacy-policy',
    '/special-lok-adalat-for-challan',
    '/terms-and-conditions',
    '/trademark-registration-in-class-35',
    '/trademark-registration-in-class-38',
    '/trademark-registration-in-class-14',
    '/trademark-registration-in-class-45',
    '/author/anuj-anand-malik',
    '/author/shrey-arora',
    '/which-one-is-the-real-amalegalsolutions',
    // Specific Loan Settlement State Pages
    '/services/loan-settlement/andhra-pradesh',
    '/services/loan-settlement/assam',
    '/services/loan-settlement/bihar',
    '/services/loan-settlement/chhattisgarh',
    '/services/loan-settlement/delhi',
    '/services/loan-settlement/goa',
    '/services/loan-settlement/gujarat',
    '/services/loan-settlement/haryana',
    '/services/loan-settlement/jharkhand',
    '/services/loan-settlement/kerala',
    '/services/loan-settlement/maharashtra',
    '/services/loan-settlement/manipur',
    '/services/loan-settlement/meghalaya',
    '/services/loan-settlement/mizoram',
    '/services/loan-settlement/odisha',
    '/services/loan-settlement/puducherry',
    '/services/loan-settlement/punjab',
    '/services/loan-settlement/rajasthan',
    '/services/loan-settlement/sikkim',
    '/services/loan-settlement/telangana',
    '/services/loan-settlement/tripura',
    '/services/loan-settlement/uttar-pradesh',
    '/services/loan-settlement/uttarakhand',
    '/services/loan-settlement/arunachal-pradesh',
    '/services/loan-settlement/himachal-pradesh',
    '/services/loan-settlement/madhya-pradesh',
    '/services/loan-settlement/tamil-nadu',
    '/services/loan-settlement/west-bengal',
    '/services/loan-settlement/jammu-and-kashmir',
    '/services/loan-settlement/ladakh',
    '/services/loan-settlement/lakshadweep',
    '/services/loan-settlement/andaman-nicobar',
    '/services/loan-settlement/chandigarh',
    '/services/loan-settlement/daman-diu',
    // Specific Loan Settlement City Pages
    '/services/loan-settlement/ghaziabad',
    '/services/loan-settlement/gurugram',
    '/services/loan-settlement/jaipur',
    '/services/loan-settlement/hyderabad',
    '/services/loan-settlement/kanpur',
    '/services/loan-settlement/mumbai',
    '/services/loan-settlement/noida',
    '/services/loan-settlement/pune',
    '/services/loan-settlement/surat',
    '/what-loan-settlement-service-can-help-me-reduce-my-outstanding-debt-quickly',
    '/which-companies-offer-the-best-loan-settlement-plans-for-personal-loans',
    '/where-can-i-find-reliable-loan-settlement-services-with-flexible-payment-options',
    '/who-provides-loan-settlement-solutions-with-minimal-processing-fees',
    '/which-firms-specialize-in-negotiating-settlements-for-unsecured-loans',
    '/what-loan-settlement-services-have-good-customer-support-in-india',
    '/can-i-get-a-loan-settlement-service-that-handles-home-loan-dues',
    '/free-loan-settlement-guide',
    '/how-to-negotiate-a-loan-settlement-with-lenders-online',
    '/not-being-paid-fnf-want-to-send-legal-notice',
    '/is-trademark-registration-one-time',
    '/what-is-ots',
    '/procedure-of-sending-legal-notice',
    '/credit-card-settlement-process-india',
    '/compare-loan-settlement-companies-that-work-with-personal-loans',
    '/can-bank-file-case-for-personal-loan',
    '/does-foreclosure-of-loan-affect-cibil',
    '/expert-panel-loan-settlement-reviews',
    '/which-bank-provide-personal-loan-for-cibil-defaulters',
    '/loan-recovery-agent-harassment-complaint-online',
    '/loan-recovery-agents-harassment-complaint',
    '/how-do-i-stop-recovery-agent-from-coming-home',
    '/bajaj-finance-agent-visiting-home',
    '/special-lok-adalat-for-loan-settlement',
    '/virtual-inhouse-councel',
    '/how-to-settle-loans-above-1-crore',
    '/how-to-settle-loans-above-5-crore',
    '/loan-settlement-near-me',
    '/loan-settlement-amount-calculator',
    '/how-to-settle-loan-with-bank',
    '/how-long-does-a-settled-tag-stay-on-my-report',
    '/documents-needed-for-loan-settlement-noc',
    '/loan-settlement-companies',
    '/best-time-for-loan-settlement',
    '/charities-that-pay-off-debt',
    '/benefits-of-settling-your-loan-in-march',
    '/trademark-infringement-without-registration',
    '/is-registering-a-name-instead-of-the-logo-enough',
    '/is-trademark-internationally-valid',
    '/services/loan-settlement/lok-adalat',
    '/employer-not-paying-salary-after-resignation',
    '/can-company-hold-my-salary-after-resignation',
    '/where-to-file-a-complaint-if-your-employer-doesnt-pay-you',
    '/ama-legal-solutions',
    '/is-loan-settlement-in-installments-possible',
    '/loan-settlement-process-in-hindi',
    '/can-i-settle-my-loan-without-a-lawyer',
    '/does-settlement-impact-a-co-borrower',
    '/can-i-convert-settled-to-closed-later',
    // Hardcoded Bank Specific Pages (left intact for backwards compatibility)
    '/services/loan-settlement/sbi-bank',
    '/services/loan-settlement/hdfc-bank',
    '/services/loan-settlement/idfc-bank',
    '/services/loan-settlement/icici-bank',
    '/services/loan-settlement/kotak-mahindra',
    '/services/loan-settlement/cred',
    '/top-loan-settlement-services-with-good-customer-reviews',
    '/services/loan-settlement/fibe',
    '/services/loan-settlement/infocredit',
    '/best-apps-for-managing-loan-settlement-offers-in-India',
    '/services/loan-settlement/hsbc',
    '/services/loan-settlement/navi',
    '/services/loan-settlement/citibank',
    '/services/loan-settlement/paytm',
    '/services/loan-settlement/pnb-bank',
    '/services/loan-settlement/rbl-bank',
    '/services/loan-settlement/yes-bank',
    '/services/loan-settlement/prefr',
    '/services/loan-settlement/newtap',
    '/services/loan-settlement/bajaj-finserv',
    '/services/loan-settlement/bank-of-baroda',
    '/services/loan-settlement/hero-fincorp',
    '/services/loan-settlement/aditya-birla',
    '/services/loan-settlement/poonawalla-fincorp',
    '/services/loan-settlement/tata-capital',
    '/services/loan-settlement/federal-bank',
    '/services/loan-settlement/payu-finance',
    '/services/loan-settlement/zype',
    '/services/loan-settlement/krazybee',
    '/services/loan-settlement/au-small-finance',
    '/services/loan-settlement/northern-arc',
    '/services/loan-settlement/dmi-finance',
    '/services/loan-settlement/piramal-finance',
    '/services/loan-settlement/dbs-bank',
    '/services/loan-settlement/ndx-p2p',
    '/services/loan-settlement/south-indian-bank',
    '/services/loan-settlement/si-creva',
    '/services/loan-settlement/stashfin',
    '/services/loan-settlement/l-and-t-finance',
    '/services/loan-settlement/american-express',
    '/services/loan-settlement/standard-chartered',
    '/services/loan-settlement/true-credits',
    '/services/loan-settlement/moneyview',
    '/services/loan-settlement/vivriti-capital',
    '/services/loan-settlement/axis-bank',
    '/services/loan-settlement/mas-financial',
    '/services/loan-settlement/kisetsu-saison-finance',
    '/services/loan-settlement/indusind-bank',
    '/services/loan-settlement/smfg-india-credit',
    '/services/debt-consolidation',
    '/services/loan-and-debt-consolidation',
    '/services/best-lawyer-for-bank-harassment',
    '/how-to-get-800-credit-score-in-india',
    // Specific Banking and Finance State Pages
    '/services/banking-and-finance/andhra-pradesh',
    '/services/banking-and-finance/arunachal-pradesh',
    '/services/banking-and-finance/assam',
    '/services/banking-and-finance/bihar',
    '/services/banking-and-finance/chandigarh',
    '/services/banking-and-finance/chhattisgarh',
    '/services/banking-and-finance/delhi',
    '/services/banking-and-finance/goa',
    '/services/banking-and-finance/gujarat',
    '/services/banking-and-finance/haryana',
    '/services/banking-and-finance/himachal-pradesh',
    '/services/banking-and-finance/jammu-and-kashmir',
    '/services/banking-and-finance/jharkhand',
    '/services/banking-and-finance/karnataka',
    '/services/banking-and-finance/kerala',
    '/services/banking-and-finance/ladakh',
    '/services/banking-and-finance/madhya-pradesh',
    '/services/banking-and-finance/maharashtra',
    '/services/banking-and-finance/manipur',
    '/services/banking-and-finance/meghalaya',
    '/services/banking-and-finance/mizoram',
    '/services/banking-and-finance/nagaland',
    '/services/banking-and-finance/odisha',
    '/services/banking-and-finance/puducherry',
    '/services/banking-and-finance/punjab',
    '/services/banking-and-finance/rajasthan',
    '/services/banking-and-finance/sikkim',
    '/services/banking-and-finance/tamil-nadu',
    '/services/banking-and-finance/telangana',
    '/services/banking-and-finance/tripura',
    '/services/banking-and-finance/uttar-pradesh',
    '/services/banking-and-finance/uttarakhand',
    '/services/banking-and-finance/west-bengal',
    // Specific IPR State Pages
    '/services/intellectual-property-rights/delhi',
    '/services/intellectual-property-rights/gujarat',
    '/services/intellectual-property-rights/maharashtra',
    '/services/intellectual-property-rights/punjab',
    '/services/intellectual-property-rights/rajasthan',
    '/services/intellectual-property-rights/tamil-nadu',
    '/services/intellectual-property-rights/uttar-pradesh',
    '/services/intellectual-property-rights/andhra-pradesh',
    '/services/intellectual-property-rights/arunachal-pradesh',
    '/services/intellectual-property-rights/assam',
    '/services/intellectual-property-rights/bihar',
    '/services/intellectual-property-rights/chandigarh',
    '/services/intellectual-property-rights/chhattisgarh',
    '/services/intellectual-property-rights/jammu-and-kashmir',
    '/services/intellectual-property-rights/jharkhand',
    '/services/intellectual-property-rights/kerala',
    '/services/intellectual-property-rights/madhya-pradesh',
    '/services/intellectual-property-rights/manipur',
    '/services/intellectual-property-rights/mizoram',
    '/services/intellectual-property-rights/odisha',
    '/services/intellectual-property-rights/puducherry',
    '/services/intellectual-property-rights/telangana',
    '/services/intellectual-property-rights/tripura',
    '/services/intellectual-property-rights/uttarakhand',
    '/services/intellectual-property-rights/west-bengal'
  ].map(route => ({
    url: `${baseUrl}${route}`,
    lastModified: new Date().toISOString(),
    changeFrequency: 'weekly',
    priority: route === '' ? 1.0 : 0.8
  }))

  // Parse Banks JSON for Dynamic Bank Pages
  let dynamicBankRoutes: { url: string; lastModified: string; changeFrequency: string; priority: number; }[] = [];
  try {
    const dataPath = path.join(process.cwd(), "src/app/loan-settlement-by-bank/banks.json");
    if (fs.existsSync(dataPath)) {
      const rawData = fs.readFileSync(dataPath, "utf-8");
      const banksData = JSON.parse(rawData);

      dynamicBankRoutes = banksData.map((bank: any) => ({
        url: `${baseUrl}/loan-settlement-by-bank/${slugify(bank.company)}`,
        lastModified: new Date().toISOString(),
        changeFrequency: 'weekly',
        priority: 0.7
      }));
    } else {
      console.warn(`banks.json not found at ${dataPath}`);
    }
  } catch (error) {
    console.error('Error generating bank routes for sitemap:', error);
  }

  // Build service slug routes
  const loanSettlementServiceRoutes = generateLoanSettlementServiceRoutes(baseUrl)
  const serviceSlugRoutes = generateServiceSlugRoutes(baseUrl)

  // Build dynamic blog routes
  const blogRoutes = blogs.map(blog => ({
    url: `${baseUrl}/blog/${blog.slug}`,
    lastModified: new Date(blog.created || Date.now()).toISOString(),
    changeFrequency: 'monthly',
    priority: 0.7
  }))

  // Build dynamic article routes
  const articleRoutes = articles.map(article => ({
    url: `${baseUrl}/articles/${article.slug}`,
    lastModified: new Date(article.created || Date.now()).toISOString(),
    changeFrequency: 'monthly',
    priority: 0.7
  }))

  // Build dynamic success story routes
  const successStoryRoutes = successStories.map(story => ({
    url: `${baseUrl}/success-stories/${story.slug}`,
    lastModified: new Date().toISOString(),
    changeFrequency: 'monthly',
    priority: 0.8
  }))

  // Build lawyer-by-city routes
  const lawyerByCityRoutes = locationData.map(loc => ({
    url: `${baseUrl}/lawyer-by-city/${loc.slug}`,
    lastModified: new Date().toISOString(),
    changeFrequency: 'weekly',
    priority: 0.7
  }))

  // Build lawyer keyword routes
  const lawyerKeywordRoutes = generateLawyerKeywordRoutes(baseUrl)

  // Combine all routes, including dynamicBankRoutes
  const allRoutes = [
    ...staticRoutes,
    ...dynamicBankRoutes,
    ...loanSettlementServiceRoutes,
    ...serviceSlugRoutes,
    ...lawyerKeywordRoutes,
    ...blogRoutes,
    ...articleRoutes,
    ...successStoryRoutes,
    ...lawyerByCityRoutes
  ]

  // Generate XML
  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  ${allRoutes.map(route => `
    <url>
      <loc>${route.url}</loc>
      <lastmod>${route.lastModified}</lastmod>
      <changefreq>${route.changeFrequency}</changefreq>
      <priority>${route.priority}</priority>
    </url>
  `).join('')}
</urlset>`

  return new Response(xml, {
    headers: {
      'Content-Type': 'application/xml',
      'Cache-Control': 'public, max-age=3600, s-maxage=3600'
    }
  })
}

// Helper functions to fetch data
async function fetchAllBlogs() {
  try {
    const querySnapshot = await getDocs(collection(db, 'blogs'))
    return querySnapshot.docs.map(doc => {
      const data = doc.data()
      return {
        slug: data.slug,
        created: data.created || Date.now()
      }
    })
  } catch (error) {
    console.error('Error fetching blogs:', error)
    return []
  }
}

async function fetchAllArticles() {
  try {
    const querySnapshot = await getDocs(collection(db, 'articles'))
    return querySnapshot.docs.map(doc => {
      const data = doc.data()
      return {
        slug: data.slug,
        created: data.created || Date.now()
      }
    })
  } catch (error) {
    console.error('Error fetching articles:', error)
    return []
  }
}

// Generate service slug routes for all states and union territories
function generateServiceSlugRoutes(baseUrl: string) {
  const services = [
    'arbitration',
    'civil',
    'corporate',
    'criminal-law',
    'cyber',
    'drafting',
    'entertainment',
    'litigation',
    'real-estate'
  ]

  const states = [
    'andhra-pradesh',
    'arunachal-pradesh',
    'assam',
    'bihar',
    'chhattisgarh',
    'goa',
    'gujarat',
    'haryana',
    'himachal-pradesh',
    'jharkhand',
    'karnataka',
    'kerala',
    'madhya-pradesh',
    'maharashtra',
    'manipur',
    'meghalaya',
    'mizoram',
    'nagaland',
    'odisha',
    'punjab',
    'rajasthan',
    'sikkim',
    'tamil-nadu',
    'telangana',
    'tripura',
    'uttar-pradesh',
    'uttarakhand',
    'west-bengal'
  ]

  const unionTerritories = [
    'andaman-and-nicobar',
    'chandigarh',
    'daman-and-diu',
    'delhi',
    'jammu-and-kashmir',
    'ladakh',
    'lakshadweep',
    'puducherry'
  ]

  const allSlugs = [...states, ...unionTerritories]

  const serviceSlugRoutes = []

  for (const service of services) {
    for (const slug of allSlugs) {
      serviceSlugRoutes.push({
        url: `${baseUrl}/services/${service}/${slug}`,
        lastModified: new Date().toISOString(),
        changeFrequency: 'monthly',
        priority: 0.8
      })
    }
  }

  return serviceSlugRoutes
}

function generateLoanSettlementServiceRoutes(baseUrl: string) {
  const services = [
    "Debt Recovery Tribunal (DRT) Lawyer",
    "Appeal Against DRT Order",
    "DRT Stay Petition Filing",
    "Writ Petition in High Court Against Bank",
    "Review Petition in DRT or High Court (Loan-Related)",
    "Contempt of Court in Loan Recovery Cases",
    "Civil Suit for Recovery",
    "Recovery Case by Bank",
    "Case for Over Recovery By Bank",
    "Legal Representation in Lok Adalat for Loan Matters",
    "Loan Restructuring & Financial Strategy",
    "Loan & EMI Settlement Lawyer",
    "Loan Restructuring Lawyer",
    "Bad Loan Recovery Strategy",
    "Overdue Loan Legal Protection",
    "EMI Default Legal Advice",
    "Loan Foreclosure Assistance",
    "Strategic Negotiation & Representation",
    "Negotiation with Banks/NBFCs for Reduced Settlement Amount",
    "Secured vs Unsecured Loan Legal Strategy for Businesses",
    "Bank, NBFC & Harassment Legal Defense",
    "Bank Harassment Legal Action",
    "Recovery Agent Complaints",
    "Legal Notices to Banks & NBFCs",
    "RBI/Banking Complaints",
    "RBI and NBFC Compliance Advisory",
    "Legal Advice on RBI Ombudsman Scheme",
    "Excess Interest Charge Complaint",
    "Hidden Loan Charges Legal Support",
    "Wrong Loan Recovery Complaint Filing",
    "Fraud in Loan by Agent",
    "Fraud by Bank Case",
    "Bank Account Freezing Due to Loan Default - Legal Help",
    "Salary Garnishment Protection in Loan Case",
    "SARFAESI & Property Protection",
    "Sarfaesi Act Legal Defense",
    "Property Attachment Stay Order (Loan Default)",
    "Auction Prevention Legal Strategy",
    "Home Auction Stay & Objection",
    "Loan Against Property Dispute Lawyer",
    "Borrower Disputes & Consumer Complaints",
    "Legal for Loan Disputes",
    "Cheque Bounce (Section 138) Lawyer",
    "Co-applicant Loan Dispute Resolution",
    "Guarantor Loan Dispute Assistance",
    "Credit Score Settlement Lawyer",
    "CIBIL Score Dispute Resolution",
    "Credit Limit Misuse Dispute Resolution",
    "Wrong Loan Account Mapping/Multiple Loans Issue",
    "Unsecured Loan Legal Advisory",
    "Auto-Debit or NACH Dispute Legal Help",
    "Loan Closure Certificate Dispute Resolution",
    "Legal Help for Non-Closure of Settled Loan",
    "Settlement Letter & No-Due Certificate Dispute",
    "CIBIL Update After Settlement or OTS",
    "Consumer Court & Loan Fraud Cases",
    "Consumer Court Case for Mis-sold Loan",
    "Filing Consumer Case Against NBFC/Bank",
    "Case Against Loan Agent Misrepresentation",
    "Filing FIR for Loan Fraud",
    "Cyber Fraud Related to Loans & EMI Apps",
    "Online Loan Scam & Fraud Case Lawyer",
    "Instant Loan App Harassment Legal Help",
    "Digital & Online Loan Disputes",
    "Identity Theft & Forgery Cases",
    "Financial Abuse & Identity Theft",
    "Loan Taken in Someone Else's Name (Identity Theft Case)",
    "Dispute Over Forged Loan Signatures",
    "Legal Case for Loan Sanction Without Consent",
    "Wrong PAN or Aadhaar Usage in Loan - Legal Help",
    "Business & Corporate Loan Matters",
    "Corporate Loan Matters",
    "SME Loan Dispute Resolution",
    "Working Capital Loan Legal Help",
    "Pre/Post Loan Legal Services",
    "Legal Due Diligence for Loans",
    "Pre-loan Legal Verification",
    "Loan Agreement Drafting & Review",
    "Post-Settlement & Compliance Services",
    "Loan & Banking Legal Issues",
    "Litigation & Consumer Court Expansion",
    "Enforcement & Garnishee Protection",
    "Borrower Protection & Rights",
    "Borrower Rights Under RBI Guidelines Advisory",
    "NPA Account Legal Consultation",
    "Written Off Loan Settlement Support",
    "Debt Consolidation Legal Services",
    "Settlement Notice Drafting",
    "NBFC Fraud Complaint Handling",
    "Credit Card Settlement Legal Help",
    "Startup Loan Legal Advisory",
    "Mudra Loan Settlement Legal Help",
    "Stop Harassment by Loan Recovery Agents – Legal Protection",
    "Legal Remedies if Your Co-Signer or Guarantor Refuses to Pay the Loan",
    "Account Unfreezing & Bank Representation",
    "Account Unfreezing Legal Assistance",
    "Drafting and Filing Representations to Banks",
    "Filing Complaints to RBI Ombudsman or Approaching Court",
    "Loan Default & Recovery Freeze Defense",
    "Loan Default Account Freeze Defense",
    "Negotiations with Bank for Account Freeze",
    "NBFC for Settlement for Account Freeze",
    "Legal Intervention if Freezing Done Without Court Order",
    "Cybercrime-Related Freeze Help",
    "Legal Support if Account Frozen Due to Cyber Complaint",
    "Liaising with Cyber Cell to Close Investigation",
    "Fraud & Police Case Account Freezes",
    "Fraud Case Account Freeze Response",
    "Representation in Police or EOW Inquiries",
    "Challenging Unlawful Freezing via High Court (Writ Petition)",
    "Income Tax & Government Attachment",
    "Income Tax Attachment & Account Freeze",
    "Representation Before Income Tax Department",
    "Challenging Section 226(3) Actions or Provisional Attachments",
    "GST or Commercial Tax Freezes",
    "Defense Against GST Fraud-Related Freeze",
    "Filing Objections and Getting Orders Vacated",
    "Garnishee Order & Civil Suit Freezes",
    "Third-Party Garnishee Order Defense",
    "Application to Modify or Set Aside Garnishee Orders",
    "False Complaint or Wrongful Freeze",
    "False Complaint Account Freeze",
    "Quashing FIR or Defending Against Baseless Freezing",
    "Drafting Clarification Notices for Police/Bank",
    "KYC/AML Compliance Issues",
    "KYC/AML Compliance Freeze Resolution",
    "Advising Clients on Documentation",
    "Legal Support for Unjustified KYC Suspension",
    "Business & Corporate Account Freezes",
    "Business Account Freeze (Company/LLP)",
    "Corporate Legal Services to Get Freeze Lifted",
    "Legal Liaison with ROC/ED if Involved",
    "Emergency Legal Relief",
    "Emergency Account Access Orders",
    "Filing Interim Relief Petition for Access to Funds",
    "Representing in District Court/High Court for Urgent Relief",
    "Preventive Advisory & Legal Compliance",
    "Account Holder Legal Advisory & Compliance",
    "Advising Clients on How to Avoid Freeze Situations",
    "Drafting Power of Attorney or Settlement MoUs"
  ];

  return services.map(service => {
    const slug = service
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/(^-|-$)+/g, '');

    return {
      url: `${baseUrl}/loan-settlement-services/${slug}`,
      lastModified: new Date().toISOString(),
      changeFrequency: 'weekly' as const,
      priority: 0.8
    };
  });
}

function generateLawyerKeywordRoutes(baseUrl: string) {
  const keywords = [
    "section 25 payment and settlement act bailable or not",
    "personal loan without cibil and income proof",
    "loan recovery agents harassment complaint",
    "does foreclosure of loan affect cibil",
    "which bank provide personal loan for cibil defaulters",
    "payment credit card standard chartered",
    "punishment for non payment of personal loan in india",
    "loan without income proof and cibil",
    "how to improve cibil score after loan settlement",
    "foreclosure charges for car loan",
    "consumer legal remedies act",
    "personal loan without cibil score and income proof",
    "meaning of settle",
    "suit filed meaning in cibil",
    "notice of arbitration meaning",
    "having multiple forms of debt generally helps your cibil score",
    "foreclosure charges on car loan",
    "bank loan settlement rules",
    "personal loan settlement",
    "personal loan for cibil defaulters from private",
    "letter for settlement of loan",
    "lawyer panel charges",
    "latest rbi guidelines for one time settlement",
    "letter of complaint to the bank manager",
    "car loan foreclosure charges",
    "loan recall notice",
    "letter of settlement of loan",
    "sample letter of complaint to bank manager",
    "arbitration notice meaning",
    "letter for loan settlement",                               
    "personal loan without cibil",
    "sample letter of complaint to bank",
    "loan consultant near me",
    "payment and settlement act section 25",
    "loan and debt consolidation",
    "self defense law in india",
    "letter of complaint to bank manager",
    "loan settlement letter",
    "loan for bad cibil",
    "settlement loan letter",
    "settlement in court",
    "personal loan without cibil check",
    "self defence laws in india",
    "is lawyer panel genuine or fake",
    "sample complaint letter to bank manager",
    "which banks offer debt consolidation loans in india",
    "which banks offer debt consolidation loans for bad credit",
    "suit filed meaning",
    "loan settlement application",
    "how to escape from cheque bounce case",
    "home loan with foreclosure",
    "nbfc personal loan for low cibil score",
    "where complaint against bank",
    "what is unsecured lending",
    "how to settle debt with credit card",
    "loan for debt consolidation",
    "personal loan closure letter format",
    "bank loan recovery rules",
    "bank settlement letter",
    "debt recovery agency in india",
    "suit filed in cibil",
    "what is unsecured loan",
    "murali law firm",
    "complaint letter bank manager",
    "how to stop 7 days loan app harassment",
    "how to get loan without cibil",
    "complaint letter to bank template",
    "extreme urgent loan for cibil defaulters",
    "what are consumer courts",
    "bank notice to customer",
    "complaint letter to bank manager",
    "where to make complaint against bank",
    "personal loan closing letter format",
    "rights of a bank",
    "settlement meaning in tamil",
    "short term loan with bad credit history",
    "what is a moratorium period",
    "complaint letter for bank manager",
    "how to lodge a complaint against a bank",
    "online loans for debt consolidation",
    "prepayment charges for car loan",
    "personal loans for cibil defaulters",
    "best debt consolidation loans in india",
    "meaning of debt trap",
    "how to check active loan on pan card",
    "foreclosure of housing loan",
    "where to file complaint against bank",
    "credit card settlement letter",
    "cibil suit filed",
    "loan overdue meaning",
    "loan waiving meaning",
    "written off loan meaning",
    "how to file complaint against a bank",
    "how to file a complaint against a bank",
    "loan recovery agent near me",
    "overdue loan meaning",
    "restructuring loan meaning",
    "recovery of loans meaning",
    "poor credit score debt consolidation loan",
    "bank complaint letter",
    "request letter to bank manager for loan",
    "cibil non suit filed",
    "instant loan for bad cibil",
    "rbi education loan rules",
    "loan overdue means",
    "loan case",
    "personal loan cibil defaulters",
    "debt recovery agents in india",
    "payday loan in delhi",
    "debt consolidation loan eligibility",
    "complaint against a bank",
    "how to file complaint against bank",
    "how to raise cibil dispute",
    "what is overdue amount",
    "definition of debt trap",
    "loan recovery agency near me",
    "how to get credit card without cibil score",
    "settlement in bank",
    " payday loan company near me",
    "letter for credit card settlement",
    "what is moratorium period",
    "how to make complaint against bank",
    "ots full form in banking",
    "complaint against bank",
    "can i get loan without cibil score",
    "cibil defaulter personal loan",
    "complaint letter format for bank",
    "whats an unsecured loan",
    "bill consolidation loan",
    "foir full form in banking",
    "what is minimum due in credit card",
    "what is debt trap",
    "final settlement payment settlement letter format",
    "what is the minimum payment on credit card",
    "rejected for loan",
    "suit filed cibil",
    "where can i file complaint against bank",
    "personal loan with default",
    "recovery of loan meaning",
    "defaulter of loans means",
    "consolidated loan companies",
    "how to remove written off on credit report",
    "bad debts meaning in hindi",
    "consolidating debt loan",
    "bad cibil loan",
    "is freed a genuine company",
    "debt consolidation loan for low credit",
    "debt consolidation loan application",
    "default on education loan",
    "self defence rules in india",
    "letter format for bank loan",
    "how to clear dpd in cibil report",
    "urgent loan for cibil defaulters",
    "cibil suit filed database",
    "used car loan for cibil defaulters",
    "loan write off meaning",
    "what are unsecured loan",
    "rbi rules for loan recovery",
    "meaning of moratorium period",
    "ots means in banking",
    "loan recovery agent rules",
    "debt meaning in tamil",
    "rbi guidelines for recovery of loans",
    "your cibil score reduces every time you check it",
    "what is unsecured loans",
    "instant loan for cibil defaulters",
    "debt trap meaning in hindi",
    "debt free company list in india",
    "waive off meaning",
    "personal loan defaulter for 10 years",
    "payment of standard chartered bank credit card",
    "raise a dispute in cibil",
    "what is minimum amount due in credit card",
    "loan app harassment",
    "settle a loan",
    "debt recovery agencies",
    "application writing to bank manager",
    "types of unsecured loans",
    "debt consolidation loan india",
    "how to check loan status online",
    "aarthi consultants private limited",
    "loan fraud complaint",
    "home loan for cibil defaulters",
    "rbi guidelines for credit card payment recovery",
    "how to remove written off from cibil",
    "hope fund loan app is rbi approved",
    "grace period for credit card payment",
    "loan recovery agency",
    "loan closing letter sample",
    "what if i pay minimum due of credit card",
    "debt consolidation in india",
    "debt recovery agent jobs",
    "lawyer panel review",
    "debt consolidation loan app",
    "cibil score is not the credit score in india",
    "payday loan in pune",
    "urgent loan with low cibil score",
    "loan close request letter",
    "debt collection agencies near me",
    "bank complaint letter format",
    "how to use credit card wisely",
    "clear credit loan app customer care number",
    "credit card what is minimum amount due",
    "meaning of minimum amount due in credit card",
    "request letter format for loan",
    "rights of banks",
    "what is credit card minimum amount due",
    "credit check score free",
    "restructured loan meaning",
    "debt consolidation loan online"
  ];

  const slugify = (text: string) => {
    return text
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/(^-|-$)+/g, '');
  };

  return keywords.map(kw => ({
    url: `${baseUrl}/lawyer/${slugify(kw)}`,
    lastModified: new Date().toISOString(),
    changeFrequency: 'weekly' as const,
    priority: 0.7
  }));
}