
const getSlug = (text) => {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)+/g, '');
};

const serviceMap = {
  "loan-settlement": "loan settlement",
  "loan-settlement-kaise-kare": "loan settlement kaise kare",
  "loan-settlement-effect-on-credit-score": "loan settlement effect on credit score",
  "loan-settlement-ke-bad-cibil-score-kaise-badhaye": "loan settlement ke bad cibil score kaise badhaye",
  "loan-settlement-kya-hota-hai": "loan settlement kya hota hai",
  "loan-settlement-telugu": "loan settlement telugu",
  "loan-settlement-app": "loan settlement app",
  "loan-settlement-agency": "loan settlement agency",
  "loan-settlement-karne-se-kya-hota-hai": "loan settlement karne se kya hota hai",
  "loan-settlement-process": "loan settlement process",
  "loan-settlement-kaise-hota-hai": "loan settlement kaise hota hai",
  "loan-settlement-application": "loan settlement application",
  "loan-settlement-affect-on-credit-score": "loan settlement effect on credit score",
  "loan-settlement-app-review": "loan settlement app review",
  "loan-settlement-agency-review": "loan settlement agency review",
  "loan-settlement-advocate": "loan settlement advocate",
  "loan-settlement-and-loan-closure": "loan settlement and loan closure",
  "loan-settlement-advocate-in-kolkata": "loan settlement advocate in kolkata",
  "loan-settlement-application-in-hindi": "loan settlement application in hindi",
  "axis-bank-personal-loan-settlement": "axis bank personal loan settlement",
  "axis-bank-loan-settlement-process": "axis bank loan settlement process",
  "after-loan-settlement-cibil-score": "after loan settlement cibil score",
  "anil-ambani-loan-settlement": "anil ambani loan settlement",
  "amardeep-kadyan-loan-settlement": "amardeep kadyan loan settlement",
  "app-loan-settlement-kaise-kare": "app loan settlement kaise kare",
  "axio-loan-settlement": "axio loan settlement",
  "agar-loan-settlement-ho-jaye-to-kya-kare": "agar loan settlement ho jaye to kya kare",
  "axis-bank-car-loan-settlement": "axis bank car loan settlement",
  "auto-loan-settlement": "auto loan settlement",
  "loan-settlement-bengali": "loan settlement bengali",
  "loan-settlement-best-app": "loan settlement best app",
  "loan-settlement-bajaj-finance": "loan settlement bajaj finance",
  "loan-settlement-bangla": "loan settlement bangla",
  "loan-settlement-before-npa": "loan settlement before npa",
  "loan-repayment-by-phonepe": "loan repayment by phonepe",
  "loan-repayment-best-app": "loan repayment best app",
  "loan-repayment-bajaj-finance": "loan repayment bajaj finance",
  "loan-payment-by-credit-card": "loan payment by credit card",
  "loan-payment-by-yono-sbi": "loan payment by yono sbi",
  "bank-loan-settlement-process": "bank loan settlement process",
  "bike-loan-settlement-kaise-kare": "bike loan settlement kaise kare",
  "bajaj-personal-loan-settlement": "bajaj personal loan settlement",
  "bajaj-loan-settlement-kaise-kare": "bajaj loan settlement kaise kare",
  "best-loan-settlement-agency": "best loan settlement agency",
  "bajaj-finance-bike-loan-settlement": "bajaj finance bike loan settlement",
  "bandhan-bank-loan-settlement": "bandhan bank loan settlement",
  "bank-loan-settlement": "bank loan settlement",
  "branch-loan-settlement": "branch loan settlement",
  "best-loan-settlement-app": "best loan settlement app",
  "loan-settlement-cibil-score": "loan settlement cibil score",
  "loan-settlement-company": "loan settlement company",
  "loan-settlement-company-review": "loan settlement company review",
  "loan-settlement-call-recording": "loan settlement call recording",
  "loan-settlement-calculation": "loan settlement calculation",
  "loan-settlement-cibil": "loan settlement cibil",
  "loan-settlement-car": "loan settlement car",
  "loan-settlement-corporation": "loan settlement corporation",
  "loan-settlement-certificate": "loan settlement certificate",
  "loan-repayment-calculator": "loan repayment calculator",
  "car-loan-settlement-kaise-kare": "car loan settlement kaise kare",
  "car-loan-settlement": "car loan settlement",
  "car-loan-settlement-process": "car loan settlement process",
  "car-loan-settlement-decent-advice": "car loan settlement decent advice",
  "car-loan-settlement-kaise-hota-hai": "car loan settlement kaise hota hai",
  "car-loan-settlement-malayalam": "car loan settlement malayalam",
  "car-loan-settlement-telugu": "car loan settlement telugu",
  "car-loan-settlement-letter": "car loan settlement letter",
  "car-loan-settlement-ke-bad-cibil-score-kaise-badhaye": "car loan settlement ke bad cibil score kaise badhaye",
  "car-loan-settlement-tamil": "car loan settlement tamil",
  "loan-settlement-decent-advice": "loan settlement decent advice",
  "loan-settlement-documents": "loan settlement documents",
  "loan-settlement-disadvantages": "loan settlement disadvantages",
  "loan-settlement-details-tamil": "loan settlement details tamil",
  "loan-settlement-details": "loan settlement details",
  "loan-default-settlement": "loan default settlement",
  "home-loan-settlement-decent-advice": "home loan settlement decent advice",
  "loan-settlement-after-death": "loan settlement after death",
  "loan-repayment-details": "loan repayment details",
  "od-loan-settlement": "od loan settlement",
  "dhani-loan-settlement-process": "dhani loan settlement process",
  "dmi-loan-settlement": "dmi loan settlement",
  "dhani-loan-settlement-kaise-kare": "dhani loan settlement kaise kare",
  "drt-loan-settlement": "drt loan settlement",
  "decent-advice-loan-settlement": "decent advice loan settlement",
  "disadvantages-of-loan-settlement": "disadvantages of loan settlement",
  "loan-settlement-kitne-din-mein-hota-hai": "loan settlement kitne din mein hota hai",
  "loan-settlement-effect-on-credit-score-telugu": "loan settlement effect on credit score telugu",
  "loan-settlement-effect-on-credit-score-tamil": "loan settlement effect on credit score tamil",
  "loan-settlement-effect-on-credit-score-malayalam": "loan settlement effect on credit score malayalam",
  "loan-settlement-ela-cheyali": "loan settlement ela cheyali",
  "loan-settlement-effect-on-credit-score-kannada": "loan settlement effect on credit score kannada",
  "loan-settlement-effect": "loan settlement effect",
  "loan-settlement-effect-on-credit-score-in-hindi": "loan settlement effect on credit score in hindi",
  "loan-settlement-effect-on-cibil-score": "loan settlement effect on cibil score",
  "loan-settlement-expert": "loan settlement expert",
  "expert-panel-loan-settlement-review": "expert panel loan settlement review",
  "education-loan-settlement-process": "education loan settlement process",
  "expert-panel-loan-settlement": "expert panel loan settlement",
  "education-loan-settlement-process-tamil": "education loan settlement process tamil",
  "education-loan-settlement": "education loan settlement",
  "education-loan-settlement-in-lok-adalat": "education loan settlement in lok adalat",
  "early-salary-loan-settlement": "early salary loan settlement",
  "education-loan-settlement-kaise-kare": "education loan settlement kaise kare",
  "effect-of-loan-settlement": "effect of loan settlement",
  "bike-loan-settlement-effect-on-credit-score": "bike loan settlement effect on credit score",
  "freed-loan-settlement-review": "freed loan settlement review",
  "freed-loan-settlement": "freed loan settlement",
  "fatakpay-loan-settlement": "fatakpay loan settlement",
  "fibe-loan-settlement": "fibe loan settlement",
  "freed-loan-settlement-review-tamil": "freed loan settlement review tamil",
  "freed-loan-settlement-review-telugu": "freed loan settlement review telugu",
  "federal-bank-loan-settlement": "federal bank loan settlement",
  "flipkart-pay-later-loan-settlement": "flipkart pay later loan settlement",
  "finance-loan-settlement": "finance loan settlement",
  "finnable-loan-settlement": "finnable loan settlement",
  "loan-settlement-good-or-bad": "loan settlement good or bad",
  "loan-settlement-guru": "loan settlement guru",
  "loan-repayment-google-pay": "loan repayment google pay",
  "gold-loan-settlement-company": "gold loan settlement company",
  "loan-payment-google-pay": "loan payment google pay",
  "gold-loan-settlement": "gold loan settlement",
  "groww-loan-settlement": "groww loan settlement",
  "loan-repayment-good-day": "loan repayment good day",
  "loan-repayment-grade-10": "loan repayment grade 10",
  "loan-gcash-payment": "loan gcash payment",
  "good-score-app-se-loan-settlement-kaise-kare": "good score app se loan settlement kaise kare",
  "good-score-loan-settlement": "good score loan settlement",
  "gadi-ka-loan-settlement-kaise-kare": "gadi ka loan settlement kaise kare",
  "gold-loan-settlement-kaise-kare": "gold loan settlement kaise kare",
  "gadi-loan-settlement-kaise-kare": "gadi loan settlement kaise kare",
  "gadi-loan-settlement": "gadi loan settlement",
  "group-loan-settlement": "group loan settlement",
  "gramin-bank-loan-settlement": "gramin bank loan settlement",
  "loan-settlement-hone-ke-bad-kya-hota-hai": "loan settlement hone ke bad kya hota hai",
  "loan-settlement-hone-ke-bad-cibil-score-kaise-badhaye": "loan settlement hone ke bad cibil score kaise badhaye",
  "loan-settlement-help": "loan settlement help",
  "loan-settlement-hone-ke-bad": "loan settlement hone ke bad",
  "loan-settlement-hone-mein-kitna-time-lagta-hai": "loan settlement hone mein kitna time lagta hai",
  "loan-settlement-hdfc-bank": "loan settlement hdfc bank",
  "loan-settlement-hdfc": "loan settlement hdfc",
  "loan-repayment-harassment": "loan repayment harassment",
  "loan-payment-history": "loan payment history",
  "loan-repayment-help": "loan repayment help",
  "loan-home-loan-settlement-kaise-kare": "loan home loan settlement kaise kare",
  "hero-fincorp-loan-settlement-process": "hero fincorp loan settlement process",
  "hdb-loan-settlement-kaise-kare": "hdb loan settlement kaise kare",
  "home-credit-loan-settlement-kaise-kare": "home credit loan settlement kaise kare",
  "hdfc-loan-settlement-kaise-kare": "hdfc loan settlement kaise kare",
  "hdfc-personal-loan-settlement": "hdfc personal loan settlement",
  "home-loan-settlement-in-telugu": "home loan settlement in telugu",
  "how-to-increase-cibil-score-after-loan-settlement": "how to increase cibil score after loan settlement",
  "how-to-get-noc-after-loan-settlement": "how to get noc after loan settlement",
  "housing-loan-settlement-process": "housing loan settlement process",
  "loan-settlement-in-telugu": "loan settlement in telugu",
  "loan-settlement-in-lok-adalat": "loan settlement in lok adalat",
  "loan-settlement-is-good-or-bad": "loan settlement is good or bad",
  "loan-settlement-in-tamil": "loan settlement in tamil",
  "loan-settlement-in-court": "loan settlement in court",
  "loan-settlement-in-kannada": "loan settlement in kannada",
  "loan-settlement-in-bengali": "loan settlement in bengali",
  "loan-settlement-in-emi": "loan settlement in emi",
  "loan-settlement-in-kolkata": "loan settlement in kolkata",
  "loan-settlement-in-islam": "loan settlement in islam",
  "idfc-loan-settlement-kaise-kare": "idfc loan settlement kaise kare",
  "iarc-loan-settlement": "iarc loan settlement",
  "idfc-bank-bike-loan-settlement": "idfc bank bike loan settlement",
  "icici-personal-loan-settlement": "icici personal loan settlement",
  "idfc-personal-loan-settlement": "idfc personal loan settlement",
  "idfc-two-wheeler-loan-settlement": "idfc two wheeler loan settlement",
  "icici-bank-personal-loan-settlement": "icici bank personal loan settlement",
  "icici-bank-loan-settlement": "icici bank loan settlement",
  "indusind-bank-loan-settlement": "indusind bank loan settlement",
  "icici-loan-settlement": "icici loan settlement",
  "loan-repayment-jazzcash": "loan repayment jazzcash",
  "loan-repayment-jaldi-kaise-kare": "loan repayment jaldi kaise kare",
  "loan-repayment-journal-entry": "loan repayment journal entry",
  "loan-settlement-ki-jankari": "loan settlement ki jankari",
  "jupiter-loan-settlement": "jupiter loan settlement",
  "jumbo-loan-settlement": "jumbo loan settlement",
  "loan-settlement-kaise-nikale": "loan settlement kaise nikale",
  "loan-settlement-kaise-karaye": "loan settlement kaise karaye",
  "loan-kaise-settlement-kiya-jata-hai": "loan kaise settlement kiya jata hai",
  "hdfc-jumbo-loan-settlement-kaise-kare": "hdfc jumbo loan settlement kaise kare",
  "kcc-loan-settlement-kaise-kare": "kcc loan settlement kaise kare",
  "loan-settlement-karne-ke-baad-loan-milta-hai-ya-nahin": "loan settlement karne ke baad loan milta hai ya nahin",
  "loan-settlement-ke-bad-loan-milta-hai-kya": "loan settlement ke bad loan milta hai kya",
  "loan-settlement-karna-chahiye-ya-nahi": "loan settlement karna chahiye ya nahi",
  "loan-settlement-karne-ke-bad-cibil-score-kaise-badhaye": "loan settlement karne ke bad cibil score kaise badhaye",
  "loan-settlement-ke-bad-loan-kaise-le": "loan settlement ke bad loan kaise le",
  "kya-loan-settlement-ke-bad-bhi-loan-mil-sakta-hai": "kya loan settlement ke bad bhi loan mil sakta hai",
  "kreditbee-loan-settlement-kaise-kare": "kreditbee loan settlement kaise kare",
  "kcc-loan-settlement": "kcc loan settlement",
  "kissht-loan-settlement": "kissht loan settlement",
  "kcc-loan-settlement-in-lok-adalat": "kcc loan settlement in lok adalat",
  "kotak-personal-loan-settlement": "kotak personal loan settlement",
  "kya-home-loan-settlement-hota-hai": "kya home loan settlement hota hai",
  "kredito24-loan-settlement": "kredito24 loan settlement",
  "kreditbee-loan-settlement-letter": "kreditbee loan settlement letter",
  "loan-settlement-letter-kaisa-hota-hai": "loan settlement letter kaisa hota hai",
  "loan-settlement-letter": "loan settlement letter",
  "loan-settlement-lok-adalat": "loan settlement lok adalat",
  "loan-settlement-letter-kaise-likhe": "loan settlement letter kaise likhe",
  "loan-settlement-lawyers": "loan settlement lawyers",
  "loan-settlement-letter-in-english": "loan settlement letter in english",
  "loan-settlement-letter-telugu": "loan settlement letter telugu",
  "loan-late-payment-cibil-score": "loan late payment cibil score",
  "loan-lado-repayment": "loan lado repayment",
  "loan-settlement-malayalam": "loan settlement malayalam",
  "loan-settlement-me-kitna-paisa-lagta-hai": "loan settlement me kitna paisa lagta hai",
  "loan-settlement-mein-kya-hota-hai": "loan settlement mein kya hota hai",
  "loan-settlement-minimum-amount": "loan settlement minimum amount",
  "loan-settlement-means": "loan settlement means",
  "loan-settlement-mane-ki": "loan settlement mane ki",
  "loan-settlement-marathi": "loan settlement marathi",
  "loan-settlement-mhanje-kay": "loan settlement mhanje kay",
  "write-off-loan-settlement-malayalam": "write off loan settlement malayalam",
  "loan-monthly-payment": "loan monthly payment",
  "mpokket-loan-settlement-kaise-kare": "mpokket loan settlement kaise kare",
  "money-view-loan-settlement-kaise-kare": "money view loan settlement kaise kare",
  "mortgage-loan-settlement": "mortgage loan settlement",
  "mpokket-loan-settlement": "mpokket loan settlement",
  "mahindra-finance-car-loan-settlement": "mahindra finance car loan settlement",
  "mudra-loan-settlement": "mudra loan settlement",
  "multiple-loan-settlement": "multiple loan settlement",
  "mobikwik-loan-settlement-kaise-kare": "mobikwik loan settlement kaise kare",
  "mobikwik-loan-settlement": "mobikwik loan settlement",
  "mahindra-finance-loan-settlement": "mahindra finance loan settlement",
  "loan-settlement-noc": "loan settlement noc",
  "loan-settlement-new-update": "loan settlement new update",
  "loan-settlement-notice": "loan settlement notice",
  "loan-settlement-negotiations": "loan settlement negotiations",
  "education-loan-npa-settlement": "education loan npa settlement",
  "loan-not-repayment": "loan not repayment",
  "loan-number-payment": "loan number payment",
  "loan-repayment-nahi-kiya-to": "loan repayment nahi kiya to",
  "loan-repayment-nahi-karne-se-kya-hoga": "loan repayment nahi karne se kya hoga",
  "debt-settlement-negotiation": "debt settlement negotiation",
  "npa-loan-settlement": "npa loan settlement",
  "navi-loan-settlement-process": "navi loan settlement process",
  "nbfc-loan-settlement-kaise-kare": "nbfc loan settlement kaise kare",
  "noc-after-loan-settlement": "noc after loan settlement",
  "nbfc-loan-settlement": "nbfc loan settlement",
  "npa-loan-settlement-in-telugu": "npa loan settlement in telugu",
  "navi-loan-settlement-letter": "navi loan settlement letter",
  "npa-loan-settlement-in-tamil": "npa loan settlement in tamil",
  "nbfc-personal-loan-settlement-kaise-kare": "nbfc personal loan settlement kaise kare",
  "nira-loan-settlement": "nira loan settlement",
  "loan-settlement-offer": "loan settlement offer",
  "loan-settlement-option": "loan settlement option",
  "loan-settlement-online": "loan settlement online",
  "loan-settlement-office": "loan settlement office",
  "loan-settlement-odia": "loan settlement odia",
  "mobikwik-loan-settlement-offer": "mobikwik loan settlement offer",
  "loan-overdue-settlement": "loan overdue settlement",
  "mpokket-loan-overdue-settlement": "mpokket loan overdue settlement",
  "online-loan-settlement-kaise-kare": "online loan settlement kaise kare",
  "online-app-loan-settlement": "online app loan settlement",
  "overdraft-loan-settlement": "overdraft loan settlement",
  "one-time-loan-settlement-scheme": "one time loan settlement scheme",
  "olyv-loan-settlement": "olyv loan settlement",
  "online-personal-loan-settlement": "online personal loan settlement",
  "retirement-and-settlement-of-loan": "retirement and settlement of loan",
  "settlement-of-loan": "settlement of loan",
  "settlement-of-home-loan": "settlement of home loan",
  "loan-settlement-process-telugu": "loan settlement process telugu",
  "loan-settlement-process-hindi": "loan settlement process hindi",
  "loan-settlement-problem": "loan settlement problem",
  "loan-settlement-percentage": "loan settlement percentage",
  "loan-settlement-paper-kaise-hota-hai": "loan settlement paper kaise hota hai",
  "loan-settlement-process-tamil": "loan settlement process tamil",
  "mortgage-loan-settlement-process": "mortgage loan settlement process",
  "personal-loan-settlement-kaise-kare": "personal loan settlement kaise kare",
  "personal-loan-settlement": "personal loan settlement",
  "paytm-postpaid-loan-settlement-kaise-kare": "paytm postpaid loan settlement kaise kare",
  "personal-loan-settlement-telugu": "personal loan settlement telugu",
  "poonawalla-fincorp-personal-loan-settlement": "poonawalla fincorp personal loan settlement",
  "payrupik-loan-settlement-kaise-kare": "payrupik loan settlement kaise kare",
  "paytm-loan-settlement-kaise-kare": "paytm loan settlement kaise kare",
  "personal-loan-settlement-tamil": "personal loan settlement tamil",
  "personal-loan-settlement-process": "personal loan settlement process",
  "poonawalla-fincorp-personal-loan-settlement-letter": "poonawalla fincorp personal loan settlement letter",
  "loan-settlement-kab-hota-hai": "loan settlement kab hota hai",
  "loan-me-settlement-kaise-kare": "loan me settlement kaise kare",
  "settlement-of-unsecured-loan": "settlement of unsecured loan",
  "loan-settlement-request-letter": "loan settlement request letter",
  "loan-settlement-remove-kaise-kare": "loan settlement remove kaise kare",
  "loan-settlement-rules": "loan settlement rules",
  "loan-settlement-review": "loan settlement review",
  "bank-loan-settlement-rules": "bank loan settlement rules",
  "ring-loan-settlement": "ring loan settlement",
  "loan-repayment-rules": "loan repayment rules",
  "rupeeredee-loan-settlement": "rupeeredee loan settlement",
  "ram-fincorp-loan-settlement-kaise-kare": "ram fincorp loan settlement kaise kare",
  "ring-app-loan-settlement": "ring app loan settlement",
  "ram-fincorp-loan-settlement": "ram fincorp loan settlement",
  "rupeeredee-loan-settlement-offer": "rupeeredee loan settlement offer",
  "rbi-guidelines-for-loan-settlement": "rbi guidelines for loan settlement",
  "reliance-arc-education-loan-settlement": "reliance arc education loan settlement",
  "rbi-loan-settlement-scheme": "rbi loan settlement scheme",
  "rbi-new-guidelines-for-loan-settlement": "rbi new guidelines for loan settlement",
  "loan-settlement-se-cibil-score-kaise-badhaye": "loan settlement se cibil score kaise badhaye",
  "loan-settlement-se-kya-hota-hai": "loan settlement se kya hota hai",
  "loan-settlement-sahi-hai-ya-galat": "loan settlement sahi hai ya galat",
  "loan-settlement-system": "loan settlement system",
  "loan-settlement-services": "loan settlement services",
  "loan-settlement-side-effects": "loan settlement side effects",
  "loan-settlement-sbi": "loan settlement sbi",
  "loan-repayment-strategies": "loan repayment strategies",
  "loan-repayment-schedule": "loan repayment schedule",
  "secured-loan-settlement": "secured loan settlement",
  "shriram-finance-loan-settlement": "shriram finance loan settlement",
  "stashfin-loan-settlement-kaise-kare": "stashfin loan settlement kaise kare",
  "sbi-loan-settlement-process": "sbi loan settlement process",
  "sbi-personal-loan-settlement": "sbi personal loan settlement",
  "stashfin-loan-settlement": "stashfin loan settlement",
  "shriram-finance-bike-loan-settlement": "shriram finance bike loan settlement",
  "slice-loan-settlement": "slice loan settlement",
  "sbi-loan-settlement": "sbi loan settlement",
  "sbi-credit-card-loan-settlement": "sbi credit card loan settlement",
  "loan-settlement-tamil": "loan settlement tamil",
  "loan-repayment-tips": "loan repayment tips",
  "loan-repayment-tricks": "loan repayment tricks",
  "loan-payment-through-credit-card": "loan payment through credit card",
  "loan-repayment-through-credit-card": "loan repayment through credit card",
  "loan-repayment-through-yono-sbi": "loan repayment through yono sbi",
  "two-wheeler-loan-settlement": "two wheeler loan settlement",
  "tata-capital-loan-settlement": "tata-capital-loan-settlement",
  "tvs-credit-loan-settlement": "tvs-credit-loan-settlement",
  "true-balance-loan-settlement": "true-balance-loan-settlement",
  "tractor-loan-settlement": "tractor-loan-settlement",
  "tradofina-loan-settlement": "tradofina-loan-settlement",
  "third-party-loan-settlement": "third-party-loan-settlement",
  "tvs-credit-bike-loan-settlement": "tvs-credit-bike-loan-settlement",
  "tata-capital-two-wheeler-loan-settlement": "tata-capital-two-wheeler-loan-settlement",
  "types-of-loan-settlement": "types-of-loan-settlement",
  "unsecured-loan-settlement-decent-advice": "unsecured loan settlement decent advice",
  "loan-repayment-using-credit-card": "loan-repayment-using-credit-card",
  "loan-upi-payment": "loan-upi-payment",
  "unsecured-loan-settlement": "unsecured loan settlement",
  "unsecured-loan-settlement-process": "unsecured loan settlement process",
  "uni-loan-settlement": "uni loan settlement",
  "union-bank-loan-settlement": "union bank loan settlement",
  "ujjivan-small-finance-bank-loan-settlement": "ujjivan small finance bank loan settlement",
  "unsecured-business-loan-settlement": "unsecured business loan settlement",
  "loan-settlement-approval": "loan settlement approval",
  "loan-settlement-video": "loan settlement video",
  "loan-settlement-vakil": "loan settlement vakil",
  "loan-repayment-vs-investment": "loan-repayment-vs-investment",
  "vehicle-loan-settlement": "vehicle loan settlement",
  "loan-foreclosure-and-settlement": "loan-foreclosure-and-settlement",
  "loan-payment-voucher-get-upto-100-cashback": "loan payment voucher get upto 100 cashback",
  "debt-settlement-vs-bankruptcies": "debt-settlement-vs-bankruptcies",
  "loan-repayment-vs-investment-warikoo": "loan-repayment-vs-investment-warikoo",
  "loan-settlement-ka-video": "loan settlement ka video",
  "vehicle-loan-settlement-kaise-kare": "vehicle loan settlement kaise kare",
  "vehicle-loan-settlement-tamil": "vehicle loan settlement tamil",
  "viva-money-loan-settlement": "viva-money-loan-settlement",
  "money-view-loan-ka-settlement-kaise-kare": "money view loan ka settlement kaise kare",
  "money-view-loan-one-time-settlement": "money view loan one time settlement",
  "money-view-loan-one-time-settlement-telugu": "money view loan one time settlement telugu",
  "loan-settlement-website": "loan settlement website",
  "how-loan-settlement-works": "how loan settlement works",
  "loan-payment-with-credit-card": "loan payment with credit card",
  "loan-repayment-whatsapp-message": "loan repayment whatsapp message",
  "werize-loan-settlement": "werize loan settlement",
  "loan-repayment-with-amazon-pay-later": "loan repayment with amazon pay later",
  "loan-repayment-warikoo": "loan repayment warikoo",
  "loan-repayment-with-amazon-pay-balance": "loan-repayment-with-amazon-pay-balance",
  "loan-settlement-ankur-warikoo": "loan settlement ankur_warikoo",
  "write-off-loan-settlement": "write off loan settlement",
  "what-happens-after-loan-settlement": "what happens after loan settlement",
  "write-off-loan-settlement-tamil": "write off loan settlement tamil",
  "what-is-loan-settlement-in-hindi": "what is loan settlement in hindi",
  "what-is-the-process-of-loan-settlement": "what is the process of loan settlement",
  "what-is-loan-settlement-in-telugu": "what is loan settlement in telugu",
  "what-is-bank-loan-settlement": "what is bank loan settlement",
  "loan-repayment-yono-sbi": "loan repayment yono sbi",
  "yono-se-loan-repayment-kaise-kare": "yono se loan repayment kaise kare",
  "loan-settlement-kare-ya-nahi": "loan settlement kare ya nahi",
  "zype-loan-settlement": "zype loan settlement",
  "mobikwik-zip-loan-settlement-kaise-kare": "mobikwik zip loan settlement kaise kare",
  "loan-settlement-kaise-hataye": "loan settlement kaise hataye",
  "nbfc-loan-settlement-process": "nbfc loan settlement process",
  "loan-settlement-13-december": "loan settlement 13 december",
  "loan-112-repayment-nahi-kiya-to": "loan 112 repayment nahi kiya to",
  "loan-112-repayment": "loan 112 repayment",
  "13-december-lok-adalat-loan-settlement": "13 december lok adalat loan settlement",
  "10-lakh-loan-settlement": "10 lakh loan settlement",
  "13-september-lok-adalat-loan-settlement": "13 september lok adalat loan settlement",
  "13-december-loan-settlement": "13 december loan settlement",
  "13-december-lok-adalat-loan-settlement-kaise-kare": "13 december lok adalat loan settlement kaise kare",
  "settlement-of-loan-account-of-the-retiring-partner-class-12": "settlement of loan account of the retiring partner class 12",
  "1-time-settlement-bank-loan": "1 time settlement bank loan",
  "bank-loan-one-time-settlement": "bank-loan-one-time-settlement",
  "loan-one-time-settlement": "loan-one-time-settlement"
};

for (const [key, value] of Object.entries(serviceMap)) {
  const expectedKey = getSlug(value);
  if (key !== expectedKey) {
    console.log(`Mismatch: key="${key}", expected="${expectedKey}", value="${value}"`);
  }
}
