
import Link from "next/link";
import Script from "next/script";
import Image from "next/image";
import GenericStatesGrid from "@/components/GenericStatesGrid";
import TableOfContents from "@/components/TableOfContents";
import Breadcrumbs from "@/components/Breadcrumbs";
import { FaStar, FaQuoteLeft, FaCheckCircle, FaBalanceScale, FaUserShield, FaHandshake, FaCar, FaMotorcycle, FaGavel, FaMoneyBillWave, FaShieldAlt, FaStarOfLife, FaInfoCircle, FaRegFileAlt, FaGlobe, FaCreditCard } from "react-icons/fa";

// FAQ data for rendering and Schema - Initial seed for expansion
const faqs = [
    {
        question: "What is a Special Lok Adalat for traffic challans?",
        answer: "A Special Lok Adalat for traffic challans is a dedicated forum organized by the Legal Services Authority to settle a large volume of pending traffic violation cases and court challans through conciliation. It allows citizens to dispose of their challans by paying a reduced fine or getting them waived entirely in specific cases, providing a quick exit from legal proceedings."
    },
    {
        question: "Can I settle all types of challans in the Lok Adalat?",
        answer: "Most traffic challans, including speeding, red-light jumping, wrong-side driving, and parking violations, can be settled. However, serious offences like fatal accidents or certain drunk-driving cases where criminal proceedings are advanced may not be eligible for simple disposal in a Lok Adalat."
    },
    {
        question: "How do I check my challan status for the 2025 Lok Adalat?",
        answer: "You can check your challan status on the official Parivahan website, the Virtual Court portal, or specific state traffic police websites (like Delhi Traffic Police or Bangalore Traffic Police). During Lok Adalat periods, these portals often provide a direct link to 'Settle in Lok Adalat'."
    },
    {
        question: "Is it mandatory to attend the Lok Adalat physically?",
        answer: "No, in 2025, many states offer E-Lok Adalats where you can settle your challans via video conferencing or direct payment through the Virtual Court portal. Physical attendance is only required if your vehicle is impounded or if the judge requests a physical verification of documents."
    },
    {
        question: "What is the maximum discount I can get on a traffic challan?",
        answer: "The discount varies by state and violation. Typically, waivers range from 50% to 75%. In some special OTS (One-Time Settlement) schemes, older challans (more than 2 years old) have seen waivers up to 80% on the base fine amount."
    },
    {
        question: "Will my 'Blacklisted' status on Vahan be removed after payment?",
        answer: "Yes, once you pay the compounding fee in the Lok Adalat and the award is issued, the traffic police tech-wing is notified. It usually takes 24-72 hours for the 'Blacklisted' or 'Pending' status to be cleared from the Vahan database."
    },
    {
        question: "Can I settle a challan that has already reached the court?",
        answer: "Yes, Lok Adalats are primarily designed for cases that are 'Pending' in court. Even if you have received a court summons, you can bring that notice to the Lok Adalat for a quicker and cheaper settlement."
    },
    {
        question: "What documents do I need for the Lok Adalat session?",
        answer: "You should have your vehicle's Registration Certificate (RC), valid Insurance policy, updated PUC certificate, and your Driving License. In many cases, having a copy of the original challan notice is also helpful."
    },
    {
        question: "What happens if I miss the Lok Adalat date?",
        answer: "If you miss the date, your challan remains pending in the system. You will lose the opportunity for the special discount offered during that session and may have to pay the full fine in a regular court later."
    },
    {
        question: "Can AMA Legal Solutions represent me in the Lok Adalat?",
        answer: "Yes, we provide legal representation for individuals and corporations. This is particularly useful for NRI clients, fleet owners, or those who cannot attend court due to professional commitments. We handle the documentation and negotiation on your behalf."
    },
    {
        question: "Are camera/ITMS challans eligible for Lok Adalat?",
        answer: "Absolutely. ITMS (Intelligent Traffic Management System) challans generated by automatic cameras for over-speeding or red-light jumping are the most common cases settled in Lok Adalats."
    },
    {
        question: "Can I challenge a wrong challan in the Lok Adalat?",
        answer: "Yes, you can present evidence (like a GPS log or proof that your vehicle was elsewhere) to the judicial panel. If they are satisfied, the challan can be dismissed entirely with zero penalty."
    },
    {
        question: "Does paying in Lok Adalat count as a 'Criminal Conviction'?",
        answer: "No. Paying a compounding fee in Lok Adalat is considered a civil settlement of a petty offense. It does not go on your criminal record and does not affect your passport or job background checks."
    },
    {
        question: "Is there an appeal against a Lok Adalat award?",
        answer: "No. Under Section 21 of the Legal Services Authorities Act, a Lok Adalat award is final and no appeal lies to any court. This ensures absolute finality for both you and the police."
    },
    {
        question: "Can I settle multiple challans in one go?",
        answer: "Yes, you can list all your pending challans for a particular vehicle and settle them in a single conciliation session."
    },
    {
        question: "What is the 'Virtual Court' portal?",
        answer: "The Virtual Court (vcourts.gov.in) is a project by the E-Committee of the Supreme Court of India. It allows for the online adjudication of challans across several states including Delhi, Haryana, and Maharashtra."
    },
    {
        question: "How do I know when the next Lok Adalat is scheduled?",
        answer: "The NALSA (National Legal Services Authority) publishes an annual calendar. Usually, there are 4 National Lok Adalats a year. Local Special Lok Adalats for traffic are also announced via newspapers and traffic police social media handles."
    },
    {
        question: "I lost my physical challan copy. Can I still settle it?",
        answer: "Yes, as long as you have the vehicle number and chassis number, your records can be fetched digitally on the spot in the Lok Adalat."
    },
    {
        question: "Are 'Dangerous Driving' challans (Section 184) settleable?",
        answer: "Yes, depending on the severity and state regulations. While they are serious, judges often allow compounding if no accident or injury was involved."
    },
    {
        question: "Can I settle challans from other states?",
        answer: "Typically, you must settle the challan in the jurisdiction (state) where the violation occurred. However, centralized portals like Parivahan are making inter-state settlement easier."
    },
    {
        question: "What is the role of a mediator in Lok Adalat?",
        answer: "A mediator helps bridge the gap between your requested waiver and the police's demand. They ensure a fair settlement that is acceptable to both parties."
    },
    {
        question: "Are commercial vehicle challans treated differently?",
        answer: "The base fines for commercial vehicles (trucks, taxis) are higher, but the percentage of waiver in Lok Adalat remains largely similar to private vehicles."
    },
    {
        question: "What if my vehicle is already blacklisted on the portal?",
        answer: "You must settle ALL pending challans for that vehicle in the Lok Adalat. Once the award is uploaded, the 'Blacklist' is removed automatically by the system."
    },
    {
        question: "Can I pay the Lok Adalat fine in installments?",
        answer: "No. The settlement amount agreed upon in a Lok Adalat must be paid in full, usually on the same day or within a specified short window."
    },
    {
        question: "Is the Lok Adalat process time-consuming?",
        answer: "Not compared to regular trials. A typical session takes 15-30 minutes if you have your documents ready and slots booked."
    },
    {
        question: "Can I get a refund if I discover I paid a wrong challan in Lok Adalat?",
        answer: "No. Once a Lok Adalat award is passed by consent, it cannot be reopened or refunded."
    },
    {
        question: "Are 'Seat Belt' and 'Helmet' violations eligible for waivers?",
        answer: "Yes, they are among the most frequently discounted offenses, often receiving a flat 50% waiver."
    },
    {
        question: "Does Lok Adalat handle 'Overloading' challans?",
        answer: "Yes, though overloading fines are very heavy. Lok Adalats provide a crucial platform for logistics companies to settle these."
    },
    {
        question: "I sold my car but challans are still coming to me. What to do?",
        answer: "You should bring the 'Sale Letter' and 'Form 29/30' to the Lok Adalat. The Judge can help transfer the liability or dismiss the challans from your record."
    },
    {
        question: "Is there a fee to register for Lok Adalat?",
        answer: "No, there is no court fee or registration charge to bring your case to a Lok Adalat. You only pay the agreed fine."
    },
    {
        question: "What is Section 200 of the MV Act?",
        answer: "It is the section that allows the 'Compounding' of offenses. It gives the legal power to authorities to settle a case by accepting a fine instead of prosecution."
    },
    {
        question: "Can I settle a 'No Parking' challan if my car was towed?",
        answer: "Yes, you can settle the traffic fine in Lok Adalat, but you might still have to pay the separate 'Towing Charges' to the agency that impounded the vehicle."
    },
    {
        question: "What if the camera caught a glimpse of another vehicle's number plate and fined me?",
        answer: "This is a 'Technical Error'. You can present the photo (downloadable from the portal) to the Lok Adalat panel to prove the mistake."
    },
    {
        question: "Is there a limit on how many challans one person can settle?",
        answer: "No. Whether you have 1 challan or 100, you can bring all of them for settlement."
    },
    {
        question: "Can I attend Lok Adalat in a different city within the same state?",
        answer: "Yes, if the state has a 'One-State-One-Challan' system implemented, you can often settle it in any mega Lok Adalat within that state."
    },
    {
        question: "Are 'No Entry' violations discounted?",
        answer: "Yes, these are generally compoundable and eligible for significant waivers."
    },
    {
        question: "What is an 'Executive Magistrate' in the context of traffic?",
        answer: "In some zones, an Executive Magistrate exercises the powers of a court to settle traffic offenses on the spot or during special drives."
    },
    {
        question: "How long does a Lok Adalat session last?",
        answer: "National Lok Adalats usually run from 10:00 AM to 5:00 PM on a Saturday."
    },
    {
        question: "What if the police officer doesn't agree to the discount?",
        answer: "In a Lok Adalat, the judge has the final say in the conciliation. If a reasonable settlement is reached, the police usually concur."
    },
    {
        question: "Can I get a physical receipt for the payment?",
        answer: "Yes, either a physical receipt is issued or a digital 'Payment Success' award is generated which is legally valid."
    },
    {
        question: "Are old pending challans (5+ years) still settleable?",
        answer: "Yes, and these often get the highest waivers as the state is keen to clear ancient records from their servers."
    },
    {
        question: "What is the DSLSA portal for Delhi residents?",
        answer: "It is notice.dslsa.org, where Delhi citizens can book slots for Lok Adalats."
    },
    {
        question: "Can I pay using UPI in Lok Adalat?",
        answer: "Yes, most E-Lok Adalats and physical court counters now accept UPI, Credit Cards, and Net Banking."
    },
    {
        question: "Do I need a lawyer for a single ₹500 challan?",
        answer: "For a single petty challan, you can handle it yourself. A lawyer is recommended for bulk cases, impounded vehicles, or serious offenses."
    },
    {
        question: "What is a 'Draft Award'?",
        answer: "It is the proposed settlement amount discussed during conciliation. Once you sign it, it becomes the 'Final Award'."
    },
    {
        question: "Are 'Fancy Number Plate' challans discounted?",
        answer: "Yes, though the police might ask for photo proof that you have now installed a standard HSRP plate."
    },
    {
        question: "Is Lok Adalat only for private cars?",
        answer: "No, it covers motorcycles, cars, autos, trucks, and even buses."
    },
    {
        question: "Can I settle a challan where a summons was already served at my home?",
        answer: "Yes, you can bring that summons to the Lok Adalat to settle the matter and avoid further court visits."
    },
    {
        question: "What is the 'Compounding Fee'?",
        answer: "It is the technical term for the fine you pay to settle the offense without a trial."
    },
    {
        question: "Are 'Pollution (PUC)' challans very expensive?",
        answer: "Yes, the standard fine is ₹10,000. Lok Adalats provide the only real way to get this reduced legally."
    },
    {
        question: "Can I settle a challan for 'Driving without a License'?",
        answer: "Yes, if you now possess a valid license or can explain the lapse, judges often allow compounding with a fine."
    },
    {
        question: "How do I check if my payment reached the police?",
        answer: "You should check the status on the Parivahan portal after 48 hours. It should change from 'Pending' to 'Disposed' or 'Paid'."
    },
    {
        question: "What is NALSA?",
        answer: "The National Legal Services Authority, which is the apex body chaired by the CJI to provide free legal services and organize Lok Adalats."
    },
    {
        question: "Can I settle a challan that involves a minor driving?",
        answer: "These are treated very seriously. While technically settleable, the fines are much higher and the owner is held strictly liable."
    },
    {
        question: "What is the best time to reach the Lok Adalat?",
        answer: "If you have a physical slot, reaching early (9:30 AM) helps you beat the crowd and get your case processed faster."
    },
    {
        question: "Are Lok Adalats held on working days?",
        answer: "National Lok Adalats are almost always held on Saturdays to allow working professionals to attend."
    }
];

// Testimonials data
const testimonials = [
  {
    name: "Vikram Singh",
    location: "New Delhi",
    rating: 5,
    text: "I had 15 pending challans amounting to ₹12,000. Through AMA's guidance in the Lok Adalat, I managed to clear everything for just ₹1,500. The process was smooth and saved me from multiple court visits."
  },
  {
    name: "Ananya Rao",
    location: "Hyderabad",
    rating: 5,
    text: "Highly recommend AMA Legal Solutions for challan disposal. They explained the difference between virtual courts and Lok Adalats perfectly. Settled my overhead camera challans in one go."
  },
  {
    name: "Sarthak Goel",
    location: "Pune",
    rating: 5,
    text: "Professional and efficient. My vehicle was impounded due to multiple pending challans. AMA helped me get the case to the Special Lok Adalat and secured a release order immediately."
  }
];

// Breadcrumb Schema
const breadcrumbSchema = {
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  "itemListElement": [
    {
      "@type": "ListItem",
      "position": 1,
      "name": "Home",
      "item": "https://www.amalegalsolutions.com"
    },
    {
      "@type": "ListItem",
      "position": 2,
      "name": "Services",
      "item": "https://www.amalegalsolutions.com/services"
    },
    {
      "@type": "ListItem",
      "position": 3,
      "name": "Traffic Challan Settlement",
      "item": "https://www.amalegalsolutions.com/special-lok-adalat-for-challan"
    }
  ]
};

export const metadata = {
  title: "Special Lok Adalat for Traffic Challan 2025 | Clear Online Challans",
  description: "Want to clear your traffic challans with massive discounts? Learn about the 2025 Special Lok Adalat schedule, online disposal procedure, and how to settle pending court challans legally.",
  keywords: [
    "special lok adalat for challan",
    "traffic challan settlement 2025",
    "national lok adalat challan delhi",
    "dispose traffic challan online",
    "challan discount lok adalat",
    "virtual court challan settlement",
    "check pending challan status",
    "how to attend lok adalat for challan",
    "motor vehicle act lok adalat",
    "traffic police challan waiver"
  ],
  alternates: {
    canonical: 'https://www.amalegalsolutions.com/special-lok-adalat-for-challan',
  }
};

export default function ChallanLokAdalatPage() {
  const tocSections = [
    { id: "introduction", title: "Introduction" },
    { id: "what-is-challan-adalat", title: "What is Traffic Lok Adalat?" },
    { id: "types-of-challans", title: "Types of Eligible Challans" },
    { id: "online-procedure", title: "Online Disposal Guide" },
    { id: "discounts-and-waivers", title: "Discount & Waiver Slabs" },
    { id: "virtual-vs-physical", title: "Virtual vs Physical" },
    { id: "legal-framework", title: "Legal Framework (MV Act)" },
    { id: "preparation", title: "How to Prepare?" },
    { id: "reviews", title: "Success Stories" },
    { id: "faqs", title: "55+ FAQs" },
  ];

  const breadcrumbItems = [
    { label: "Services", href: "/services" },
    { label: "Special Lok Adalat", href: "#" },
    { label: "Traffic Challan", href: "/special-lok-adalat-for-challan" },
  ];

  return (
    <>
      <Script
        id="breadcrumb-schema"
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }}
      />
      <Script
        id="article-schema"
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify({
          "@context": "https://schema.org",
          "@type": "Article",
          "headline": "Special Lok Adalat for Traffic Challan 2025: Clear Online Challans",
          "description": "Exhaustive guide to settling traffic challans in Lok Adalat 2025. Learn about waivers, online disposal, and legal rights.",
          "author": { "@type": "Organization", "name": "AMA Legal Solutions" },
          "publisher": { "@type": "Organization", "name": "AMA Legal Solutions", "logo": { "@type": "ImageObject", "url": "https://www.amalegalsolutions.com/logo.png" } },
          "mainEntityOfPage": { "@type": "WebPage", "@id": "https://www.amalegalsolutions.com/special-lok-adalat-for-challan" }
        }) }}
      />
      <Script
        id="faq-schema"
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify({
          "@context": "https://schema.org",
          "@type": "FAQPage",
          "mainEntity": faqs.map(f => ({
            "@type": "Question",
            "name": f.question,
            "acceptedAnswer": { "@type": "Answer", "text": f.answer }
          }))
        }) }}
      />
      <Script
        id="review-schema"
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify({
          "@context": "https://schema.org",
          "@type": "Product",
          "name": "Traffic Challan Settlement Service",
          "aggregateRating": {
            "@type": "AggregateRating",
            "ratingValue": "4.9",
            "reviewCount": "1250"
          },
          "review": testimonials.map(t => ({
            "@type": "Review",
            "reviewRating": { "@type": "Rating", "ratingValue": t.rating },
            "author": { "@type": "Person", "name": t.name },
            "reviewBody": t.text
          }))
        }) }}
      />

      <div className="bg-gray-50 min-h-screen font-sans text-gray-800">
        {/* Premium Hero Section */}
        <div className="relative bg-[#0F172A] text-white overflow-hidden">
          <div className="absolute inset-0 bg-black opacity-65 z-10"></div>
          <div 
            className="absolute inset-0 bg-[url('https://images.unsplash.com/photo-1590674899736-22a8439df686?q=80&w=2070')] bg-cover bg-center z-0 scale-105 opacity-40" 
          ></div>
          <div className="relative z-20 container mx-auto px-4 py-16 md:py-32 text-center">
            <h1 className="text-3xl md:text-6xl font-black mb-6 leading-tight tracking-tighter">
              Clear Your Traffic <span className="text-[#D2A02A]">Challans</span> Permanently
            </h1>
            <p className="text-base md:text-2xl mb-10 max-w-4xl mx-auto text-gray-200 font-medium leading-relaxed">
              Join the 2025 Special Lok Adalat movement. Dispose of pending court notices, camera challans, and impounded vehicle cases with legal finality and maximum waivers.
            </p>
            <div className="flex flex-col md:flex-row gap-6 justify-center items-center">
                <Link href="/contact">
                <button className="bg-[#D2A02A] hover:bg-[#b88a22] text-white font-black py-4 px-10 md:py-5 md:px-12 rounded-full transition-all transform hover:scale-105 shadow-[0_15px_30px_-10px_rgba(210,160,42,0.6)] text-base md:text-xl flex items-center gap-3">
                    <FaGavel /> Settle Your Challans Now
                </button>
                </Link>
                <div className="flex items-center gap-4 bg-white/10 backdrop-blur-md p-4 rounded-2xl border border-white/20">
                    <div className="flex -space-x-3">
                        {[1,2,3,4].map(i => <div key={i} className="w-10 h-10 rounded-full border-2 border-[#D2A02A] bg-gray-600 flex items-center justify-center text-[10px] font-bold">U{i}</div>)}
                    </div>
                    <p className="text-gray-300 text-sm font-semibold">10,000+ Challans Settled</p>
                </div>
            </div>
          </div>
        </div>

        <div className="container mx-auto px-4 max-w-[1600px] py-12">
          <Breadcrumbs items={breadcrumbItems} />
          
          <div className="grid grid-cols-1 lg:grid-cols-[240px_1fr_300px] gap-12 items-start mt-8">
            {/* Sidebar TOC */}
            <div className="hidden lg:block sticky top-28">
              <TableOfContents sections={tocSections} orientation="vertical" />
              <div className="mt-12 p-8 bg-gradient-to-b from-[#1E293B] to-[#0F172A] rounded-3xl border border-white/10 shadow-2xl">
                  <h4 className="font-bold text-[#D2A02A] mb-4 uppercase tracking-widest text-xs">Legal Assistance</h4>
                  <p className="text-xs text-gray-400 leading-relaxed mb-6 font-medium">Don't let complex traffic notices ruin your peace. Get expert representation for bulk challan settlement.</p>
                  <Link href="/contact" className="inline-flex items-center gap-2 text-sm font-bold text-white hover:text-[#D2A02A] transition-colors">
                    Talk to a Lawyer <FaHandshake />
                  </Link>
              </div>
            </div>

            {/* Main Content */}
            <div className="min-w-0">
              <div className="lg:hidden mb-10 sticky top-20 z-10">
                <TableOfContents sections={tocSections} />
              </div>

              <div className="bg-white p-6 md:p-16 rounded-[2.5rem] shadow-2xl border border-gray-100 space-y-12 md:space-y-24 relative overflow-hidden">
                
                {/* Introduction */}
                <section id="introduction" className="scroll-mt-32">
                  <div className="flex items-center gap-4 mb-10">
                      <div className="h-12 w-2 bg-[#D2A02A] rounded-full"></div>
                      <h2 className="text-2xl md:text-5xl font-black text-gray-900 tracking-tight leading-tight italic">Roadmap to Traffic Justice</h2>
                  </div>
                  <div className="prose prose-2xl max-w-none text-gray-700 leading-relaxed space-y-10">
                    <p className="text-lg md:text-2xl font-light text-gray-500 italic border-l-8 border-gray-50 pl-8 py-4 mb-10 bg-gray-50/50 rounded-r-3xl">
                        "A pending challan is not just a fine; it is an unresolved legal obligation that can block your vehicle sale, fitness certificate, and insurance renewal. The Lok Adalat is your constitutional right to a clean slate."
                    </p>
                    <p>
                        In the fast-paced urban landscape of modern India, traffic violations have become an almost inevitable part of city driving. With the deployment of intelligent traffic management systems (ITMS), overhead speed cameras, and AI-driven signal monitors, challans are being generated in unprecedented volumes. Thousands of vehicle owners across major metros like Delhi, Mumbai, Bengaluru, and Pune find themselves burdened with a backlog of notices that they often discover months after the alleged violation.
                    </p>
                    <p>
                        The weight of these pending challans goes beyond the immediate financial penalty. Under the latest amendments to the Motor Vehicles Act, unresolved challans can lead to the 'Blacklisting' of your vehicle on the Vahan portal. This prevents you from renewing your insurance, transferring ownership, obtaining a Pollution Under Control (PUC) certificate, or even renewing your driving license.
                    </p>
                    <div className="p-10 bg-blue-50/50 rounded-[2.5rem] border border-blue-100/50 flex flex-col md:flex-row gap-8 items-center">
                        <FaCar className="text-7xl text-blue-600 opacity-20" />
                        <p className="text-lg text-blue-900 font-medium italic">
                            The Special Lok Adalat for traffic challans bridges the gap between the administration's need for compliance and the citizen's need for a fair, affordable, and quick resolution.
                        </p>
                    </div>
                  </div>
                </section>

                {/* What is it? */}
                <section id="what-is-challan-adalat" className="scroll-mt-32">
                    <h2 className="text-xl md:text-4xl font-bold text-gray-900 mb-10 flex items-center gap-4 underline decoration-[#D2A02A] decoration-8 underline-offset-8">
                        The Anatomy of a Traffic Lok Adalat
                    </h2>
                    <div className="grid md:grid-cols-2 gap-10">
                        <div className="p-10 bg-gray-900 text-white rounded-[2rem] shadow-xl">
                            <h4 className="text-2xl font-bold mb-6 text-[#D2A02A]">What is it?</h4>
                            <p className="text-gray-300 leading-relaxed text-lg">
                                Established under the Legal Services Authorities Act, 1987, a Traffic Lok Adalat is an Alternative Dispute Resolution (ADR) forum where pending traffic notices and court-sent challans are resolved through mutual consent. It is chaired by a sitting or retired judicial officer along with a panel of social workers and legal experts.
                            </p>
                        </div>
                        <div className="p-10 bg-[#fff9e6] rounded-[2rem] border border-[#D2A02A]/20">
                            <h4 className="text-2xl font-bold mb-6 text-gray-900">The 2025 Objective</h4>
                            <p className="text-gray-700 leading-relaxed text-lg">
                                The 2025 vision for Traffic Lok Adalats is "Digital Disposal." The focus is on clearing the 50-million-plus pending challans across India using E-Lok Adalat platforms, reducing the burden on regular courts and providing instant relief to motorists.
                            </p>
                        </div>
                    </div>
                </section>

                {/* Types of Eligible Challans */}
                <section id="types-of-challans" className="scroll-mt-32">
                    <h2 className="text-xl md:text-4xl font-black text-gray-900 mb-10">Types of Eligible Challans</h2>
                    <p className="text-xl text-gray-600 mb-10 leading-relaxed">
                        While the Lok Adalat is inclusive, not every traffic notice follows the same disposal logic. Here is a breakdown of the most common categories we help our clients settle.
                    </p>
                    <div className="grid md:grid-cols-3 gap-6">
                        {[
                            { title: "ITMS & Camera Challans", desc: "Over-speeding, red-light jumping, and no-seatbelt caught by AI cameras.", icon: <FaCar className="text-blue-500" /> },
                            { title: "Court-Sent Challans", desc: "Violations where the physical notice has aged and transferred to judicial custody.", icon: <FaGavel className="text-[#D2A02A]" /> },
                            { title: "Compoundable Offences", desc: "Parking, wrong-way, and document violations (PUC, Insurance).", icon: <FaCheckCircle className="text-green-500" /> },
                        ].map((item, i) => (
                            <div key={i} className="p-8 bg-white border-2 border-gray-50 rounded-[2rem] shadow-lg hover:shadow-2xl transition-all">
                                <div className="text-4xl mb-6">{item.icon}</div>
                                <h4 className="text-xl font-bold mb-4">{item.title}</h4>
                                <p className="text-sm text-gray-500 leading-relaxed">{item.desc}</p>
                            </div>
                        ))}
                    </div>
                    <div className="mt-12 overflow-x-auto rounded-[2rem] border border-gray-100 shadow-xl">
                        <table className="w-full text-left">
                            <thead className="bg-[#1E293B] text-white">
                                <tr>
                                    <th className="p-6">Violation Type</th>
                                    <th className="p-6">Standard Fine (MV Act)</th>
                                    <th className="p-6">Lok Adalat Prospect</th>
                                </tr>
                            </thead>
                            <tbody className="divide-y divide-gray-100">
                                <tr><td className="p-6 font-bold">Over-speeding</td><td className="p-6">₹1,000 - ₹2,000</td><td className="p-6 text-green-600 font-bold">50% - 75% Waiver</td></tr>
                                <tr><td className="p-6 font-bold">No PUC</td><td className="p-6">₹10,000</td><td className="p-6 text-green-600 font-bold">High Waiver Opportunity</td></tr>
                                <tr><td className="p-6 font-bold">Drunk Driving</td><td className="p-6">₹10,000 + Jail</td><td className="p-6 text-red-600 font-bold">Strict / Low Waiver</td></tr>
                                <tr><td className="p-6 font-bold">Wrong Way</td><td className="p-6">₹5,000</td><td className="p-6 text-[#D2A02A] font-bold">Negotiable</td></tr>
                            </tbody>
                        </table>
                    </div>
                </section>

                {/* Online Procedure Guide */}
                <section id="online-procedure" className="scroll-mt-32">
                    <h2 className="text-xl md:text-4xl font-black text-gray-900 mb-10 underline decoration-[#D2A02A] decoration-8 underline-offset-8">Step-by-Step Online Disposal Guide</h2>
                    <div className="space-y-12">
                        {[
                            { step: "01", title: "Verify Your Jurisdictions", desc: "Identify if your challans are with the Traffic Police (Sent to Court) or Virtual Court. Different portals manage different statuses." },
                            { step: "02", title: "Download the Notice", desc: "Once the Lok Adalat schedule is announced, download the official settlement notice from the SLSA portal." },
                            { step: "03", title: "Conciliation Session", desc: "Log in to the E-Lok Adalat link. You will be connected to a mediator or judge to agree on the final compounding fee." },
                            { step: "04", title: "Digital Payment", desc: "Pay the agreed amount immediately via the GRAS or SBI portal link provided in the digital award." },
                        ].map((item, i) => (
                            <div key={i} className="flex gap-10 items-start">
                                <div className="text-6xl font-black text-gray-100">{item.step}</div>
                                <div>
                                    <h4 className="text-2xl font-bold mb-4 text-gray-900">{item.title}</h4>
                                    <p className="text-lg text-gray-600 leading-relaxed">{item.desc}</p>
                                </div>
                            </div>
                        ))}
                    </div>
                </section>

                {/* Legal Framework */}
                <section id="legal-framework" className="scroll-mt-32 bg-gray-900 p-10 md:p-20 rounded-[4rem] text-white">
                    <h2 className="text-xl md:text-4xl font-black mb-10 text-[#D2A02A]">Legal Framework (Motor Vehicles Act)</h2>
                    <div className="prose prose-invert prose-2xl max-w-none text-gray-300 leading-relaxed space-y-10">
                        <p>
                            Traffic Lok Adalats operate under the umbrella of the **Legal Services Authorities Act, 1987**, specifically Section 19. The decisions made here are called 'Awards' and have the same legal standing as a decree of a civil court.
                        </p>
                        <ul className="grid md:grid-cols-2 gap-8 list-none p-0">
                            <li className="flex gap-4 items-start"><FaBalanceScale className="text-[#D2A02A] mt-2 flex-shrink-0" /> <span>**Section 21**: Civil Court status for Awards. No appeal lies against a Lok Adalat Award.</span></li>
                            <li className="flex gap-4 items-start"><FaUserShield className="text-[#D2A02A] mt-2 flex-shrink-0" /> <span>**Article 39A**: Every citizen's right to free legal aid and equal justice.</span></li>
                            <li className="flex gap-4 items-start"><FaGavel className="text-[#D2A02A] mt-2 flex-shrink-0" /> <span>**MV Act Section 200**: The power of the state to 'Compound' (settle) offences.</span></li>
                            <li className="flex gap-4 items-start"><FaShieldAlt className="text-[#D2A02A] mt-2 flex-shrink-0" /> <span>**MV Act Section 194**: Overloading penalties and their settlement logic.</span></li>
                        </ul>
                    </div>
                </section>

                {/* State-Specific Guides */}
                <section id="state-specific-guides" className="scroll-mt-32">
                    <h2 className="text-xl md:text-4xl font-black text-gray-900 mb-10">State-Specific Lok Adalat Procedures</h2>
                    <div className="space-y-20">
                        {/* Delhi */}
                        <div className="p-10 bg-white rounded-[2rem] border border-gray-100 shadow-xl">
                            <h4 className="text-2xl font-bold text-gray-900 mb-6 flex items-center gap-4">
                                <span className="w-12 h-12 bg-blue-100 text-blue-600 rounded-full flex items-center justify-center font-black">DL</span>
                                Delhi Traffic Lok Adalat 2025
                            </h4>
                            <div className="prose prose-xl max-w-none text-gray-600 space-y-6">
                                <p>
                                    Delhi remains the benchmark for traffic challan disposal in India. The Delhi State Legal Services Authority (DSLSA) organizes mega Lok Adalats almost every quarter. In 2025, the focus is on "Integrated Disposal."
                                </p>
                                <ul className="list-none p-0 space-y-4">
                                    <li className="flex gap-4"><strong>Online Booking:</strong> You must log in to the DSLSA portal (notice.dslsa.org) exactly at 10:00 AM on the pre-announced date to book your slot.</li>
                                    <li><strong>Virtual Courts:</strong> Most Delhi challans are now processed via the Virtual Court (NI Act) portal. You can settle these 24/7, but the 'Discount' applies only during the Lok Adalat window.</li>
                                    <li><strong>Node Courts:</strong> For physical attendance, Delhi is divided into zones like Patiala House, Saket, Rohini, and Dwarka courts.</li>
                                </ul>
                            </div>
                        </div>

                        {/* Bangalore */}
                        <div className="p-10 bg-white rounded-[2rem] border border-gray-100 shadow-xl">
                            <h4 className="text-2xl font-bold text-gray-900 mb-6 flex items-center gap-4">
                                <span className="w-12 h-12 bg-green-100 text-green-600 rounded-full flex items-center justify-center font-black">KA</span>
                                Bengaluru (Karnataka) Enforcement
                            </h4>
                            <div className="prose prose-xl max-w-none text-gray-600 space-y-6">
                                <p>
                                    Karnataka has pioneered the 50% rebate scheme, which is often extended for several weeks. Unlike Delhi's one-day mega event, Bengaluru often provides a wider window for citizens to pay at traffic police stations or even at Bangalore One centers.
                                </p>
                                <p>
                                    <strong>The 'BTP' Portal:</strong> The Bengaluru Traffic Police portal is highly advanced. It allows you to view the citation image, specific location, and the 'Compounding' status in real-time. We help commercial fleet owners in Karnataka clear thousands of 'Contract Carriage' violations during these drives.
                                </p>
                            </div>
                        </div>

                        {/* Mumbai */}
                        <div className="p-10 bg-white rounded-[2rem] border border-gray-100 shadow-xl">
                            <h4 className="text-2xl font-bold text-gray-900 mb-6 flex items-center gap-4">
                                <span className="w-12 h-12 bg-red-100 text-red-600 rounded-full flex items-center justify-center font-black">MH</span>
                                Mumbai & Maharashtra E-Challans
                            </h4>
                            <div className="prose prose-xl max-w-none text-gray-600 space-y-6">
                                <p>
                                    The Mumbai traffic police use the 'MTP App' extensively. During Lok Adalats, the 'Mahatraffic' portal opens up specialized links for 'Pre-Litigation' settlements. This is specifically for challans that have not yet reached the court but are older than 90 days.
                                </p>
                                <p>
                                    <strong>The 'One-State-One-Challan' Logic:</strong> Maharashtra has integrated its highway and city traffic data. A violation on the Mumbai-Pune Expressway can be settled in a Lok Adalat held in Nagpur, provided it's under the same state jurisdiction.
                                </p>
                            </div>
                        </div>
                    </div>
                </section>

                {/* Legal Deep Dive */}
                <section id="legal-deep-dive" className="scroll-mt-32">
                    <h2 className="text-2xl md:text-5xl font-black text-gray-900 mb-12">Legal Deep Dive: The Motor Vehicles Act 2025</h2>
                    <div className="prose prose-2xl max-w-none text-gray-800 leading-relaxed space-y-12">
                        <p>
                            To navigate a Lok Adalat successfully, one must understand the statutes governing traffic violations. The 2019 Amendment to the Motor Vehicles Act (implemented fully by 2025) drastically increased the fines, making Lok Adalats even more critical.
                        </p>
                        
                        <div className="grid md:grid-cols-2 gap-10">
                            <div className="p-8 bg-gray-50 rounded-[2rem] border border-gray-200">
                                <h3 className="text-2xl font-bold text-gray-900 mb-6">Section 183: Over-speeding</h3>
                                <p className="text-lg text-gray-600">
                                    Distinguishes between LMV (Light Motor Vehicles) and MPV/HMV (Medium/Heavy). The fine for LMV is ₹1,000–₹2,000, while for heavy vehicles it starts at ₹2,000. Lok Adalats typically reduce this to a flat ₹500 or ₹400 for LMV first-time offenders.
                                </p>
                            </div>
                            <div className="p-8 bg-gray-50 rounded-[2rem] border border-gray-200">
                                <h3 className="text-2xl font-bold text-gray-900 mb-6">Section 184: Dangerous Driving</h3>
                                <p className="text-lg text-gray-600">
                                    Includes jumping red lights, usage of mobile phones, and wrong-way driving. This is a "Non-Compoundable" offence in some states, but Lok Adalats can often convert it to a compoundable one by viewing it as 'negligent' rather than 'dangerous' based on legal arguments.
                                </p>
                            </div>
                        </div>

                        <div className="p-12 bg-blue-900 text-white rounded-[3rem] shadow-2xl relative overflow-hidden">
                            <div className="absolute -right-20 -bottom-20 w-80 h-80 bg-blue-800/50 rounded-full blur-3xl"></div>
                            <h3 className="text-3xl font-black mb-8 text-[#D2A02A]">The Power of Section 200</h3>
                            <p className="text-xl mb-10 leading-relaxed font-medium">
                                This section is the "Magic Wand" of Traffic Lok Adalats. It allows the State Government to authorize any officer or authority to 'Compound' any offence before or after the institution of the prosecution. When you pay in Lok Adalat, you are essentially exercising your right under Section 200 to settle the matter without a criminal trial.
                            </p>
                            <div className="p-6 bg-white/10 backdrop-blur-md rounded-2xl border border-white/20 italic">
                                "Compounding an offence means the victim (State) agrees to drop charges in exchange for a specified fine. Once compounded, the accused is acquitted of the charges for all legal purposes."
                            </div>
                        </div>
                    </div>
                </section>

                {/* Discounts & Waiver Slabs */}
                <section id="discounts-and-waivers" className="scroll-mt-32">
                    <h2 className="text-2xl md:text-5xl font-black text-gray-900 mb-12">Discount & Waiver Slabs: The Math of Lok Adalat</h2>
                    <div className="prose prose-2xl max-w-none text-gray-700 leading-relaxed mb-12">
                        <p>
                            One of the most frequently asked questions during a traffic Lok Adalat drive is: "Exactly how much will I save?" Unlike standard court proceedings where the fine is rigid, Lok Adalats operate on the principle of 'Compounding'. This means the authority is willing to accept a smaller portion of the fine to settle the case permanently.
                        </p>
                        <p>
                            In 2024 and 2025, several state governments and High Courts introduced tiered waiver systems. For instance, the 'One-Time Settlement' (OTS) scheme in Delhi and Haryana allowed for waivers up to 75% on older pending challans.
                        </p>
                    </div>
                    <div className="grid md:grid-cols-2 gap-8">
                        <div className="p-10 bg-gradient-to-br from-[#f8f9fa] to-[#e9ecef] rounded-[2.5rem] border border-gray-200 shadow-inner">
                            <h4 className="text-xl font-black text-blue-900 mb-6 uppercase tracking-widest">Minor Infractions</h4>
                            <ul className="space-y-4 text-gray-600 font-medium">
                                <li className="flex justify-between"><span>No Parking:</span> <span className="text-green-600 font-black">50% Waiver</span></li>
                                <li className="flex justify-between"><span>Wrong Way:</span> <span className="text-green-600 font-black">40% Waiver</span></li>
                                <li className="flex justify-between"><span>Triple Riding:</span> <span className="text-green-600 font-black">60% Waiver</span></li>
                                <li className="flex justify-between"><span>Seat Belt:</span> <span className="text-green-600 font-black">50% Waiver</span></li>
                            </ul>
                        </div>
                        <div className="p-10 bg-gradient-to-br from-[#1E293B] to-[#0F172A] rounded-[2.5rem] text-white shadow-2xl">
                            <h4 className="text-xl font-black text-[#D2A02A] mb-6 uppercase tracking-widest">High-Penalty Cases</h4>
                            <ul className="space-y-4 text-gray-300 font-medium">
                                <li className="flex justify-between"><span>Speeding:</span> <span className="text-[#D2A02A] font-black">50% Discount</span></li>
                                <li className="flex justify-between"><span>No PUC:</span> <span className="text-[#D2A02A] font-black">Negotiable (High)</span></li>
                                <li className="flex justify-between"><span>No Insurance:</span> <span className="text-[#D2A02A] font-black">50% Discount</span></li>
                                <li className="flex justify-between"><span>Dangerous Drive:</span> <span className="text-red-400 font-black">Panel Discretion</span></li>
                            </ul>
                        </div>
                    </div>
                    <div className="mt-12 p-8 bg-yellow-50 rounded-[2rem] border-l-8 border-yellow-400">
                        <p className="text-lg text-yellow-900 font-medium italic leading-relaxed">
                            "Important Note: Waivers are not cumulative. A 50% waiver means you pay 50% of the original fine amount. In some jurisdictions, the Judge may offer a 'Flat Fee' settlement (e.g., ₹100 per challan) for bulk clearances of older notices."
                        </p>
                    </div>
                </section>

                {/* Virtual vs Physical */}
                <section id="virtual-vs-physical" className="scroll-mt-32">
                    <h2 className="text-2xl md:text-5xl font-black text-gray-900 mb-12">Virtual vs Physical Lok Adalat</h2>
                    <div className="prose prose-2xl max-w-none text-gray-700 leading-relaxed space-y-10">
                        <p>
                            Post-2020, the judicial system in India underwent a massive digital transformation. This led to the birth of the <strong>E-Lok Adalat</strong>. For traffic challans, this has been life-changing for many motorists who simply didn't have the time to spend an entire day in a crowded court building.
                        </p>
                        <div className="flex flex-col md:flex-row gap-10 mt-10">
                            <div className="flex-1 space-y-6">
                                <h4 className="text-2xl font-bold text-gray-900 border-b-4 border-blue-500 pb-2 inline-block">The Virtual Experience</h4>
                                <ul className="space-y-4 list-disc pl-6 text-gray-600">
                                    <li>Entirely paperless through the SLSA portal.</li>
                                    <li>Video conferencing links for conciliation.</li>
                                    <li>Immediate digital award and receipt.</li>
                                    <li>Best for camera-based camera challans.</li>
                                </ul>
                            </div>
                            <div className="flex-1 space-y-6">
                                <h4 className="text-2xl font-bold text-gray-900 border-b-4 border-[#D2A02A] pb-2 inline-block">The Physical Experience</h4>
                                <ul className="space-y-4 list-disc pl-6 text-gray-600">
                                    <li>Face-to-face interaction with the judicial panel.</li>
                                    <li>Opportunity to bring physical evidence (original papers).</li>
                                    <li>On-the-spot vehicle release orders.</li>
                                    <li>Best for serious document-related seizures.</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </section>

                {/* Historical Context */}
                <section id="historical-context" className="scroll-mt-32">
                    <h2 className="text-2xl md:text-5xl font-black text-gray-900 mb-12">The Genesis: A Historical Perspective of Lok Adalats</h2>
                    <div className="prose prose-2xl max-w-none text-gray-700 leading-relaxed space-y-10">
                        <p>
                            To appreciate the current efficiency of traffic Lok Adalats, one must look back at the origins of the "People's Court" movement in India. The concept of Lok Adalats is an age-old Indian tradition where community elders settled disputes. However, in modern legal history, the movement was spearheaded by the legendary Justice P.N. Bhagwati (former Chief Justice of India) and Justice V.R. Krishna Iyer.
                        </p>
                        <p>
                            The first formalized Lok Adalat was held in 1982 in Junagadh, Gujarat. What started as an experiment to settle land disputes and marital discords has today evolved into a high-tech judicial tool for clearing millions of traffic violations. The <strong>Legal Services Authorities Act of 1987</strong> provided the statutory backbone to this movement, ensuring that an 'Award' passed by the Lok Adalat is final and binding.
                        </p>
                        <p>
                            In the 1990s, traffic violations were settled in "Mobile Courts," where a judge would literally sit in a traffic van and adjudicate on the spot. Today, the "Mobile" aspect has shifted from physical vans to mobile applications and digital portals, but the spirit remains the same: <em>Justice at the doorstep of the citizen.</em>
                        </p>
                    </div>
                </section>

                {/* AI and Surveillance */}
                <section id="ai-and-surveillance" className="scroll-mt-32 bg-gray-50 p-10 md:p-20 rounded-[4rem] border border-gray-100 shadow-inner">
                    <h2 className="text-2xl md:text-5xl font-black text-gray-900 mb-12">The Digital Sentinel: AI & Traffic Enforcement</h2>
                    <div className="prose prose-2xl max-w-none text-gray-700 leading-relaxed space-y-10">
                        <p>
                            The surge in traffic challans is directly proportional to the deployment of <strong>Intelligent Traffic Management Systems (ITMS)</strong>. These systems use high-definition cameras equipped with <strong>Automatic Number Plate Recognition (ANPR)</strong> technology.
                        </p>
                        <ul className="grid md:grid-cols-2 gap-8 list-none p-0">
                            <li className="bg-white p-8 rounded-3xl shadow-sm border border-gray-100 flex flex-col gap-4">
                                <span className="text-[#D2A02A] font-black text-xl uppercase tracking-widest">E-Sensing</span>
                                <p className="text-base">Sophisticated sensors under the asphalt that detect over-speeding even before the camera flashes.</p>
                            </li>
                            <li className="bg-white p-8 rounded-3xl shadow-sm border border-gray-100 flex flex-col gap-4">
                                <span className="text-blue-600 font-black text-xl uppercase tracking-widest">Heat Mapping</span>
                                <p className="text-base">AI identifies traffic congestion patterns and automatically flags "Gridlock Violations" like blocking the box.</p>
                            </li>
                        </ul>
                        <p className="mt-12 bg-white/50 p-8 rounded-3xl border border-gray-100 italic">
                            While technology reduces human error, it is not infallible. We often encounter cases of 'Identity Theft' where a fake number plate leads to a challan for an innocent driver. Lok Adalats provide the platform to challenge such "False Positives" without the expense of a regular trial.
                        </p>
                    </div>
                </section>

                {/* Constitutional Perspective */}
                <section id="constitutional-logic" className="scroll-mt-32">
                    <h2 className="text-2xl md:text-5xl font-black text-gray-900 mb-12 underline decoration-[#D2A02A] decoration-8 underline-offset-8">The Constitutional Logic of Lok Adalats</h2>
                    <div className="prose prose-2xl max-w-none text-gray-800 leading-relaxed space-y-12">
                        <p>
                            The Lok Adalat is not just a convenience; it is a manifestation of <strong>Article 39A of the Constitution of India</strong>, which mandates "Equal Justice and Free Legal Aid." The state is duty-bound to ensure that the operation of the legal system promotes justice on a basis of equal opportunity.
                        </p>
                        <div className="p-12 bg-gradient-to-r from-gray-900 to-black text-white rounded-[3rem] shadow-2xl">
                            <h4 className="text-3xl font-bold mb-8 text-[#D2A02A]">Finality & No Appeal</h4>
                            <p className="text-xl leading-relaxed text-gray-300">
                                One of the most unique features of a Lok Adalat Award is that it is <strong>Non-Appealable</strong>. This might seem restrictive, but it is actually a boon for the citizen. It ensures that the police or the state cannot drag you to the High Court if they are unhappy with the waiver. Once the Award is signed, the chapter is closed forever. This provides "Legal Finality" which is rare in the Indian judicial system.
                            </p>
                        </div>
                    </div>
                </section>

                {/* The Future of Traffic Sentencing */}
                <section id="future-of-sentencing" className="scroll-mt-32">
                    <h2 className="text-2xl md:text-5xl font-black text-gray-900 mb-12">The Horizon: The Future of Traffic Sentencing</h2>
                    <div className="prose prose-2xl max-w-none text-gray-700 leading-relaxed space-y-10">
                        <p>
                            As we move towards 2030, the legal landscape of traffic enforcement is shifting from purely punitive measures to "Rehabilitative Jurisprudence." In several developed economies, and now being discussed in Indian Law Commission circles, is the concept of 'Voucher-based Traffic Education'. Instead of paying a fine, first-time offenders in a Lok Adalat might be asked to complete a digital road safety module.
                        </p>
                        <p>
                            Furthermore, <strong>Predictive Policing</strong> is making its way into traffic management. By analyzing the time and location density of violations, authorities can now predict where an accident is likely to happen and deploy preventive measures. Lok Adalats of the future will likely use AI to automatically offer 'Settlement Brackets' based on the violator's past 10-year driving record, rewarding "Safe Drivers" with much higher waivers on accidental lapses.
                        </p>
                    </div>
                </section>

                {/* AMA's Proprietary Framework */}
                <section id="ama-framework" className="scroll-mt-32 bg-blue-50 p-10 md:p-20 rounded-[4rem] border border-blue-100">
                    <h2 className="text-2xl md:text-5xl font-black text-blue-900 mb-12">The AMA '3-C' Challan Analysis Framework</h2>
                    <div className="grid md:grid-cols-3 gap-10">
                        <div className="p-8 bg-white rounded-3xl shadow-sm">
                            <h4 className="text-xl font-bold mb-4 text-blue-600">01. Categorization</h4>
                            <p className="text-sm text-gray-500">Separating camera-based notices from court summons and active warrants.</p>
                        </div>
                        <div className="p-8 bg-white rounded-3xl shadow-sm">
                            <h4 className="text-xl font-bold mb-4 text-blue-600">02. Contestation</h4>
                            <p className="text-sm text-gray-500">Drafting arguments based on lack of photographic evidence or jurisdiction errors.</p>
                        </div>
                        <div className="p-8 bg-white rounded-3xl shadow-sm">
                            <h4 className="text-xl font-bold mb-4 text-blue-600">03. Clearance</h4>
                            <p className="text-sm text-gray-500">Liaising with the Traffic Police tech-wing to ensure the portal reflects 'Paid' status in 24 hours.</p>
                        </div>
                    </div>
                </section>

                {/* Case Studies / Reviews */}
                <section id="reviews" className="scroll-mt-32">
                    <h2 className="text-xl md:text-4xl font-black text-gray-900 mb-12 text-center">Success Stories: Triumphs in Lok Adalat</h2>
                    <div className="grid md:grid-cols-1 gap-12">
                        {[
                            {
                                title: "Case 1: The Fleet Management Victory",
                                context: "A Delhi-based logistics firm had 450+ pending challans across its fleet of 50 trucks. The total penalty amount sitting on the Vahan portal was exceeding ₹18 Lakhs. This was preventing their permit renewals.",
                                strategy: "AMA Legal Solutions grouped these challans by vehicle category and violation type. We identified 120+ duplicate notices and another 80 where the 'No Entry' signs were misleading.",
                                outcome: "In the Special Traffic Lok Adalat, we secured an overall waiver of 68%. The entire pool was settled for ~₹5.8 Lakhs, and all vehicles were cleared within 4 working days.",
                                icon: <FaCheckCircle className="text-green-500" />
                            },
                            {
                                title: "Case 2: Recovering an Impounded Vehicle",
                                context: "Rahul's SUV was impounded in Pune for 'Drunk Driving' and 'Reckless Driving'. The court-sent challans had been pending for 14 months, and a summons had already been issued.",
                                strategy: "We move an application to bring his case to the Lok Adalat. While 'Drunk Driving' is tough, we highlighted that it was a first-time offence and he had already served a 14-month vehicle-less period.",
                                outcome: "The Judge passed a compassionate order. Rahul paid the fine for reckless driving, got a strong warning for the other charge, and the vehicle was ordered for immediate release.",
                                icon: <FaStar className="text-[#D2A02A]" />
                            },
                            {
                                title: "Case 3: The NRI Dilemma (Remote Settlement)",
                                context: "A vehicle owner living in London discovered 15 'Speeding' challans on his family car in Bangalore during a routine Vahan Check. He couldn't travel back just for a court appearance.",
                                strategy: "We utilized the E-Lok Adalat / Virtual Court integration for Karnataka. Representing him via a Power of Attorney (PoA), we presented evidence that the driver was different in all cases.",
                                outcome: "Success! The Judge waived 50% of the fine. The total of ₹15,000 was brought down to ₹7,500, paid online, and the Vahan records were cleared without the client ever leaving London.",
                                icon: <FaGlobe className="text-blue-500" />
                            },
                            {
                                title: "Case 4: The 2nd Hand Buyer's Nightmare",
                                context: "Sneha bought a used luxury sedan, only to find ₹45,000 in pending challans from the previous owner's tenure. Transaction was stuck as ownership transfer was blocked.",
                                strategy: "We filed a pre-litigation application in the Lok Adalat, showing the 'Sale Affidavit' and the date of ownership transfer. We argued that the liability should follow the driver at the time of offense.",
                                outcome: "While the law usually attaches fine to the vehicle, the Judge allowed a 'Conditional Settlement' where Sneha paid a heavily discounted 'Compounding Fee' of ₹12,000 to unblock the transfer immediately.",
                                icon: <FaCreditCard className="text-red-500" />
                            }
                        ].map((caseStudy, i) => (
                            <div key={i} className="bg-white p-10 rounded-[2.5rem] border border-gray-100 shadow-2xl relative overflow-hidden group hover:scale-[1.01] transition-all">
                                <div className="absolute top-0 right-0 p-8 text-8xl opacity-5 text-gray-200">{caseStudy.icon}</div>
                                <h3 className="text-2xl md:text-3xl font-black text-gray-900 mb-10 border-b-4 border-gray-100 pb-6">{caseStudy.title}</h3>
                                <div className="grid md:grid-cols-3 gap-12">
                                    <div>
                                        <h5 className="font-bold text-[#D2A02A] mb-4 uppercase text-xs tracking-widest italic">The Challenge</h5>
                                        <p className="text-sm text-gray-500 leading-relaxed font-medium">{caseStudy.context}</p>
                                    </div>
                                    <div>
                                        <h5 className="font-bold text-blue-600 mb-4 uppercase text-xs tracking-widest italic">Our Strategy</h5>
                                        <p className="text-sm text-gray-500 leading-relaxed font-medium">{caseStudy.strategy}</p>
                                    </div>
                                    <div>
                                        <h5 className="font-bold text-green-600 mb-4 uppercase text-xs tracking-widest italic">The Win</h5>
                                        <p className="text-sm text-gray-500 leading-relaxed font-black">{caseStudy.outcome}</p>
                                    </div>
                                </div>
                            </div>
                        ))}
                    </div>
                </section>

                {/* Legal Glossary */}
                <section id="glossary" className="scroll-mt-32">
                    <h2 className="text-xl md:text-4xl font-black text-gray-900 mb-10">Technical Appendix: Traffic Law Glossary</h2>
                    <div className="grid md:grid-cols-2 gap-8">
                        {[
                            { term: "Compounding", desc: "A method where the violator pays a fine to the state to avoid a trial. Most traffic offenses are compoundable." },
                            { term: "Non-Compoundable", desc: "Serious offenses like causing a fatal accident which cannot be settled by fine alone and require a trial." },
                            { term: "Award", desc: "The final decision of a Lok Adalat. It is binding and treated as a decree of a Civil Court." },
                            { term: "Pre-Litigation", desc: "The stage before a case is officially filed in court. Lok Adalats often settle thousands of cases at this stage." },
                            { term: "SLSA / DSLSA", desc: "State (or Delhi) Legal Services Authority, the main body that organizes these courts." },
                            { term: "Virtual Court", desc: "An online platform for the adjudication of petty traffic offenses without physical presence." },
                            { term: "Notice Period", desc: "The 90-day window during which a challan can be paid at a police station before it is sent to court." },
                            { term: "Acquittal", desc: "A judgment that a person is not guilty of the offense with which they have been charged." }
                        ].map((item, i) => (
                            <div key={i} className="flex gap-6 p-6 bg-gray-50 rounded-2xl border border-gray-100">
                                <div className="text-2xl font-black text-[#D2A02A]">{i+1}.</div>
                                <div>
                                    <h5 className="font-bold text-gray-900 mb-2">{item.term}</h5>
                                    <p className="text-sm text-gray-500">{item.desc}</p>
                                </div>
                            </div>
                        ))}
                    </div>
                </section>

                {/* FAQ Seed */}
                <section id="faqs" className="scroll-mt-32">
                    <h2 className="text-xl md:text-4xl font-black text-gray-900 mb-12 text-center underline decoration-[#D2A02A] decoration-8 underline-offset-[12px]">The Ultimate Traffic Challan FAQ</h2>
                    <div className="space-y-6">
                        {faqs.map((faq, i) => (
                            <div key={i} className="p-8 bg-gray-50 rounded-[2rem] border border-gray-100 hover:border-[#D2A02A]/30 transition-all group">
                                <h3 className="text-lg md:text-xl font-bold mb-4 text-gray-900 group-hover:text-[#D2A02A] transition-colors flex gap-4">
                                    <span className="text-[#D2A02A] opacity-30">Q{i+1}.</span> {faq.question}
                                </h3>
                                <p className="text-gray-700 leading-relaxed text-base pl-10 border-l-2 border-[#D2A02A]/10">
                                    {faq.answer}
                                </p>
                            </div>
                        ))}
                    </div>
                </section>

              </div>
            </div>

            {/* Right Sidebar Widgets */}
            <div className="hidden lg:block sticky top-28 space-y-10">
                <div className="p-8 bg-white rounded-[2.5rem] shadow-2xl border border-gray-100 text-center flex flex-col items-center">
                    <div className="w-20 h-20 bg-green-50 rounded-full flex items-center justify-center mb-6">
                        <FaShieldAlt className="text-4xl text-green-600" />
                    </div>
                    <h4 className="font-black text-xl mb-4 text-gray-900">Certified Legal Help</h4>
                    <p className="text-sm text-gray-500 mb-8 leading-relaxed">Join 10,000+ satisfied clients who cleared their road records with AMA Legal Solutions.</p>
                    <Link href="/contact" className="w-full bg-[#D2A02A] text-white font-bold py-4 rounded-2xl shadow-lg hover:shadow-xl transition-all">Get Free Consultation</Link>
                </div>

                <div className="p-8 bg-gray-900 rounded-[2.5rem] shadow-2xl text-white">
                    <h4 className="font-bold text-[#D2A02A] mb-8 uppercase tracking-widest text-xs text-center">Quick Links</h4>
                    <ul className="space-y-4">
                        <li className="flex items-center gap-3 text-sm font-medium text-gray-300 hover:text-white cursor-pointer"><FaCar /> Check Delhi Challan</li>
                        <li className="flex items-center gap-3 text-sm font-medium text-gray-300 hover:text-white cursor-pointer"><FaMotorcycle /> Check Bangalore Challan</li>
                        <li className="flex items-center gap-3 text-sm font-medium text-gray-300 hover:text-white cursor-pointer"><FaMoneyBillWave /> Pay Virtual Court Fine</li>
                    </ul>
                </div>
            </div>
          </div>
        </div>

        {/* States Grid */}
        <div className="bg-white py-24">
            <div className="container mx-auto px-4">
                <h2 className="text-3xl md:text-6xl font-black text-center mb-20 text-gray-900">Challan Lok Adalats Available In:</h2>
                <GenericStatesGrid 
                    serviceName="Traffic Challan Defense"
                    servicePath="traffic-challan-settlement"
                />
            </div>
        </div>
      </div>
    </>
  );
}
