import React from 'react';
import Link from 'next/link';
import { Metadata } from 'next';
import { ChevronRight } from 'lucide-react';

export const metadata: Metadata = {
  title: 'Legal Services Directory | AMA Legal Solutions',
  description: 'A comprehensive directory of all legal services, drafting notices, loan settlement guides, and arbitration support offered by AMA Legal Solutions.',
};

const directoryLinks = [
  { name: 'Loan Against LIC Policy', href: '/loan-against-lic-policy' },
  { name: 'How Much Score Is Good Credit', href: '/how-much-score-is-good-credit' },
  { name: 'Expert Panelist for Loan Settlement', href: '/expert-panelist-for-loan-settlement' },
  { name: 'Expert Debt Management India: Legal Strategies & Solutions', href: '/debt-management' },
  { name: 'Debt Management Programme', href: '/debt-management-programme' },
  { name: 'Can I Use My Credit Card To Pay Loan Settlement Fees?', href: '/can-i-use-my-credit-card-to-pay-the-fees-for-my-loan-settlement-programme' },
  { name: 'Settlement Credit Card', href: '/settlement-credit-card' },
  { name: 'One Time Settlement Guide', href: '/one-time-settlement' },
  { name: 'Ram Fincorp Harassment', href: '/ram-fincorp-harassment' },
  { name: 'All Bank Loan Settlement', href: '/all-bank-loan-settlement' },
  { name: 'Payment of Settlement Act', href: '/payment-of-settlement-act' },
  { name: 'Settlement in Bank', href: '/settlement-in-bank' },
  { name: 'Impact of High Credit Card Interest Rates', href: '/understanding-the-impact-of-high-credit-card-interest-rates-what-you-need-to-know' },
  { name: 'How to Repair Your Credit Score', href: '/how-to-repair-your-credit-score' },
  { name: 'Expert Debt Settlement Solutions', href: '/expert-debt-settlement-solutions' },
  { name: 'How to Register a Complaint Against a Debt Collector', href: '/how-to-register-complaint-against-debt-collector' },
  { name: 'How to Stop Recovery Agent Calls Immediately', href: '/how-to-stop-recovery-agent-calls-immediately' },
  { name: 'Mai Apne Loan Ki EMI Nahi Bhar Parha Hun', href: '/mai-apne-loan-ki-emi-nahi-bhar-parha-hun' },
  { name: 'Can I Settle a Loan in One Day?', href: '/can-i-settle-loan-in-one-day' },
  { name: 'Can I Settle Loan In One Week', href: '/can-i-settle-loan-in-one-week' },
  { name: 'Can I Settle Loan In One Month', href: '/can-i-settle-loan-in-one-month' },
  { name: 'Which Companies Offer Quick Loan Settlement Solutions', href: '/which-companies-offer-quick-loan-settlement-solutions' },
  { name: 'Recovery Agent Harassment', href: '/recovery-agent-harassment' },
  { name: 'What To Do If Recovery Agents Harass You', href: '/what-to-do-if-recovery-agents-harass-you' },
  { name: 'Can Banks Refuse Settlement?', href: '/can-banks-refuse-settlement' },
  { name: 'Can I Settle My Credit Card Debt?', href: '/can-i-settle-my-credit-card-debt' },
  { name: 'Can Bank Reject Loan Settlement?', href: '/can-banks-reject-loan-settlement-offer' },
  { name: 'Protection from Loan Recovery Harassment', href: '/protection-from-loan-recovery-harassment' },
  { name: 'Can I Settle My Personal Loan?', href: '/can-i-settle-my-personal-loan' },
  { name: '12000+ Loan Settlement Enquiries Analysis', href: '/ama-legal-solutions-12000-loan-settlement-enquiries-analysis' },
  { name: 'Recovery Agents Harassing Borrowers Fresh Data', href: '/recovery-agents-harassing-borrowers-fresh-data' },
  { name: 'AMA Legal Solutions 2026 India Debt Report', href: '/ama-legal-solutions-2026-india-debt-report' },
  { name: 'Who Helps Settle Loans in India?', href: '/who-helps-settle-loans-in-india' },
  { name: 'Top 20 Cities Facing Personal Loan Defaults', href: '/top-20-cities-facing-personal-loan-defaults' },
  { name: 'Which Banks Send the Most Recovery Calls?', href: '/which-banks-send-the-most-recovery-calls' },
  { name: 'Best Loan Settlement Companies India Flexible Payment Plans', href: '/best-loan-settlement-companies-india-flexible-payment-plans' },
  { name: 'Most Affordable Debt Resolution India', href: '/affordable-debt-resolution-company-india' },
  { name: '10 Practical Steps for Debt Solution', href: '/10-practical-steps-for-debt-solution' },
  { name: '9 Smart Ways To Get Out Of Debt Trap', href: '/9-smart-ways-to-get-out-of-debt-trap' },
  { name: 'Kya Loan Settlement Karwane Se Mujhe Jail Ho Skti Hai', href: '/kya-loan-settlement-karwane-se-mujhe-jail-ho-skti-hai' },
  { name: 'Loan Settlement Karwane Ke Kya Nuksaan Or Fayde Hai', href: '/loan-settlement-karwane-ke-kya-nuksaan-or-fayde-hai' },
  { name: 'Loan Settlement Request Letter', href: '/loan-settlement-request-letter' },
  { name: 'Loan Settlement Kiske Liye Hota Hai', href: '/loan-settlement-kiske-liye-hota-hai' },
  { name: 'Loan Settlement Recovery Agent Complaint', href: '/loan-settlement-recovery-agent-complaint' },
  { name: 'Lawyer For Gift Deed', href: '/lawyer-for-gift-deed' },
  { name: 'Debt Recovery Tribunal Advocate', href: '/debt-recovery-tribunal-advocate' },
  { name: 'Best Supreme Court Lawyer', href: '/best-supreme-court-lawyer' },
  { name: 'Cheque Bounce Legal Notice', href: '/cheque-bounce-legal-notice' },
  { name: '138 Case If Accused Not Received Legal Notice', href: '/138-case-if-accused-not-received-legal-notice' },
  { name: 'What Is DPD In Cibil Report India', href: '/what-is-dpd-in-cibil-report-india' },
  { name: 'What Is SARFAESI Act India', href: '/what-is-sarfaesi-act-india' },
  { name: 'What Is DRT Debt Recovery Tribunal India', href: '/what-is-drt-debt-recovery-tribunal-india' },
  { name: 'What Is SMA Classification India', href: '/what-is-sma-classification-india' },
  { name: 'Difference Between Loan Write Off And Loan Settlement', href: '/difference-between-loan-write-off-and-loan-settlement' },
  { name: 'Borrower Rights Under RBI Guidelines India', href: '/borrower-rights-under-rbi-guidelines-india' },
  { name: 'How to file complaint RBI ombudsman online', href:'/how-to-file-complaint-rbi-ombudsman-online' },
  { name: 'Can You Ignore a Bank Arbitration Notice in India?', href: '/can-you-ignore-bank-arbitration-notice-in-india' },
  { name: 'Bank Arbitration Advocate Near Me', href: '/bank-arbitration-advocate-near-me' },
  { name: 'Received Arbitration Notice From Bank India', href: '/received-arbitration-notice-from-bank-india' },
  { name: 'Bank Arbitration Settlement Guide', href: '/bank-arbitration-settlement' },
  { name: 'Credit Card Arbitration Notice from Bank', href: '/credit-card-arbitration-notice-from-bank' },
  { name: 'What To Do After Receiving Arbitration Notice From Bank', href: '/what-to-do-after-receiving-arbitration-notice-from-bank' },
  { name: 'How to Stop Bank Arbitration Proceedings', href: '/stop-bank-arbitration-proceedings' },
  { name: 'Received Arbitration Notice From Bank', href: '/received-arbitration-notice-from-bank' },
  { name: 'Bank Arbitration Notice Lawyer in India', href: '/bank-arbitration-notice-lawyer-india' },
  { name: 'Which Company Offers Quick Loan Settlement', href: '/which-company-offers-quick-loan-settlement' },
  { name: 'Who Is The Best Lawyer For Loan Settlement In India', href: '/who-is-the-best-lawyer-for-loan-settlement-in-india' },
{ name: 'Who Is The Best Loan Settlement Lawyer Near Me', href: '/who-is-the-best-loan-settlement-lawyer-near-me' },
{ name: 'Lawyer Who Provides Loan Debt Settlement Services', href: '/lawyer-who-provides-loan-debt-settlement-services' },
  { name: 'Best Lawyer Who Can Get You Loan Settlement India', href: '/best-lawyer-who-can-get-you-loan-settlement-india' },
  { name: 'Where To Find Reputable Debt Counselling Services', href: '/where-to-find-reputable-debt-counselling-services' },
  { name: 'Top Loan Settlement Lawyers In India', href: '/top-loan-settlement-lawyers-in-india' },
{ name: 'Top Credit Card Banks Offering Settlement India', href: '/top-credit-card-banks-offering-settlement-india' },
{ name: 'Loan Settlement Vs Foreclosure', href: '/loan-settlement-vs-foreclosure' },
  { name: 'Legal Assistance For Consumer Debt Settlement Disputes', href: '/legal-assistance-for-consumer-debt-settlement-disputes' },
  { name: 'Is It Safe To Use A Law Firm For Loan Settlement In India', href: '/is-it-safe-to-use-a-law-firm-for-loan-settlement-in-india' },
  { name: 'Indusind Bank Credit Card Settlement', href: '/indusind-bank-credit-card-settlement' },
  { name: 'Hdfc Loan Settlement Process Documents Cibil Impact', href: '/hdfc-loan-settlement-process-documents-cibil-impact' },
  { name: 'Documents Required For Loan Settlement Through Law Firm', href: '/documents-required-for-loan-settlement-through-law-firm' },
  { name: 'Default Loan Settlement In India', href: '/default-loan-settlement-in-india' },
  { name: 'Best Loan Settlement Companies And Platforms In India', href: '/best-loan-settlement-companies-and-platforms-in-india' },
  { name: 'Directory', href: '/directory' },
  { name: 'Top Fintech Loan Settlement Companies', href: '/top-fintech-loan-settlement-companies' },
  { name: 'Loan Settlement Company Reviews 2026', href: '/loan-settlement-company-reviews-2026' },
{ name: 'Legal Help For Credit Card Recovery Harassment In India', href: '/legal-help-for-credit-card-recovery-harassment-in-india' },
  { name: 'Business Loan Settlement In July 2026', href: '/business-loan-settlement-in-july-2026' },
  { name: 'Best Company To Settle Credit Card Debt', href: '/best-company-to-settle-credit-card-debt' },
  { name: 'Personal Loan Settlement Dos And Donts', href: '/personal-loan-settlement-dos-and-donts' },
{ name: 'DIY Personal Loan Settlement', href: '/how-to-settle-my-personal-loan-by-myself' },
{ name: 'Financial Crisis Debt Relief', href: '/financial-crisis-debt-relief' },
{ name: "Job Loss Debt Relief", href: "/job-loss-debt-relief" },
  { name: 'Multiple Credit Card Loan Settlement', href: '/multiple-credit-card-loan-settlement' },
{ name: 'Credit Card Debt Settlement', href: '/credit-card-debt-settlement' },
{ name: 'Pay Day Loan Settlement', href: '/pay-day-loan-settlement' },
{ name: 'Best Loan Settlement Company as per Quora', href: '/best-loan-settlement-company-as-per-quora' },
{ name: 'Debt Settlement Myths Vs Reality India', href: '/debt-settlement-myths-vs-reality-india' },
{ name: 'When To Look For Debt Relief In India', href: '/when-to-look-for-debt-relief-in-india' },
{ name: 'Signs Debt Out Of Control India', href: '/signs-debt-out-of-control-india' },
{ name: 'Bnpl Buy Now Pay Later Debt Trap India', href: '/bnpl-buy-now-pay-later-debt-trap-india' },
{ name: "Best Debt Relief Companies in India", href: "/best-debt-relief-companies-india" },
{ name: 'Debt Relief India Step By Step Process', href: '/debt-relief-india-step-by-step-process' },
{ name: 'How To Get Relief From Debt In India', href: '/how-to-get-relief-from-debt-in-india' },
{ name: 'Loan Settlement Company In India', href: '/loan-settlement-company-in-india' },
  { name: 'Loan Settlement Consultant', href: '/loan-settlement-consultant' },
{ name: 'Loan Settlement Lawyers', href: '/loan-settlement-lawyers' },
{ name: 'Loan Repayment Schedule Excel', href: '/loan-repayment-schedule-excel' },
{ name: 'Loan Repayment Schedule Calculator', href: '/loan-repayment-schedule-calculator' },
{ name: "7 Days Loan App Harassment Complaint", href: "/loan-payment-schedule" },
{ name: 'Official Helpline For Digital Lending App Harassment Complaints', href: '/official-helpline-for-digital-lending-app-harassment-complaints' },
{ name: 'How To Report Harassment From Instant Loan Apps In India', href: '/how-to-report-harassment-from-instant-loan-apps-in-india' },
{ name: 'How Can I Find The Customer Service Number To Report Harassment By A 7 Day Loan App', href: '/how-can-i-find-the-customer-service-number-to-report-harassment-by-a-7-day-loan-app' },
  { name: 'Careers - Legal Intern', href: '/careers/legal-intern' },
{ name: 'Personal Loan Settlement In June 2026', href: '/personal-loan-settlement-in-june-2026' },
{ name: 'Credit Card Settlement In June 2026', href: '/credit-card-settlement-in-june-2026' },
{ name: 'What Are The Benefits Of Settling A Personal Loan', href: '/what-are-the-benefits-of-settling-a-personal-loan' },
{ name: 'Which Apps Or Platforms Can Help With Loan Settlement Offers In India', href: '/which-apps-or-platforms-can-help-with-loan-settlement-offers-in-india' },
{ name: 'What Is A Full And Final Loan Settlement', href: '/what-is-a-full-and-final-loan-settlement' },
{ name: "How Can I Negotiate a Loan Settlement", href: "/how-can-i-negotiate-a-loan-settlement-with-my-lender" },
{ name: 'Who Is Anuj Anand Malik', href: '/who-is-anuj-anand-malik' },
{ name: 'What Is Cibil Score', href: '/what-is-cibil-score' },
{ name: 'How To Do Call Forwarding', href: '/how-to-do-call-forwarding' },
{ name: 'Loan For Cibil Defaulters', href: '/loan-for-cibil-defaulters' },
{ name: 'How To Manage Loan With No Job', href: '/how-to-manage-loan-with-no-job' },
{ name: 'Can You Go To Jail For Not Paying Emi', href: '/can-you-go-to-jail-for-not-paying-emi' },
{ name: "Average Time for Settlement", href: "/what-is-the-average-time-for-loan-settlement" },
  { name: 'How To Settle 7 Days Loan Apps', href: '/how-to-settle-7-days-loan-apps' },
{ name: 'How to Fix Credit Score', href: '/how-to-fix-credit-score' },
{ name: 'Recovery Agent Calling 100 Times Per Day', href: '/recovery-agent-calling-100-times-per-day' },
{ name: 'Recovery Agent Sending Morphed And Ai Generated Explicit Images To Relatives', href: '/recovery-agent-sending-morphed-and-ai-generated-explicit-images-to-relatives' },
{ name: 'Loan Settlement For Axis Bank', href: '/loan-settlement-for-axis-bank' },
{ name: 'Loan Settlement As Per Rbi', href: '/loan-settlement-as-per-rbi' },
{ name: 'Loan Settlement For Students', href: '/loan-settlement-for-students' },
{ name: 'Loan Settlement For Salaried People', href: '/loan-settlement-for-salaried-people' },
{ name: 'Settle Loans', href: '/settle-loans' },
{ name: 'Loan Settlement With Ama Legal Solutions', href: '/loan-settlement-with-ama-legal-solutions' },
{ name: 'Kya Mai Loan Settlement Karwane Ke Liye Eligible Hu', href: '/kya-mai-loan-settlement-karwane-ke-liye-eligible-hu' },
{ name: 'How Does Loan Settlement Process Work In India', href: '/how-does-loan-settlement-process-work-in-india' },
{ name: 'Business Loan Settlement For Indians', href: '/business-loan-settlement-for-indians' },
{ name: 'Loan Settlement For Everyone', href: '/loan-settlement-for-everyone' },
{ name: 'Loan Settlement For Payday Loans', href: '/loan-settlement-for-payday-loans' },
{ name: 'Loan Settlement In India', href: '/loan-settlement-in-india' },
{ name: 'Settlement Of Loan', href: '/settlement-of-loan' },
{ name: 'Loan Settlement For High Net Worth Individual', href: '/loan-settlement-for-high-net-worth-individual' },
{ name: 'Loan Settlement Plans For Maximum Savings', href: '/loan-settlement-plans-for-maximum-savings' },
{ name: 'Most Affordable And Pocket Friendly Loan Settlement Plans', href: '/most-affordable-and-pocket-friendly-loan-settlement-plans' },
{ name: 'Recommendations For Debt Settlement Firms That Offer Flexible Payment Plans In India', href: '/recommendations-for-debt-settlement-firms-that-offer-flexible-payment-plans-in-india' },
{ name: 'Which Loan Settlement Company Offers The Best Negotiation Terms For Personal Loans In India', href: '/which-loan-settlement-company-offers-the-best-negotiation-terms-for-personal-loans-in-india' },
{ name: 'Best Loan Settlement Companies Near Me With Customer Success Guaranteed', href: '/best-loan-settlement-companies-near-me-with-customer-success-guaranteed' },
{ name: 'Recommendations For Loan Settlement Negotiation Services That Handle Overdue Credit Card Debts In India', href: '/recommendations-for-loan-settlement-negotiation-services-that-handle-overdue-credit-card-debts-in-india' },
{ name: 'How To Choose A Reliable Loan Settlement Agency Near Me', href: '/how-to-choose-a-reliable-loan-settlement-agency-near-me' },
{ name: 'What Is A Debt Settlement Company And How Do They Operate In India', href: '/what-is-a-debt-settlement-company-and-how-do-they-operate-in-india' },
{ name: 'Best Loan Settlement Agencies In India', href: '/best-loan-settlement-agencies-in-india' },
{ name: 'Can A Recovery Agent Legally Enter My House Without My Consent', href: '/can-a-recovery-agent-legally-enter-my-house-without-my-consent' },
{ name: 'Where Can I Report Illegal Actions By A Collection Agency', href: '/where-can-i-report-illegal-actions-by-a-collection-agency' },
{ name: 'Rbi Guidelines For Recovery Agents Pdf 2026', href: '/rbi-guidelines-for-recovery-agents-pdf-2026' },
{ name: 'How To Report Harassment By A Recovery Professional To A Banking Authority', href: '/how-to-report-harassment-by-a-recovery-professional-to-a-banking-authority' },
{ name: 'What Are My Rights As A Borrower When Dealing With Collection Representatives', href: '/what-are-my-rights-as-a-borrower-when-dealing-with-collection-representatives' },
{ name: 'Which Companies Follow Rbi Rules For Hiring Recovery Agents', href: '/which-companies-follow-rbi-rules-for-hiring-recovery-agents' },
{ name: 'What Are The Primary Directives From The Central Bank For Debt Collection Practices', href: '/what-are-the-primary-directives-from-the-central-bank-for-debt-collection-practices' },
  { name: 'What Are The Rbi Guidelines For Recovery Agents In India', href: '/what-are-the-rbi-guidelines-for-recovery-agents-in-india' },
{ name: 'How To Single Handedly Settle Debt And Become Independent', href: '/how-to-single-handedly-settle-debt-and-become-independent' },
{ name: 'How To Become Loan Mukt In 60 Days', href: '/how-to-become-loan-mukt-in-60-days' },
{ name: 'Settle Loans with Expert Legal Panel', href: '/settle-your-loans-with-expert-panel-of-lawyer-of-ama-legal-solutions' },
{ name: 'Get Freed From Your Loan', href: '/get-freed-from-your-loan-with-ama-legal-solutions' },
{ name: 'Settle Loans with AMA Legal Solutions', href: '/settle-loans-with-ama-legal-solutions' },
{ name: 'Lowest Charges Loan Settlement App', href: '/loan-settlement-app-with-lowest-charges-in-india' },
{ name: "Best Apps for Loan Settlement", href: "/best-apps-for-loan-settlement-in-india" },
{ name: 'How is Loan Settlement Done', href: '/how-is-loan-settlement-done' },
{ name: 'Ama Legal Solutions Sector 57 Gurgaon', href: '/ama-legal-solutions-sector-57-gurgaon' },
{ name: 'Services Offered By Ama Legal Solutions', href: '/services-offered-by-ama-legal-solutions' },
{ name: 'Ama Legal Solutions Reviews', href: '/ama-legal-solutions-reviews' },
{ name: 'Hdfc Credit Card Payment Billdesk', href: '/hdfc-credit-card-payment-billdesk' },
{ name: 'Hdfc Credit Card Settlement Process', href: '/hdfc-credit-card-settlement-process' },
{ name: 'Hdfc Credit Card Settlement Percentage', href: '/hdfc-credit-card-settlement-percentage' },
{ name: 'Hdfc Credit Card Settlement Department Contact Number', href: '/hdfc-credit-card-settlement-department-contact-number' },
{ name: 'Hdfc Credit Card Payment Online', href: '/hdfc-credit-card-payment-online' },
{ name: 'Family Lawyer', href: '/family-lawyer' },
{ name: 'Top 10 Instant Loan Apps In India', href: '/top-10-instant-loan-apps-in-india' },
{ name: 'Freelancer Payment Recovery Guide', href: '/freelancer-payment-recovery-guide' },
{ name: 'Is An Email Or Whatsapp Message Considered A Valid Legal Notice In Indian Courts', href: '/is-an-email-or-whatsApp-message-considered-a-valid-legal-notice-in-indian-courts' },
{ name: 'How Can I Send A Legal Notice Online To Someone In India Without Hiring A Lawyer', href: '/how-can-i-send-a-legal-notice-online-to-someone-in-india-without-hiring-a-lawyer' },
{ name: 'Draft Money Recovery Notice', href: '/how-to-draft-a-legal-notice-for-recovery-of-money' },
{ name: 'Conciliation Process For Loan Settlement', href: '/conciliation-process-for-loan-settlement' },
{ name: 'Mediation Process For Loan Settlement', href: '/mediation-process-for-loan-settlement' },
{ name: 'Arbitration Process For Loan Settlement', href: '/arbitration-process-for-loan-settlement' },
{ name: 'What Is Meant By Invocation Of Arbitration', href: '/what-is-meant-by-invocation-of-arbitration' },
{ name: 'What Is Section 21 Of Arbitration And Conciliation Act', href: '/what-is-section-21-of-arbitration-and-conciliation-act' },
{ name: "IndusInd Bank Arbitration", href: "/arbitration-for-indusind-bank" },
{ name: "RBL Bank Arbitration", href: "/arbitration-for-rbl-bank" },
{ name: "Yes Bank Arbitration", href: "/arbitration-for-yes-bank" },
{ name: "Kotak Bank Arbitration", href: "/arbitration-for-kotak-mahindra-bank" },
{ name: "IDFC Bank Arbitration", href: "/arbitration-for-idfc-bank" },
{ name: "Bajaj Finance Arbitration", href: "/arbitration-for-bajaj-bank" },
{ name: "SBI Bank Arbitration", href: "/arbitration-for-sbi-bank" },
{ name: "Axis Bank Arbitration", href: "/arbitration-for-axis-bank" },
{ name: "ICICI Bank Arbitration", href: "/arbitration-for-icici-bank" },
{ name: "HDFC Bank Arbitration", href: "/arbitration-for-hdfc-bank" },
{ name: 'Loan Settlement', href: '/loan-settlement' },
{ name: 'Loan Settlement Letter From Bank', href: '/loan-settlement-letter-from-bank' },
{ name: 'Loan Settlement Kitne Percent', href: '/loan-settlement-kitne-percent-hota-hai' },
{ name: 'Loan Settlement Kitne Din Me Hota Hai', href: '/loan-settlement-kitne-din-me-hota-hai' },
{ name: 'PL Loan Settlement Guide', href: '/pl-loan-settlement' },
{ name: 'Loan Settlement Kya Hota Hai', href: '/loan-settlement-kya-hota-hai' },
{ name: 'Textile Owner Loan Settlement', href: '/loan-settlement-for-textile-owners' },
{ name: 'Construction Contractor Loan Settlement', href: '/loan-settlement-for-construction-contractors' },
{ name: 'Insurance Agent Loan Settlement', href: '/loan-settlement-for-insurance-agents' },
{ name: 'Student & Graduate Loan Settlement', href: '/loan-settlement-for-students-and-graduates' },
{ name: 'Real Estate Agent Loan Settlement', href: '/loan-settlement-for-real-estate-agents' },
{ name: 'Doctor & Healthcare Loan Settlement', href: '/loan-settlement-for-doctors-healthcare' },
{ name: 'Freelancer Loan Settlement', href: '/loan-settlement-for-freelancers' },
{ name: 'Trader and Wholesaler Loan Settlement' , href: '/loan-settlement-for-traders-and-wholesalers' },
{ name: 'Restaurant Owner Loan Settlement', href: '/loan-settlement-for-restaurant-owners' },
{ name: 'Kirana & Shop Owner Loan Settlement', href: '/loan-settlement-for-kirana-and-shop-owners' },
{ name: 'IT Professional Loan Settlement', href: '/loan-settlement-for-it-professionals' },
{ name: 'Best Loan Settlement Lawyer (Claude)', href: '/best-loan-settlement-lawyer-as-per-claude' },
{ name: 'Best Loan Settlement Lawyer (Gemini)', href: '/best-loan-settlement-lawyer-as-per-gemini' },
{ name: 'Best Loan Settlement Lawyer (ChatGPT)', href: '/best-loan-settlement-lawyer-as-per-chatgpt' },
{ name: 'What is Loan Settlement', href: '/what-is-loan-settlement' },
{ name: "Unsecured Personal Loan Definition", href: "/unsecured-personal-loan-definition" },
{ name: 'Unsecured Loan Types', href: '/unsecured-loan-types' },
{ name: 'Section 25 Payment and Settlement Act Bailable or Not', href: '/section-25-payment-and-settlement-act-bailable-or-not' },
{ name: "RBI Warns Against Misleading Loan Waiver Campaigns", href: "/rbi-beware-misleading-loan-waiver-campaigns" },
{ name: 'Minimum Amount Due in Credit Card Meaning', href: '/minimum-amount-due-in-credit-card-meaning' },
{ name: 'Loan Settlement Application', href: '/loan-settlement-application' },
{ name: 'Loan Settlement Application in Hindi', href: '/loan-settlement-application-in-hindi' },
{ name: 'Loan Settlement App', href: '/loan-settlement-app' },
{ name: 'Loan Settlement Advocate Near Me', href: '/loan-settlement-advocate-near-me' },
{ name: 'Loan Moratorium Meaning', href: '/loan-moratorium-meaning' },
{ name: 'How to Settle Credit Card Debt', href: '/how-to-settle-credit-card-debt' },
{ name: 'How to Improve CIBIL Score After Loan Settlement', href: '/how-to-improve-cibil-score-after-loan-settlement' },
{ name: 'HDFC Debt Consolidation Loan', href: '/hdfc-debt-consolidation-loan' },
{ name: 'Expert Panel Loan Settlement', href: '/expert-panel-loan-settlement' },
{ name: 'Debt Settlement Company in India', href: '/debt-settlement-company-in-india' },
{ name: "Can Bank Issue Look Out Notice for Loan Default?", href: "/can-bank-issue-look-out-notice-loan-default" },
{ name: "Bank Loan Settlement Rules", href: "/bank-loan-settlement-rules" },
{ name: "Bank Complaint in RBI", href: "/bank-complaint-in-rbi" },
{ name: 'Legal Notice For Freelance Payment Recovery', href: '/legal-notice-for-freelance-payment-recovery' },
{ name: 'Experience & Relieving Letter Help', href: '/legal-notice-for-experience-letter-and-releiving-letter' },
{ name: 'Illegal Termination Notice', href: '/legal-notice-for-illegal-termination' },
{ name: 'Partnership Dispute Help', href: '/legal-notice-for-partnership-dispute' },
{ name: 'Legal Notice Against NBFC', href: '/legal-notice-against-nbfc' },
{ name: 'Consumer Complaint Finance', href: '/consumer-complaint-against-finance-company' },
{ name: 'OTS Legal Assistance', href: '/one-time-settlement-ots-legal-assistance' },
{ name: 'Loan Defaulter Legal Help', href: '/legal-help-for-loan-defaulters' },
{ name: 'CIBIL Correction Notice', href: '/notice-for-cibil-correction-after-settlement' },
{ name: 'Debt Settlement Drafting', href: '/debt-settlement-agreement-drafting' },
{ name: 'RBI Guideline Violation Help', href: '/rbi-guideline-violation-complaint' },
{ name: 'Credit Card Harassment Help', href: '/legal-notice-for-credit-card-recovery-harassment-dues' },
{ name: 'Asset Recovery Notice', href: '/notice-for-recovery-of-company-assets-from-employee' },
{ name: 'Absenteeism & Negligence Notice', href: '/notice-to-employee-for-absenteeism-negligence' },
{ name: 'Breach of Contract Notice', href: '/notice-to-employee-for-breach-of-employment-contract' },
{ name: 'Employee Misconduct Notice', href: '/notice-to-employee-for-misconduct' },
{ name: 'Workplace Harassment Notice', href: '/notice-to-employer-for-workplace-harassment' },
{ name: 'Non-Payment of Salary Notice', href: '/notice-to-employer-for-non-payment-of-salary-or-benefits' },
{ name: 'Wrongful Termination Notice', href: '/notice-to-employer-for-wrongful-termination' },
{ name: 'Tenant/Landlord Recovery Notice', href: '/notice-for-recovery-from-tenant-landlord' },
{ name: 'Professional Fee Recovery Notice', href: '/notice-for-recovery-of-professional-fees' },
{ name: 'Business Dues Recovery Notice', href: '/notice-for-recovery-of-outstanding-business-dues' },
{ name: 'Security Deposit Recovery Notice', href: '/notice-for-recovery-of-security-deposit' },
{ name: 'Unpaid Salary Recovery Notice', href: '/notice-for-recovery-of-unpaid-salary' },
{ name: 'Dishonoured Cheque Notice', href: '/notice-for-for-dishonoured-cheque' },
{ name: 'Loan Repayment Demand Notice', href: '/demand-notice-for-loan-repayment' },
{ name: 'Recovery of Money Notice', href: '/demand-notice-for-recovery-of-money' },
{ name: 'Lawyer', href: '/lawyer' },
{ name: "Data Breach Privacy Notice", href: "/data-breach-privacy-notice" },
{ name: "Income Tax Demand Notice", href: "/income-tax-demand-notice" },
{ name: "GST Show Cause Notice", href: "/gst-show-cause-notice-scn" },
{ name: "Debt Recovery Notice", href: "/debt-recovery-money-recovery-notice" },
{ name: "IP Cease & Desist Notice", href: "/ip-cease-desist-notice" },
{ name: "Property Eviction Notice", href: "/property-eviction-notice" },
{ name: "Consumer Complaint Notice", href: "/consumer-complaint-notice" },
{ name: "Breach of Contract Notice", href: "/breach-of-contract-notice" },
{ name: "Cheque Bounce Notice", href: "/cheque-bounce-notice" },
{ name: "Compare Debt Management vs Settlement", href: "/compare-different-debt-management-and-settlement-programs-available-to-indian-consumers" },
{ name: "Reputable Debt Relief Agencies Bangalore", href: "/find-reputable-debt-relief-agencies-specializing-in-unsecured-loans-in-bangalore" },
{ name: "Personal Loan Settlement Process", href: "/what-is-the-typical-process-for-settling-a-personal-loan-in-india" },
{ name: "Professional Debt Settlement Companies", href: "/which-companies-offer-professional-debt-settlement-services-for-personal-loans" },
{ name: "Negotiate Personal Loan Settlement", href: "/how-can-I-negotiate-a-personal-loan-settlement-with-lenders" },
{ name: "Best Settlement Services Near Me", href: "/what-are-the-best-loan-settlement-services-near-me" },
{ name: "Zero Balance Account Guide", href: "/zero-balance" },
{ name: "Understanding NPA Guide", href: "/understanding-non-performing-assets-npa-what-happens-next-your-complete-guide" },
{ name: "Top 10 Instant Loan Apps", href: "/top-10-instant-loan-apps-revolutionizing-access-to-credit-in-india" },
{ name: "Check Loan Status Online", href: "/how-to-check-your-loan-status-without-visiting-the-bank" },
{ name: 'What Happens After Loan Settlement', href: '/what-happens-after-loan-settlement' },
{ name: 'Can We Do Home Loan Settlement', href: '/can-we-do-home-loan-settlement' },
{ name: 'Can Debt Settlement Be Removed From Credit Report', href: '/can-debt-settlement-be-removed-from-credit-report' },
{ name: 'Can Loan Repayment Be Done In Cash', href: '/can-loan-repayment-be-done-in-cash' },
{ name: 'Can Debt Settlement Hurt Your Credit', href: '/can-debt-settlement-hurt-your-credit' },
{ name: 'Does Loan Settlement Affect Cibil Score', href: '/does-loan-settlement-affect-cibil-score' },
{ name: "Stop Bajaj Recovery Abuse", href: "/bajaj-recovery-agent-abusing" },
{ name: "Bajaj Contact Hacking Help", href: "/bajaj-recovery-agent-hacked-my-contact-list" },
{ name: "Bajaj Reference Calling Help", href: "/bajaj-recovery-agent-calling-references" },
{ name: 'How To Stop Bajaj Recovery Agent Harassment Instantly', href: '/how-to-stop-bajaj-recovery-agent-harassment-instantly' },
{ name: 'Loan Settlement Services', href: '/loan-settlement-services' },
{ name: 'Will Drafting For Indians Living In Germany', href: '/will-drafting-for-indians-living-in-germany' },
{ name: "Will Drafting for Indians in Dubai", href: "/will-drafting-for-indians-living-in-dubai" },
{ name: "Will Drafting for Indians in Australia", href: "/will-drafting-for-indians-living-in-australia" },
{ name: "Will Drafting for Indians in USA", href: "/will-drafting-for-indians-living-in-usa" },
{ name: "Will Drafting for Indians in Canada", href: "/will-drafting-for-indians-living-in-canada" },
{ name: 'Loan Settlement By Bank', href: '/loan-settlement-by-bank' },
{ name: 'Lawyer By Expertise', href: '/lawyer-by-expertise' },
{ name: 'Lawyer By City', href: '/lawyer-by-city' },
{ name: "Recovery Notice Reply Format", href: "/reply-to-recovery-notice-format" },
{ name: "When to Choose Settlement", href: "/when-to-choose-loan-settlement" },
{ name: "Legal Rights After Default", href: "/legal-rights-after-loan-default" },
{ name: "How to Challenge Bank Statement?", href: "/how-to-challenge-bank-statement-account-statement" },
{ name: "What Happens After Bank Issues Recall Notice?", href: "/what-happens-after-bank-issues-recall-notice" },
{ name: "Settlement vs Repayment", href: "/loan-settlement-vs-repayment" },
{ name: "NPA Loan Settlement", href: "/loan-settlement-after-npa-classification" },
{ name: "Settlement Before Auction", href: "/loan-settlement-before-auction" },
{ name: "Can Guarantor Be Liable After Settlement?", href: "/can-guarantor-be-liable-after-settlement" },
{ name: "Can Settlement Be Done in Installments?", href: "/can-settlement-be-done-in-installments" },
{ name: "Can Bank Reject Settlement?", href: "/can-bank-reject-settlement-request" },
{ name: "40L Debt Resolution Plan", href: "/40L-unsecured-debt-in-india-what-to-do-self-vs-debt-settlement-program" },
{ name: "Settle Now and Remove Later?", href: "/can-I-go-for-settlement-of-loan-now-and-remove-it-later-when-im-financially-stable" },
{ name: "Is Settlement Letter Valid?", href: "/how-to-know-if-the-settlement-letter-is-valid" },
{ name: "How to Identify Fake Settlement Letter", href: "/how-to-identify-fake-settlement-letter" },
{ name: "Understanding 90 Day Default", href: "/understanding-90-day-loan-default-india" },
{ name: "Do Banks File FIR for Credit Card Dues", href: "/do-banks-file-fir-for-credit-card-dues" },
{ name: "Is Loan Settlement Illegal in India Truth", href: "/is-loan-settlement-illegal-in-india-truth" },
{ name: "Can Recovery Agents Abuse You Legally India", href: "/can-recovery-agents-abuse-you-legally-india" },
{ name: "Is CIBIL Ruined Forever?", href: "/is-cibil-ruined-forever-after-settlement" },
{ name: 'MAS Financial Settlement', href: '/services/loan-settlement/mas-financial' },
{ name: 'Services - Loan Settlement - Newtap', href: '/services/loan-settlement/newtap' },
{ name: 'Services - Loan Settlement - Ndx P2P', href: '/services/loan-settlement/ndx-p2p' },
{ name: 'Services - Loan Settlement - Infocredit', href: '/services/loan-settlement/infocredit' },
{ name: 'Services - Loan Settlement - Zype', href: '/services/loan-settlement/zype' },
{ name: 'Services - Loan Settlement - Citibank', href: '/services/loan-settlement/citibank' },
{ name: 'Services - Loan Settlement - Prefr', href: '/services/loan-settlement/prefr' },
{ name: "Why Credit Score Drops Even When Paying On Time", href: "/why-does-my-credit-score-drop-even-though-i-pay-on-time" },
{ name: "How to Check Active Loan on Your Name", href: "/how-to-check-active-loan-on-your-name-in-india-step-by-step-guide" },
{ name: "Financial Reset Settlement", href: "/loan-settlement-for-borrowers-planning-financial-reset" },
{ name: "Debt Free Future Plan", href: "/amalegalsolutions-plan-for-building-debt-free-future-after-settlement" },
{ name: "Economic Downturn Settlement", href: "/loan-settlement-for-borrowers-facing-economic-downturn" },
{ name: "LPG Crisis India 2026", href: "/lpg-cylinder-crisis-india-2026-iran-war" },
{ name: "2026 Resource Lockdown", href: "/2026-lockdown-due-to-scarcity-of-resources" },
{ name: "P2P Crypto Scam Unfreeze", href: "/p2p-crypto-scam-unfreeze-bank-account" },
{ name: "Harassment Protection", href: "/legal-notice-for-loan-settlement-harassment" },
{ name: "Legal Notice for Harassment", href: "/legal-notice-for-loan-settlement-harassment" },
{ name: "Home Loan Eligibility After Settlement", href: "/home-loan-eligibility-after-settlement" },
{ name: "Loan Settlement & NOC Formats", href: "/loan-settlement-letter-format-noc-format" },
{ name: "Stop Bank Harassment", href: "/services/best-lawyer-for-bank-harassment" },
{ name: 'Services - Loan Settlement - Daman Diu', href: '/services/loan-settlement/daman-diu' },
{ name: 'Services - Loan Settlement - Chandigarh', href: '/services/loan-settlement/chandigarh' },
{ name: 'Services - Loan Settlement - Andaman Nicobar', href: '/services/loan-settlement/andaman-nicobar' },
{ name: "How to Get 800 Credit Score in India", href: "/how-to-get-800-credit-score-in-india" },
{ name: 'Support For Loan Settlement During Medical Emergencies', href: '/support-for-loan-settlement-during-medical-emergencies' },
{ name: "Trademark Class 38", href: "/trademark-registration-in-class-38" },
{ name: "Trademark Class 45", href: "/trademark-registration-in-class-45" },
{ name: "Trademark Class 14", href: "/trademark-registration-in-class-14" },
{ name: "Trademark Class 35", href: "/trademark-registration-in-class-35" },
{ name: "Can I Convert Settled To Closed Later", href: "/can-i-convert-settled-to-closed-later" },
{ name: "Does Settlement Impact a Co-borrower", href: "/does-settlement-impact-a-co-borrower" },
{ name: "Can I Settle My Loan Without A Lawyer?", href: "/can-i-settle-my-loan-without-a-lawyer" },
{ name: "Loan Settlement Process in Hindi", href: "/loan-settlement-process-in-hindi" },
{ name: "Is Loan Settlement in Installments Possible", href: "/is-loan-settlement-in-installments-possible" },
{ name: "Which one is REAL AMA?", href: "/which-one-is-the-real-amalegalsolutions" },
{ name: 'Debt Resolution Companies India', href: '/get-contact-details-for-top-rated-debt-resolution-companies-in-india' },
{ name: "CFP specialized in Debt Restructuring", href: "/certified-financial-planners-who-specialize-in-debt-restructuring-and-settlement" },
{ name: "Settle Credit Card Using Third Party", href: "/can-i-settle-my-credit-card-dues-using-third-party-loan-settlement-companies" },
{ name: 'Third Party Credit Card Settlement', href: '/can-i-settle-my-credit-card-dues-using-third-party-loan-settlement-companies' },
{ name: "Credit Counseling Chennai", href: "/where-can-i-locate-government-approved-consumer-credit-counseling-services-in-chennai" },
{ name: "Tax Implications of Settled Debt", href: "/what-are-the-income-tax-implications-of-a-settled-debt-amount" },
{ name: 'Effective Negotiation Services', href: '/find-debt-settlement-services-known-for-effective-negotiation' },
{ name: 'Check Genuine Settlement Offer', href: '/how-to-check-if-a-loan-settlement-offer-is-genuine-on-digital-platforms' },
{ name: 'Initiate Settlement Discussion', href: '/how-can-i-initiate-a-full-and-final-settlement-discussion-with-bank' },
{ name: 'Reputable Debt Relief Agencies Specializing In Unsecured Loans In Banglore', href: '/reputable-debt-relief-agencies-specializing-in-unsecured-loans-in-banglore' },
{ name: 'Benefits & Drawbacks of Settlement', href: '/key-benefits-and-drawbacks-of-persuing-loan-settlement' },
{ name: 'Steps to Apply for Settlement', href: '/steps-to-apply-for-a-loan-settlement-through-a-financial-service-provider' },
{ name: "Best Law Firms in India for Corporate Law", href: "/best-law-firms-in-india-for-corporate-law" },
{ name: 'Best Corporate Law Firms', href: '/best-law-firms-in-india-for-corporate-law' },
{ name: 'Trading Loan Settlement', href: '/trading-loan-settlement' },
{ name: "Workplace Harassment Notice", href: "/workplace-harassment-legal-notice-service" },
{ name: "Overcharged at Hospital - Legal Notice", href: "/overcharged-at-hospital-send-legal-notice" },
{ name: "Hospital Harassment Protection", href: "/protection-from-hospital-harrassement" },
{ name: "Legal Notice to Hospital", href: "/legal-notice-to-hospital" },
{ name: 'Secured Loan Settlement', href: '/secured-loan-settlement' },
{ name: 'Unsecured Loan Settlement', href: '/unsecured-loan-settlement' },
{ name: 'Got An Arbitration Notice Dont Worry We Got You', href: '/got-an-arbitration-notice-dont-worry-we-got-you' },
{ name: 'Get Your Trademark In 180 Days', href: '/get-your-trademark-in-180-days' },
{ name: 'Expedited Process For Trademark Registration', href: '/expedited-process-for-trademark-registration' },
{ name: 'App Loan Settlement', href: '/app-loan-settlement' },
{ name: 'Car Loan Settlement', href: '/car-loan-settlement' },
{ name: 'Business Loan Settlement', href: '/business-loan-settlement' },
{ name: 'Credit Card Settlement', href: '/credit-card-settlement' },
{ name: 'Personal Loan Settlement', href: '/personal-loan-settlement' },
{ name: 'Reasonable Settlement Offer', href: '/what-is-a-reasonable-settlement-offer' },
{ name: 'Ama Legal Solutions Application', href: '/ama-legal-solutions-application' },
{ name: "Google's Trusted Law Firm", href: "/googles-trusted-law-firm" },
{ name: "Google's Trusted Legal Advisor", href: "/googles-trusted-legal-advisor" },
{ name: "Will Drafting for NRI", href: "/will-drafting-for-nri" },
{ name: "Simple Will Format - Download", href: "/simple-will-format-download-free-legal-document-sample" },
{ name: "Drafting of Will", href: "/drafting-of-will" },
{ name: "RBI Recovery Guidelines July 2026", href: "/rbi-new-recovery-guidelines-july-2026" },
{ name: "Telecaller Vacancies in Gurgaon", href: "/telecaller-vacancies-in-gurgaon" },
{ name: "Sales Job Vacancies in Gurgaon", href: "/sales-job-vacancies-in-gurgaon" },
{ name: 'How To Register Fssai Licence', href: '/how-to-register-fssai-licence' },
{ name: 'Get Fssai Licence In 7 Days', href: '/get-fssai-licence-in-7-days' },
{ name: "Credit Card Settlement Process India", href: "/credit-card-settlement-process-india" },
{ name: "Can Bank File Case for Personal Loan", href: "/can-bank-file-case-for-personal-loan" },
{ name: "Benefits of Settling Your Loan in March", href: "/benefits-of-settling-your-loan-in-march" },
{ name: "Best Time for Loan Settlement", href: "/best-time-for-loan-settlement" },
{ name: 'Charities That Pay Off Debt', href: '/charities-that-pay-off-debt' },
{ name: 'Top Settlement Companies', href: '/loan-settlement-companies' },
{ name: 'Documents Needed for Loan Settlement NOC', href: '/documents-needed-for-loan-settlement-noc' },
{ name: 'Settled Tag Duration', href: '/how-long-does-a-settled-tag-stay-on-my-report' },
{ name: 'How to Settle with Bank', href: '/how-to-settle-loan-with-bank' },
{ name: 'Settlement Calculator', href: '/loan-settlement-amount-calculator' },
{ name: 'Loan Settlement Near Me', href: '/loan-settlement-near-me' },
{ name: '10 Lakhs Settlement', href: '/10-lakhs-loan-settlement' },
{ name: "How to Settle Loans Above 5 Cr", href: "/how-to-settle-loans-above-5-crore" },
{ name: "How to Settle Loans Above 1 Cr", href: "/how-to-settle-loans-above-1-crore" },
{ name: 'Virtual Inhouse Councel', href: '/virtual-inhouse-councel' },
{ name: "Bajaj Finance Agent Help", href: "/bajaj-finance-agent-visiting-home" },
{ name: "Stop Recovery Agent Home Visits", href: "/how-do-i-stop-recovery-agent-from-coming-home" },
{ name: "Expert Panel Reviews", href: "/expert-panel-loan-settlement-reviews" },
{ name: "Legal Relief from Harassment", href: "/loan-recovery-agents-harassment-complaint" },
{ name: "Stop Recovery Harassment", href: "/loan-recovery-agent-harassment-complaint-online" },
{ name: "Loan for CIBIL Defaulters", href: "/which-bank-provide-personal-loan-for-cibil-defaulters" },
{ name: "Does Foreclosure of Loan Affect CIBIL?", href: "/does-foreclosure-of-loan-affect-cibil" },
{ name: 'Services - Loan And Debt Consolidation', href: '/services/loan-and-debt-consolidation' },
{ name: 'Home Loan Dues', href: '/can-i-get-a-loan-settlement-service-that-handles-home-loan-dues' },
{ name: 'Good Customer Support', href: '/what-loan-settlement-services-have-good-customer-support-in-india' },
{ name: 'Unsecured Loan Specialists', href: '/which-firms-specialize-in-negotiating-settlements-for-unsecured-loans' },
{ name: 'Low Fee Settlement', href: '/who-provides-loan-settlement-solutions-with-minimal-processing-fees' },
{ name: 'Reliable Settlement', href: '/where-can-i-find-reliable-loan-settlement-services-with-flexible-payment-options' },
{ name: 'Best Settlement Companies', href: '/which-companies-offer-the-best-loan-settlement-plans-for-personal-loans' },
{ name: 'Reduce Debt Quickly', href: '/what-loan-settlement-service-can-help-me-reduce-my-outstanding-debt-quickly' },
{ name: 'Careers - Business Development Associate', href: '/careers/business-development-associate' },
  { name: 'Careers - Software Development Engineer Intern', href: '/careers/software-development-engineer-intern' },
{ name: 'Careers - Legal Associate', href: '/careers/legal-associate' },
{ name: 'Careers', href: '/careers' },
{ name: 'Free Loan Settlement Guide', href: '/free-loan-settlement-guide' },
{ name: 'Legal Services In Ghaziabad', href: '/legal-services-in-ghaziabad' },
{ name: 'Legal Services In Delhi', href: '/legal-services-in-delhi' },
{ name: 'Legal Services In Noida', href: '/legal-services-in-noida' },
{ name: 'Legal Services In Gurgaon', href: '/legal-services-in-gurgaon' },
{ name: 'Ama Legal Solutions', href: '/ama-legal-solutions' },
{ name: "Where to File Salary Complaint", href: "/where-to-file-a-complaint-if-your-employer-doesnt-pay-you" },
{ name: "Can Company Hold Salary?", href: "/can-company-hold-my-salary-after-resignation" },
{ name: "Employer not paying salary", href: "/employer-not-paying-salary-after-resignation" },
{ name: "Procedure of Sending Legal Notice", href: "/procedure-of-sending-legal-notice" },
{ name: "Compare Loan Settlement Companies", href: "/compare-loan-settlement-companies-that-work-with-personal-loans" },
{ name: "What is OTS? - Comprehensive Guide", href: "/what-is-ots" },
{ name: "Is Trademark Registration One Time?", href: "/is-trademark-registration-one-time" },
{ name: "Trademark Registration Office Delhi", href: "/trademark-registration-office-delhi" },
{ name: "Special Lok Adalat for Challan", href: "/special-lok-adalat-for-challan" },
{ name: "Special Lok Adalat for Loan Settlement", href: "/special-lok-adalat-for-loan-settlement" },
{ name: "Legal Notice for Unpaid F&F", href: "/not-being-paid-fnf-want-to-send-legal-notice" },
{ name: "Is Trademark Internationally Valid", href: "/is-trademark-internationally-valid" },
{ name: "Name vs Logo Trademark", href: "/is-registering-a-name-instead-of-the-logo-enough" },
{ name: "Trademark Infringement Without Registration", href: "/trademark-infringement-without-registration" },
{ name: "Is Trademark Mandatory for Amazon", href: "/is-trademark-registration-mandatory-to-sell-on-amazon" },
{ name: "Trademark Opposition Procedure", href: "/trademark-opposition-procedure" },
{ name: "Trademark Agency Near Me", href: "/trademark-registration-agency-near-me" },
{ name: "Steps to Trademark Registration", href: "/steps-to-trademark-registration" },
{ name: 'Best Apps For Managing Loan Settlement Offers In India', href: '/best-apps-for-managing-loan-settlement-offers-in-India' },
{ name: "How to Negotiate Loan Settlement", href: "/how-to-negotiate-a-loan-settlement-with-lenders-online" },
{ name: "Top Loan Settlement Services", href: "/top-loan-settlement-services-with-good-customer-reviews" },
{ name: "Job Lost Loan Settlement", href: "/job-lost-loan-settlement" },
{ name: "Delhi NCR Law Firm", href: "/delhi-ncr-law-firm" },
{ name: "Legal Services Near Me", href: "/legal-services-near-me" },
{ name: "Best Law Firm Near Me", href: "/best-law-firm-near-me" },
{ name: "Best Advocate Near Me", href: "/best-advocate-near-me" },
{ name: 'How Much Time It Takes To Get Your Trademark Registered', href: '/how-much-time-it-takes-to-get-your-trademark-registered' },
{ name: "Registration Office Locations", href: "/where-to-register-trademark" },
{ name: 'Validity Of Trademark Registration', href: '/validity-of-trademark-registration' },
{ name: "How to Get Trademark Certificate", href: "/how-can-i-get-trademark-certificate" },
{ name: 'Can I Sell My Products Without Trademark', href: '/can-i-sell-my-products-without-trademark' },
{ name: 'Trademark Objection Reply Procedure', href: '/trademark-objection-reply-procedure' },
{ name: 'Which Is Better Tm Or R', href: '/which-is-better-tm-or-r' },
{ name: 'Is Gst Required For Trademarks', href: '/is-gst-required-for-trademarks' },
{ name: 'What Documents Are Required For Trademark Registration', href: '/what-documents-are-required-for-trademark-registration' },
{ name: 'Can I Register My Trademark By Myself', href: '/can-i-register-my-trademark-by-myself' },
{ name: 'Trademark Registration Fees', href: '/trademark-registration-fees' },
{ name: 'Msme Registration', href: '/msme-registration' },
{ name: 'Services - Trademark Status', href: '/services/trademark-status' },
{ name: 'Services - Trademark Search', href: '/services/trademark-search' },
{ name: 'Services - Comprehensive Guide Trademark Registration India', href: '/services/comprehensive-guide-trademark-registration-india' },
{ name: 'How Can I Send Legal Notice', href: '/how-can-i-send-legal-notice' },
{ name: 'Send Legal Notice In Punjab', href: '/send-legal-notice-in-punjab' },
{ name: 'Send Legal Notice In Uttar Pradesh', href: '/send-legal-notice-in-uttar-pradesh' },
{ name: 'Send Legal Notice Haryana', href: '/send-legal-notice-haryana' },
{ name: 'Send Legal Notice', href: '/send-legal-notice' },
{ name: 'Send Legal Notice In Noida', href: '/send-legal-notice-in-noida' },
{ name: 'Send Legal Notice In Gurugram', href: '/send-legal-notice-in-gurugram' },
{ name: 'Send Legal Notice In Delhi', href: '/send-legal-notice-in-delhi' },
{ name: 'Services - Loan Settlement - Hyderabad', href: '/services/loan-settlement/hyderabad' },
{ name: 'Services - Loan Settlement - Karnataka', href: '/services/loan-settlement/karnataka' },
{ name: 'Services - Loan Settlement - Lakshadweep', href: '/services/loan-settlement/lakshadweep' },
{ name: 'Services - Loan Settlement - Ladakh', href: '/services/loan-settlement/ladakh' },
{ name: 'Services - Loan Settlement - Jammu And Kashmir', href: '/services/loan-settlement/jammu-and-kashmir' },
{ name: 'Ask Me Anything', href: '/ask-me-anything' },
{ name: 'Locations - Mizoram', href: '/locations/mizoram' },
{ name: 'Locations - Kerala', href: '/locations/kerala' },
{ name: 'Locations - Tamil Nadu', href: '/locations/tamil-nadu' },
{ name: 'Locations - Chandigarh', href: '/locations/chandigarh' },
{ name: 'Locations - Rajasthan', href: '/locations/rajasthan' },
{ name: 'Locations - Punjab', href: '/locations/punjab' },
{ name: 'Locations - Haryana', href: '/locations/haryana' },
{ name: 'Locations - Uttarakhand', href: '/locations/uttarakhand' },
{ name: 'Locations - Uttar Pradesh', href: '/locations/uttar-pradesh' },
{ name: 'Locations - Telangana', href: '/locations/telangana' },
{ name: 'Services - Quick Company Registration And Trademark', href: '/services/quick-company-registration-and-trademark' },
{ name: 'Services - Expert Vakil Search For Trademark Registration', href: '/services/expert-vakil-search-for-trademark-registration' },
{ name: 'Services - How To Register Trademark With Ipindia', href: '/services/how-to-register-trademark-with-ipindia' },
{ name: 'Services - Trademark Registration', href: '/services/trademark-registration' },
{ name: 'Success Stories', href: '/success-stories' },
{ name: 'Services - Loan Settlement - Vivriti Capital', href: '/services/loan-settlement/vivriti-capital' },
{ name: 'Services - Loan Settlement - Moneyview', href: '/services/loan-settlement/moneyview' },
{ name: 'Services - Loan Settlement - True Credits', href: '/services/loan-settlement/true-credits' },
{ name: 'Services - Loan Settlement - Standard Chartered', href: '/services/loan-settlement/standard-chartered' },
{ name: 'Services - Loan Settlement - American Express', href: '/services/loan-settlement/american-express' },
{ name: 'Services - Loan Settlement - L And T Finance', href: '/services/loan-settlement/l-and-t-finance' },
{ name: 'Services - Loan Settlement - Stashfin', href: '/services/loan-settlement/stashfin' },
{ name: 'Services - Loan Settlement - Si Creva', href: '/services/loan-settlement/si-creva' },
{ name: 'Services - Loan Settlement - South Indian Bank', href: '/services/loan-settlement/south-indian-bank' },
{ name: 'Services - Loan Settlement - Dbs Bank', href: '/services/loan-settlement/dbs-bank' },
{ name: 'Services - Loan Settlement - Piramal Finance', href: '/services/loan-settlement/piramal-finance' },
{ name: 'Services - Loan Settlement - Dmi Finance', href: '/services/loan-settlement/dmi-finance' },
{ name: 'Services - Loan Settlement - Northern Arc', href: '/services/loan-settlement/northern-arc' },
{ name: 'Services - Loan Settlement - Au Small Finance', href: '/services/loan-settlement/au-small-finance' },
{ name: 'Services - Loan Settlement - Krazybee', href: '/services/loan-settlement/krazybee' },
{ name: 'Services - Loan Settlement - Payu Finance', href: '/services/loan-settlement/payu-finance' },
{ name: 'Services - Loan Settlement - Federal Bank', href: '/services/loan-settlement/federal-bank' },
{ name: 'Services - Loan Settlement - Tata Capital', href: '/services/loan-settlement/tata-capital' },
{ name: 'Services - Loan Settlement - Poonawalla Fincorp', href: '/services/loan-settlement/poonawalla-fincorp' },
{ name: 'Services - Loan Settlement - Aditya Birla', href: '/services/loan-settlement/aditya-birla' },
{ name: 'Services - Loan Settlement - Hero Fincorp', href: '/services/loan-settlement/hero-fincorp' },
{ name: 'Services - Loan Settlement - Bank Of Baroda', href: '/services/loan-settlement/bank-of-baroda' },
{ name: 'Services - Loan Settlement - Smfg India Credit', href: '/services/loan-settlement/smfg-india-credit' },
{ name: 'Services - Loan Settlement - Indusind Bank', href: '/services/loan-settlement/indusind-bank' },
{ name: 'Services - Loan Settlement - Kisetsu Saison Finance', href: '/services/loan-settlement/kisetsu-saison-finance' },
{ name: 'Axis Bank Settlement', href: '/services/loan-settlement/axis-bank' },
{ name: 'Services - Loan Settlement - Bajaj Finserv', href: '/services/loan-settlement/bajaj-finserv' },
{ name: 'Services - Debt Consolidation', href: '/services/debt-consolidation' },
{ name: 'Services - Litigation - Rajasthan', href: '/services/litigation/rajasthan' },
{ name: 'Services - Litigation - Punjab', href: '/services/litigation/punjab' },
{ name: 'Services - Litigation - Uttarakhand', href: '/services/litigation/uttarakhand' },
{ name: 'Services - Litigation - Uttar Pradesh', href: '/services/litigation/uttar-pradesh' },
{ name: 'Services - Litigation - Tamil Nadu', href: '/services/litigation/tamil-nadu' },
{ name: 'Services - Litigation - West Bengal', href: '/services/litigation/west-bengal' },
{ name: 'Services - Litigation - Telangana', href: '/services/litigation/telangana' },
{ name: 'Services - Litigation - Delhi', href: '/services/litigation/delhi' },
{ name: 'Services - Litigation - Maharashtra', href: '/services/litigation/maharashtra' },
{ name: 'Services - Loan Settlement - What Is Loan Settlement', href: '/services/loan-settlement/what-is-loan-settlement' },
{ name: 'Services - Loan Settlement - Lok Adalat', href: '/services/loan-settlement/lok-adalat' },
{ name: 'Services - Loan Settlement - Surat', href: '/services/loan-settlement/surat' },
{ name: 'Services - Loan Settlement - Jaipur', href: '/services/loan-settlement/jaipur' },
{ name: 'Services - Loan Settlement - Kanpur', href: '/services/loan-settlement/kanpur' },
{ name: 'Services - Loan Settlement - Ghaziabad', href: '/services/loan-settlement/ghaziabad' },
{ name: 'Services - Loan Settlement - Gurugram', href: '/services/loan-settlement/gurugram' },
{ name: 'Services - Loan Settlement - Noida', href: '/services/loan-settlement/noida' },
{ name: 'Services - Loan Settlement - Pune', href: '/services/loan-settlement/pune' },
{ name: 'Services - Loan Settlement - Mumbai', href: '/services/loan-settlement/mumbai' },
{ name: 'Services - Banking And Finance - Sikkim', href: '/services/banking-and-finance/sikkim' },
{ name: 'Services - Banking And Finance - Chhattisgarh', href: '/services/banking-and-finance/chhattisgarh' },
{ name: 'Services - Banking And Finance - Karnataka', href: '/services/banking-and-finance/karnataka' },
{ name: 'Services - Banking And Finance - Goa', href: '/services/banking-and-finance/goa' },
{ name: 'Services - Banking And Finance - Himachal Pradesh', href: '/services/banking-and-finance/himachal-pradesh' },
{ name: 'Services - Banking And Finance - Mizoram', href: '/services/banking-and-finance/mizoram' },
{ name: 'Services - Banking And Finance - Tripura', href: '/services/banking-and-finance/tripura' },
{ name: 'Services - Banking And Finance - Meghalaya', href: '/services/banking-and-finance/meghalaya' },
{ name: 'Services - Banking And Finance - Nagaland', href: '/services/banking-and-finance/nagaland' },
{ name: 'Services - Banking And Finance - Jammu And Kashmir', href: '/services/banking-and-finance/jammu-and-kashmir' },
{ name: 'Services - Banking And Finance - Ladakh', href: '/services/banking-and-finance/ladakh' },
{ name: 'Services - Banking And Finance - Puducherry', href: '/services/banking-and-finance/puducherry' },
{ name: 'Services - Banking And Finance - Assam', href: '/services/banking-and-finance/assam' },
{ name: 'Services - Banking And Finance - Kerala', href: '/services/banking-and-finance/kerala' },
{ name: 'Services - Banking And Finance - Tamil Nadu', href: '/services/banking-and-finance/tamil-nadu' },
{ name: 'Services - Banking And Finance - Gujarat', href: '/services/banking-and-finance/gujarat' },
{ name: 'Services - Banking And Finance - Haryana', href: '/services/banking-and-finance/haryana' },
{ name: 'Services - Banking And Finance - Arunachal Pradesh', href: '/services/banking-and-finance/arunachal-pradesh' },
{ name: 'Services - Banking And Finance - Jharkhand', href: '/services/banking-and-finance/jharkhand' },
{ name: 'Services - Banking And Finance - Bihar', href: '/services/banking-and-finance/bihar' },
{ name: 'Services - Banking And Finance - Manipur', href: '/services/banking-and-finance/manipur' },
{ name: 'Services - Banking And Finance - Odisha', href: '/services/banking-and-finance/odisha' },
{ name: 'Services - Banking And Finance - Uttarakhand', href: '/services/banking-and-finance/uttarakhand' },
{ name: 'Services - Banking And Finance - Uttar Pradesh', href: '/services/banking-and-finance/uttar-pradesh' },
{ name: 'Services - Banking And Finance - Punjab', href: '/services/banking-and-finance/punjab' },
{ name: 'Services - Banking And Finance - Rajasthan', href: '/services/banking-and-finance/rajasthan' },
{ name: 'Services - Banking And Finance - Madhya Pradesh', href: '/services/banking-and-finance/madhya-pradesh' },
{ name: 'Services - Banking And Finance - Andhra Pradesh', href: '/services/banking-and-finance/andhra-pradesh' },
{ name: 'Services - Banking And Finance - Chandigarh', href: '/services/banking-and-finance/chandigarh' },
{ name: 'Services - Banking And Finance - West Bengal', href: '/services/banking-and-finance/west-bengal' },
{ name: 'Services - Banking And Finance - Telangana', href: '/services/banking-and-finance/telangana' },
{ name: 'Services - Banking And Finance - Delhi', href: '/services/banking-and-finance/delhi' },
{ name: 'Services - Banking And Finance - Maharashtra', href: '/services/banking-and-finance/maharashtra' },
{ name: 'Services - Intellectual Property Rights - Mizoram', href: '/services/intellectual-property-rights/mizoram' },
{ name: 'Services - Intellectual Property Rights - Chhattisgarh', href: '/services/intellectual-property-rights/chhattisgarh' },
{ name: 'Services - Intellectual Property Rights - Jammu And Kashmir', href: '/services/intellectual-property-rights/jammu-and-kashmir' },
{ name: 'Services - Intellectual Property Rights - Tripura', href: '/services/intellectual-property-rights/tripura' },
{ name: 'Services - Intellectual Property Rights - Arunachal Pradesh', href: '/services/intellectual-property-rights/arunachal-pradesh' },
{ name: 'Services - Intellectual Property Rights - Andhra Pradesh', href: '/services/intellectual-property-rights/andhra-pradesh' },
{ name: 'Services - Intellectual Property Rights - Puducherry', href: '/services/intellectual-property-rights/puducherry' },
{ name: 'Services - Intellectual Property Rights - Manipur', href: '/services/intellectual-property-rights/manipur' },
{ name: 'Services - Intellectual Property Rights - Jharkhand', href: '/services/intellectual-property-rights/jharkhand' },
{ name: 'Services - Intellectual Property Rights - Madhya Pradesh', href: '/services/intellectual-property-rights/madhya-pradesh' },
{ name: 'Services - Intellectual Property Rights - Chandigarh', href: '/services/intellectual-property-rights/chandigarh' },
{ name: 'Services - Intellectual Property Rights - Bihar', href: '/services/intellectual-property-rights/bihar' },
{ name: 'Services - Intellectual Property Rights - West Bengal', href: '/services/intellectual-property-rights/west-bengal' },
{ name: 'Services - Intellectual Property Rights - Uttarakhand', href: '/services/intellectual-property-rights/uttarakhand' },
{ name: 'Services - Intellectual Property Rights - Telangana', href: '/services/intellectual-property-rights/telangana' },
{ name: 'Services - Intellectual Property Rights - Kerala', href: '/services/intellectual-property-rights/kerala' },
{ name: 'Services - Intellectual Property Rights - Odisha', href: '/services/intellectual-property-rights/odisha' },
{ name: 'Services - Intellectual Property Rights - Assam', href: '/services/intellectual-property-rights/assam' },
{ name: 'Services - Intellectual Property Rights - Punjab', href: '/services/intellectual-property-rights/punjab' },
{ name: 'Services - Intellectual Property Rights - Uttar Pradesh', href: '/services/intellectual-property-rights/uttar-pradesh' },
{ name: 'Services - Intellectual Property Rights - Gujarat', href: '/services/intellectual-property-rights/gujarat' },
{ name: 'Services - Intellectual Property Rights - Rajasthan', href: '/services/intellectual-property-rights/rajasthan' },
{ name: 'Services - Intellectual Property Rights - Tamil Nadu', href: '/services/intellectual-property-rights/tamil-nadu' },
{ name: 'Services - Intellectual Property Rights - Delhi', href: '/services/intellectual-property-rights/delhi' },
{ name: 'Services - Intellectual Property Rights - Maharashtra', href: '/services/intellectual-property-rights/maharashtra' },
{ name: 'Services - Loan Settlement - Pnb Bank', href: '/services/loan-settlement/pnb-bank' },
{ name: 'Services - Loan Settlement - Navi', href: '/services/loan-settlement/navi' },
{ name: 'Services - Loan Settlement - Paytm', href: '/services/loan-settlement/paytm' },
{ name: 'Services - Loan Settlement - Cred', href: '/services/loan-settlement/cred' },
{ name: 'Services - Loan Settlement - Fibe', href: '/services/loan-settlement/fibe' },
{ name: 'Services - Loan Settlement - Hsbc', href: '/services/loan-settlement/hsbc' },
{ name: 'Services - Loan Settlement - Rbl Bank', href: '/services/loan-settlement/rbl-bank' },
{ name: 'Services - Loan Settlement - Yes Bank', href: '/services/loan-settlement/yes-bank' },
{ name: 'Services - Loan Settlement - Sbi Bank', href: '/services/loan-settlement/sbi-bank' },
{ name: 'Kotak Mahindra Settlement', href: '/services/loan-settlement/kotak-mahindra' },
{ name: 'Services - Loan Settlement - Idfc Bank', href: '/services/loan-settlement/idfc-bank' },
{ name: 'ICICI Bank Settlement', href: '/services/loan-settlement/icici-bank' },
{ name: 'HDFC Bank Settlement', href: '/services/loan-settlement/hdfc-bank' },
{ name: 'Services - Loan Settlement - Puducherry', href: '/services/loan-settlement/puducherry' },
{ name: 'Services - Loan Settlement - Manipur', href: '/services/loan-settlement/manipur' },
{ name: 'Services - Loan Settlement - Meghalaya', href: '/services/loan-settlement/meghalaya' },
{ name: 'Services - Loan Settlement - Mizoram', href: '/services/loan-settlement/mizoram' },
{ name: 'Services - Loan Settlement - Uttarakhand', href: '/services/loan-settlement/uttarakhand' },
{ name: 'Services - Loan Settlement - Tripura', href: '/services/loan-settlement/tripura' },
{ name: 'Services - Loan Settlement - Sikkim', href: '/services/loan-settlement/sikkim' },
{ name: 'Services - Loan Settlement - Himachal Pradesh', href: '/services/loan-settlement/himachal-pradesh' },
{ name: 'Services - Loan Settlement - Assam', href: '/services/loan-settlement/assam' },
{ name: 'Services - Loan Settlement - Chhattisgarh', href: '/services/loan-settlement/chhattisgarh' },
{ name: 'Services - Loan Settlement - Odisha', href: '/services/loan-settlement/odisha' },
{ name: 'Services - Loan Settlement - Jharkhand', href: '/services/loan-settlement/jharkhand' },
{ name: 'Services - Loan Settlement - Goa', href: '/services/loan-settlement/goa' },
{ name: 'Services - Loan Settlement - Gujarat', href: '/services/loan-settlement/gujarat' },
{ name: 'Services - Loan Settlement - Arunachal Pradesh', href: '/services/loan-settlement/arunachal-pradesh' },
{ name: 'Services - Loan Settlement - Kerala', href: '/services/loan-settlement/kerala' },
{ name: 'Services - Loan Settlement - Tamil Nadu', href: '/services/loan-settlement/tamil-nadu' },
{ name: 'Services - Loan Settlement - Madhya Pradesh', href: '/services/loan-settlement/madhya-pradesh' },
{ name: 'Services - Loan Settlement - Bihar', href: '/services/loan-settlement/bihar' },
{ name: 'Services - Loan Settlement - Rajasthan', href: '/services/loan-settlement/rajasthan' },
{ name: 'Services - Loan Settlement - Punjab', href: '/services/loan-settlement/punjab' },
{ name: 'Services - Loan Settlement - Haryana', href: '/services/loan-settlement/haryana' },
{ name: 'Services - Loan Settlement - West Bengal', href: '/services/loan-settlement/west-bengal' },
{ name: 'Services - Loan Settlement - Andhra Pradesh', href: '/services/loan-settlement/andhra-pradesh' },
{ name: 'Services - Loan Settlement - Telangana', href: '/services/loan-settlement/telangana' },
{ name: 'Services - Loan Settlement - Uttar Pradesh', href: '/services/loan-settlement/uttar-pradesh' },
{ name: 'Services - Loan Settlement - Delhi', href: '/services/loan-settlement/delhi' },
{ name: 'Services - Loan Settlement - Maharashtra', href: '/services/loan-settlement/maharashtra' },
{ name: 'Author - Shrey Arora', href: '/author/shrey-arora' },
{ name: 'Author - Anuj Anand Malik', href: '/author/anuj-anand-malik' },
{ name: 'Terms And Conditions', href: '/terms-and-conditions' },
{ name: 'Privacy Policy', href: '/privacy-policy' },
{ name: 'Ourvision', href: '/ourvision' },
{ name: 'Present', href: '/present' },
{ name: 'Ourhistory', href: '/ourhistory' },
{ name: 'Services - Litigation', href: '/services/litigation' },
{ name: 'Services - Drafting', href: '/services/drafting' },
{ name: 'Services - Civil', href: '/services/civil' },
{ name: 'Services - Cyber', href: '/services/cyber' },
{ name: 'Services - Arbitration', href: '/services/arbitration' },
{ name: 'Services - Corporate', href: '/services/corporate' },
{ name: 'Services - Criminal Law', href: '/services/criminal-law' },
{ name: 'Services - Real Estate', href: '/services/real-estate' },
{ name: 'Services - Entertainment', href: '/services/entertainment' },
{ name: 'Services - Intellectual Property Rights', href: '/services/intellectual-property-rights' },
{ name: 'Services - Loan Settlement', href: '/services/loan-settlement' },
{ name: 'Services - Banking And Finance', href: '/services/banking-and-finance' },
{ name: 'Articles', href: '/articles' },
{ name: 'Ama Live', href: '/ama-live' },
{ name: 'Blog', href: '/blog' },
{ name: 'Locations - Chennai', href: '/locations/chennai' },
{ name: 'Locations - Bengaluru', href: '/locations/bengaluru' },
{ name: 'Locations - Jaipur', href: '/locations/jaipur' },
{ name: 'Locations - Kolkata', href: '/locations/kolkata' },
{ name: 'Locations - Mumbai', href: '/locations/mumbai' },
{ name: 'Locations - Newdelhi', href: '/locations/newdelhi' },
{ name: 'Locations', href: '/locations' },
{ name: 'Contact', href: '/contact' },
{ name: 'Services', href: '/services' },
{ name: 'About', href: '/about' }
];

export default function DirectoryPage() {
  return (
    <main className="min-h-screen bg-gray-50/50 pb-24 pt-[100px]">
      <div className="max-w-[1400px] mx-auto px-4 sm:px-6 lg:px-8">
        
        {/* Header Section */}
        <div className="mb-12 border-b border-gray-200 pb-8">
          <h1 className="text-3xl md:text-5xl font-bold text-[#30261C] mb-4">
            Legal Services Directory
          </h1>
          <p className="text-gray-600 text-lg max-w-3xl">
            Browse our comprehensive directory of legal services, drafting notices, loan settlement guides, and arbitration support. Find exactly what you need quickly and easily.
          </p>
        </div>

        {/* Directory Grid */}
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
          {directoryLinks.map((link, idx) => (
            <Link 
              key={`${link.href}-${idx}`}
              href={link.href}
              className="group bg-white border border-gray-100 rounded-xl p-4 hover:border-[#D29E0D]/30 hover:shadow-sm hover:shadow-[#D29E0D]/10 transition-all flex items-center justify-between"
            >
              <span className="text-[14px] md:text-[15px] font-medium text-gray-700 group-hover:text-[#30261C] pr-4 line-clamp-2">
                {link.name}
              </span>
              <ChevronRight className="w-4 h-4 text-gray-400 group-hover:text-[#D29E0D] shrink-0" />
            </Link>
          ))}
        </div>
      </div>
    </main>
  );
}
