import React from 'react';
import Link from 'next/link';
import { Metadata } from 'next';
import { ChevronRight } from 'lucide-react';

export const metadata: Metadata = {
  title: 'Legal Services Directory | AMA Legal Solutions',
  description: 'A comprehensive directory of all legal services, drafting notices, loan settlement guides, and arbitration support offered by AMA Legal Solutions.',
};

const directoryLinks = [
  { name: 'Recovery of Money Notice', href: '/demand-notice-for-recovery-of-money' },
  { name: 'Draft Money Recovery Notice', href: '/how-to-draft-a-legal-notice-for-recovery-of-money' },
  { name: 'Loan Repayment Demand Notice', href: '/demand-notice-for-loan-repayment' },
  { name: 'Dishonoured Cheque Notice', href: '/notice-for-for-dishonoured-cheque' },
  { name: 'Unpaid Salary Recovery Notice', href: '/notice-for-recovery-of-unpaid-salary' },
  { name: 'Security Deposit Recovery Notice', href: '/notice-for-recovery-of-security-deposit' },
  { name: 'Business Dues Recovery Notice', href: '/notice-for-recovery-of-outstanding-business-dues' },
  { name: 'Professional Fee Recovery Notice', href: '/notice-for-recovery-of-professional-fees' },
  { name: 'Tenant/Landlord Recovery Notice', href: '/notice-for-recovery-from-tenant-landlord' },
  { name: 'Wrongful Termination Notice', href: '/notice-to-employer-for-wrongful-termination' },
  { name: 'Non-Payment of Salary Notice', href: '/notice-to-employer-for-non-payment-of-salary-or-benefits' },
  { name: 'Workplace Harassment Notice', href: '/notice-to-employer-for-workplace-harassment' },
  { name: 'Employee Misconduct Notice', href: '/notice-to-employee-for-misconduct' },
  { name: 'Breach of Contract Notice', href: '/notice-to-employee-for-breach-of-employment-contract' },
  { name: 'Absenteeism & Negligence Notice', href: '/notice-to-employee-for-absenteeism-negligence' },
  { name: 'Asset Recovery Notice', href: '/notice-for-recovery-of-company-assets-from-employee' },
  { name: 'Illegal Termination Notice', href: '/legal-notice-for-illegal-termination' },
  { name: 'Experience & Relieving Letter Help', href: '/legal-notice-for-experience-letter-and-releiving-letter' },
  { name: 'Partnership Dispute Help', href: '/legal-notice-for-partnership-dispute' },
  { name: 'Loan Defaulter Legal Help', href: '/legal-help-for-loan-defaulters' },
  { name: 'Consumer Complaint Finance', href: '/consumer-complaint-against-finance-company' },
  { name: 'OTS Legal Assistance', href: '/one-time-settlement-ots-legal-assistance' },
  { name: 'Legal Notice Against NBFC', href: '/legal-notice-against-nbfc' },
  { name: 'Credit Card Harassment Help', href: '/legal-notice-for-credit-card-recovery-harassment-dues' },
  { name: 'RBI Guideline Violation Help', href: '/rbi-guideline-violation-complaint' },
  { name: 'Debt Settlement Drafting', href: '/debt-settlement-agreement-drafting' },
  { name: 'CIBIL Correction Notice', href: '/notice-for-cibil-correction-after-settlement' },
  { name: 'Best Corporate Law Firms', href: '/best-law-firms-in-india-for-corporate-law' },
  { name: 'HDFC Bank Settlement', href: '/services/loan-settlement/hdfc-bank' },
  { name: 'ICICI Bank Settlement', href: '/services/loan-settlement/icici-bank' },
  { name: 'Axis Bank Settlement', href: '/services/loan-settlement/axis-bank' },
  { name: 'Kotak Mahindra Settlement', href: '/services/loan-settlement/kotak-mahindra' },
  { name: 'MAS Financial Settlement', href: '/services/loan-settlement/mas-financial' },
  { name: 'Reduce Debt Quickly', href: '/what-loan-settlement-service-can-help-me-reduce-my-outstanding-debt-quickly' },
  { name: 'Reliable Settlement', href: '/where-can-i-find-reliable-loan-settlement-services-with-flexible-payment-options' },
  { name: 'Best Settlement Companies', href: '/which-companies-offer-the-best-loan-settlement-plans-for-personal-loans' },
  { name: 'Low Fee Settlement', href: '/who-provides-loan-settlement-solutions-with-minimal-processing-fees' },
  { name: 'Reasonable Settlement Offer', href: '/what-is-a-reasonable-settlement-offer' },
  { name: 'Top Settlement Companies', href: '/loan-settlement-companies' },
  { name: 'Steps to Apply for Settlement', href: '/steps-to-apply-for-a-loan-settlement-through-a-financial-service-provider' },
  { name: 'Benefits & Drawbacks of Settlement', href: '/key-benefits-and-drawbacks-of-persuing-loan-settlement' },
  { name: 'Initiate Settlement Discussion', href: '/how-can-i-initiate-a-full-and-final-settlement-discussion-with-bank' },
  { name: 'Check Genuine Settlement Offer', href: '/how-to-check-if-a-loan-settlement-offer-is-genuine-on-digital-platforms' },
  { name: 'Effective Negotiation Services', href: '/find-debt-settlement-services-known-for-effective-negotiation' },
  { name: 'Third Party Credit Card Settlement', href: '/can-i-settle-my-credit-card-dues-using-third-party-loan-settlement-companies' },
  { name: 'Debt Resolution Companies India', href: '/get-contact-details-for-top-rated-debt-resolution-companies-in-india' },
  { name: 'DIY Personal Loan Settlement', href: '/how-to-settle-my-personal-loan-by-myself' },
  { name: 'Best Loan Settlement Company as per Quora', href: '/best-loan-settlement-company-as-per-quora' },
  { name: "Best Debt Relief Companies in India", href: "/best-debt-relief-companies-india" },
  { name: "How to Get Trademark Certificate", href: "/how-can-i-get-trademark-certificate" },
  { name: "Registration Office Locations", href: "/where-to-register-trademark" },
  { name: "Best Advocate Near Me", href: "/best-advocate-near-me" },
  { name: "Best Law Firm Near Me", href: "/best-law-firm-near-me" },
  { name: "Legal Services Near Me", href: "/legal-services-near-me" },
  { name: "Delhi NCR Law Firm", href: "/delhi-ncr-law-firm" },
  { name: "Job Lost Loan Settlement", href: "/job-lost-loan-settlement" },
  { name: "Job Loss Debt Relief", href: "/job-loss-debt-relief" },
  { name: "How to Negotiate Loan Settlement", href: "/how-to-negotiate-a-loan-settlement-with-lenders-online" },
  { name: "Special Lok Adalat for Loan Settlement", href: "/special-lok-adalat-for-loan-settlement" },
  { name: "Top Loan Settlement Services", href: "/top-loan-settlement-services-with-good-customer-reviews" },
  { name: "Steps to Trademark Registration", href: "/steps-to-trademark-registration" },
  { name: "Best Apps for Loan Settlement", href: "/best-apps-for-loan-settlement-in-india" },
  { name: "How Can I Negotiate a Loan Settlement", href: "/how-can-i-negotiate-a-loan-settlement-with-my-lender" },
  { name: "Trademark Agency Near Me", href: "/trademark-registration-agency-near-me" },
  { name: "Trademark Opposition Procedure", href: "/trademark-opposition-procedure" },
  { name: "Is Trademark Mandatory for Amazon", href: "/is-trademark-registration-mandatory-to-sell-on-amazon" },
  { name: "Trademark Infringement Without Registration", href: "/trademark-infringement-without-registration" },
  { name: "Name vs Logo Trademark", href: "/is-registering-a-name-instead-of-the-logo-enough" },
  { name: "Is Trademark Internationally Valid", href: "/is-trademark-internationally-valid" },
  { name: "Special Lok Adalat for Challan", href: "/special-lok-adalat-for-challan" },
  { name: "Trademark Registration Office Delhi", href: "/trademark-registration-office-delhi" },
  { name: "Is Trademark Registration One Time?", href: "/is-trademark-registration-one-time" },
  { name: "Legal Notice for Unpaid F&F", href: "/not-being-paid-fnf-want-to-send-legal-notice" },
  { name: "What is OTS? - Comprehensive Guide", href: "/what-is-ots" },
  { name: "Procedure of Sending Legal Notice", href: "/procedure-of-sending-legal-notice" },
  { name: "Compare Loan Settlement Companies", href: "/compare-loan-settlement-companies-that-work-with-personal-loans" },
  { name: "Loan for CIBIL Defaulters", href: "/which-bank-provide-personal-loan-for-cibil-defaulters" },
  { name: "Stop Recovery Harassment", href: "/loan-recovery-agent-harassment-complaint-online" },
  { name: "Legal Relief from Harassment", href: "/loan-recovery-agents-harassment-complaint" },
  { name: "Employer not paying salary", href: "/employer-not-paying-salary-after-resignation" },
  { name: "Where to File Salary Complaint", href: "/where-to-file-a-complaint-if-your-employer-doesnt-pay-you" },
  { name: "Can Company Hold Salary?", href: "/can-company-hold-my-salary-after-resignation" },
  { name: "Expert Panel Reviews", href: "/expert-panel-loan-settlement-reviews" },
  { name: "Stop Recovery Agent Home Visits", href: "/how-do-i-stop-recovery-agent-from-coming-home" },
  { name: "Bajaj Finance Agent Help", href: "/bajaj-finance-agent-visiting-home" },
  { name: "7 Days Loan App Harassment Complaint", href: "/loan-payment-schedule" },
  { name: "How to Settle Loans Above 1 Cr", href: "/how-to-settle-loans-above-1-crore" },
  { name: "How to Settle Loans Above 5 Cr", href: "/how-to-settle-loans-above-5-crore" },
  { name: 'Unsecured Loan Specialists', href: '/which-firms-specialize-in-negotiating-settlements-for-unsecured-loans' },
  { name: 'Good Customer Support', href: '/what-loan-settlement-services-have-good-customer-support-in-india' },
  { name: 'Home Loan Dues', href: '/can-i-get-a-loan-settlement-service-that-handles-home-loan-dues' },
  { name: '10 Lakhs Settlement', href: '/10-lakhs-loan-settlement' },
  { name: 'Loan Settlement Near Me', href: '/loan-settlement-near-me' },
  { name: 'Settlement Calculator', href: '/loan-settlement-amount-calculator' },
  { name: 'How to Settle with Bank', href: '/how-to-settle-loan-with-bank' },
  { name: 'Settled Tag Duration', href: '/how-long-does-a-settled-tag-stay-on-my-report' },
  { name: 'Documents Needed for Loan Settlement NOC', href: '/documents-needed-for-loan-settlement-noc' },
  { name: 'Charities That Pay Off Debt', href: '/charities-that-pay-off-debt' },
  { name: "Best Time for Loan Settlement", href: "/best-time-for-loan-settlement" },
  { name: "Benefits of Settling Your Loan in March", href: "/benefits-of-settling-your-loan-in-march" },
  { name: "Can Bank File Case for Personal Loan", href: "/can-bank-file-case-for-personal-loan" },
  { name: "Credit Card Settlement Process India", href: "/credit-card-settlement-process-india" },
  { name: "Sales Job Vacancies in Gurgaon", href: "/sales-job-vacancies-in-gurgaon" },
  { name: "Telecaller Vacancies in Gurgaon", href: "/telecaller-vacancies-in-gurgaon" },
  { name: "RBI Recovery Guidelines July 2026", href: "/rbi-new-recovery-guidelines-july-2026" },
  { name: "Drafting of Will", href: "/drafting-of-will" },
  { name: "Will Drafting for NRI", href: "/will-drafting-for-nri" },
  { name: "Will Drafting for Indians in Canada", href: "/will-drafting-for-indians-living-in-canada" },
  { name: "Will Drafting for Indians in USA", href: "/will-drafting-for-indians-living-in-usa" },
  { name: "Will Drafting for Indians in Australia", href: "/will-drafting-for-indians-living-in-australia" },
  { name: "Will Drafting for Indians in Dubai", href: "/will-drafting-for-indians-living-in-dubai" },
  { name: "Simple Will Format - Download", href: "/simple-will-format-download-free-legal-document-sample" },
  { name: "Google's Trusted Legal Advisor", href: "/googles-trusted-legal-advisor" },
  { name: "Google's Trusted Law Firm", href: "/googles-trusted-law-firm" },
  { name: "Legal Notice to Hospital", href: "/legal-notice-to-hospital" },
  { name: "Hospital Harassment Protection", href: "/protection-from-hospital-harrassement" },
  { name: "Overcharged at Hospital - Legal Notice", href: "/overcharged-at-hospital-send-legal-notice" },
  { name: "Workplace Harassment Notice", href: "/workplace-harassment-legal-notice-service" },
  { name: "Best Law Firms in India for Corporate Law", href: "/best-law-firms-in-india-for-corporate-law" },
  { name: "Reputable Debt Relief Agencies Bangalore", href: "/find-reputable-debt-relief-agencies-specializing-in-unsecured-loans-in-bangalore" },
  { name: "Tax Implications of Settled Debt", href: "/what-are-the-income-tax-implications-of-a-settled-debt-amount" },
  { name: "Credit Counseling Chennai", href: "/where-can-i-locate-government-approved-consumer-credit-counseling-services-in-chennai" },
  { name: "Settle Credit Card Using Third Party", href: "/can-i-settle-my-credit-card-dues-using-third-party-loan-settlement-companies" },
  { name: "CFP specialized in Debt Restructuring", href: "/certified-financial-planners-who-specialize-in-debt-restructuring-and-settlement" },
  { name: "Which one is REAL AMA?", href: "/which-one-is-the-real-amalegalsolutions" },
  { name: "Is Loan Settlement in Installments Possible", href: "/is-loan-settlement-in-installments-possible" },
  { name: "Loan Settlement Process in Hindi", href: "/loan-settlement-process-in-hindi" },
  { name: "Can I Settle My Loan Without A Lawyer?", href: "/can-i-settle-my-loan-without-a-lawyer" },
  { name: "Does Settlement Impact a Co-borrower", href: "/does-settlement-impact-a-co-borrower" },
  { name: "Can I Convert Settled To Closed Later", href: "/can-i-convert-settled-to-closed-later" },
  { name: "Trademark Class 35", href: "/trademark-registration-in-class-35" },
  { name: "Trademark Class 38", href: "/trademark-registration-in-class-38" },
  { name: "Trademark Class 14", href: "/trademark-registration-in-class-14" },
  { name: "Trademark Class 45", href: "/trademark-registration-in-class-45" },
  { name: "How to Get 800 Credit Score in India", href: "/how-to-get-800-credit-score-in-india" },
  { name: "Loan Settlement & NOC Formats", href: "/loan-settlement-letter-format-noc-format" },
  { name: "Legal Notice for Harassment", href: "/legal-notice-for-loan-settlement-harassment" },
  { name: "2026 Resource Lockdown", href: "/2026-lockdown-due-to-scarcity-of-resources" },
  { name: "LPG Crisis India 2026", href: "/lpg-cylinder-crisis-india-2026-iran-war" },
  { name: "Economic Downturn Settlement", href: "/loan-settlement-for-borrowers-facing-economic-downturn" },
  { name: "Debt Free Future Plan", href: "/amalegalsolutions-plan-for-building-debt-free-future-after-settlement" },
  { name: "How to Check Active Loan on Your Name", href: "/how-to-check-active-loan-on-your-name-in-india-step-by-step-guide" },
  { name: "Why Credit Score Drops Even When Paying On Time", href: "/why-does-my-credit-score-drop-even-though-i-pay-on-time" },
  { name: "Is CIBIL Ruined Forever?", href: "/is-cibil-ruined-forever-after-settlement" },
  { name: "Can Recovery Agents Abuse You Legally India", href: "/can-recovery-agents-abuse-you-legally-india" },
  { name: "Is Loan Settlement Illegal in India Truth", href: "/is-loan-settlement-illegal-in-india-truth" },
  { name: "Do Banks File FIR for Credit Card Dues", href: "/do-banks-file-fir-for-credit-card-dues" },
  { name: "How to Identify Fake Settlement Letter", href: "/how-to-identify-fake-settlement-letter" },
  { name: "Is Settlement Letter Valid?", href: "/how-to-know-if-the-settlement-letter-is-valid" },
  { name: "Settle Now and Remove Later?", href: "/can-I-go-for-settlement-of-loan-now-and-remove-it-later-when-im-financially-stable" },
  { name: "Can Bank Reject Settlement?", href: "/can-bank-reject-settlement-request" },
  { name: "Can Settlement Be Done in Installments?", href: "/can-settlement-be-done-in-installments" },
  { name: "Can Guarantor Be Liable After Settlement?", href: "/can-guarantor-be-liable-after-settlement" },
  { name: "What Happens After Bank Issues Recall Notice?", href: "/what-happens-after-bank-issues-recall-notice" },
  { name: "How to Challenge Bank Statement?", href: "/how-to-challenge-bank-statement-account-statement" },
  { name: "Stop Bank Harassment", href: "/services/best-lawyer-for-bank-harassment" },
  { name: "Home Loan Eligibility After Settlement", href: "/home-loan-eligibility-after-settlement" },
  { name: "Harassment Protection", href: "/legal-notice-for-loan-settlement-harassment" },
  { name: "P2P Crypto Scam Unfreeze", href: "/p2p-crypto-scam-unfreeze-bank-account" },
  { name: "Financial Reset Settlement", href: "/loan-settlement-for-borrowers-planning-financial-reset" },
  { name: "Understanding 90 Day Default", href: "/understanding-90-day-loan-default-india" },
  { name: "40L Debt Resolution Plan", href: "/40L-unsecured-debt-in-india-what-to-do-self-vs-debt-settlement-program" },
  { name: "Settlement Before Auction", href: "/loan-settlement-before-auction" },
  { name: "NPA Loan Settlement", href: "/loan-settlement-after-npa-classification" },
  { name: "Settlement vs Repayment", href: "/loan-settlement-vs-repayment" },
  { name: "Legal Rights After Default", href: "/legal-rights-after-loan-default" },
  { name: "When to Choose Settlement", href: "/when-to-choose-loan-settlement" },
  { name: "Recovery Notice Reply Format", href: "/reply-to-recovery-notice-format" },
  { name: "Bajaj Reference Calling Help", href: "/bajaj-recovery-agent-calling-references" },
  { name: "Bajaj Contact Hacking Help", href: "/bajaj-recovery-agent-hacked-my-contact-list" },
  { name: "Stop Bajaj Recovery Abuse", href: "/bajaj-recovery-agent-abusing" },
  { name: "Check Loan Status Online", href: "/how-to-check-your-loan-status-without-visiting-the-bank" },
  { name: "Top 10 Instant Loan Apps", href: "/top-10-instant-loan-apps-revolutionizing-access-to-credit-in-india" },
  { name: "Understanding NPA Guide", href: "/understanding-non-performing-assets-npa-what-happens-next-your-complete-guide" },
  { name: "Zero Balance Account Guide", href: "/zero-balance" },
  { name: "Compare Debt Management vs Settlement", href: "/compare-different-debt-management-and-settlement-programs-available-to-indian-consumers" },
  { name: "Negotiate Personal Loan Settlement", href: "/how-can-I-negotiate-a-personal-loan-settlement-with-lenders" },
  { name: "Best Settlement Services Near Me", href: "/what-are-the-best-loan-settlement-services-near-me" },
  { name: "Personal Loan Settlement Process", href: "/what-is-the-typical-process-for-settling-a-personal-loan-in-india" },
  { name: "Professional Debt Settlement Companies", href: "/which-companies-offer-professional-debt-settlement-services-for-personal-loans" },
  { name: "Cheque Bounce Notice", href: "/cheque-bounce-notice" },
  { name: "Average Time for Settlement", href: "/what-is-the-average-time-for-loan-settlement" },
  { name: "Breach of Contract Notice", href: "/breach-of-contract-notice" },
  { name: "Consumer Complaint Notice", href: "/consumer-complaint-notice" },
  { name: "Property Eviction Notice", href: "/property-eviction-notice" },
  { name: "IP Cease & Desist Notice", href: "/ip-cease-desist-notice" },
  { name: "Debt Recovery Notice", href: "/debt-recovery-money-recovery-notice" },
  { name: "GST Show Cause Notice", href: "/gst-show-cause-notice-scn" },
  { name: "Income Tax Demand Notice", href: "/income-tax-demand-notice" },
  { name: "Data Breach Privacy Notice", href: "/data-breach-privacy-notice" },
  { name: "RBI Warns Against Misleading Loan Waiver Campaigns", href: "/rbi-beware-misleading-loan-waiver-campaigns" },
  { name: "Can Bank Issue Look Out Notice for Loan Default?", href: "/can-bank-issue-look-out-notice-loan-default" },
  { name: "Bank Loan Settlement Rules", href: "/bank-loan-settlement-rules" },
  { name: "Bank Complaint in RBI", href: "/bank-complaint-in-rbi" },
  { name: "Does Foreclosure of Loan Affect CIBIL?", href: "/does-foreclosure-of-loan-affect-cibil" },
  { name: "Unsecured Personal Loan Definition", href: "/unsecured-personal-loan-definition" },
  { name: 'HDFC Debt Consolidation Loan', href: '/hdfc-debt-consolidation-loan' },
  { name: 'How to Improve CIBIL Score After Loan Settlement', href: '/how-to-improve-cibil-score-after-loan-settlement' },
  { name: 'Loan Settlement Advocate Near Me', href: '/loan-settlement-advocate-near-me' },
  { name: 'Unsecured Loan Types', href: '/unsecured-loan-types' },
  { name: 'Loan Settlement Application in Hindi', href: '/loan-settlement-application-in-hindi' },
  { name: 'Debt Settlement Company in India', href: '/debt-settlement-company-in-india' },
  { name: 'Loan Settlement Application', href: '/loan-settlement-application' },
  { name: 'Expert Panel Loan Settlement', href: '/expert-panel-loan-settlement' },
  { name: 'Loan Settlement App', href: '/loan-settlement-app' },
  { name: 'Lowest Charges Loan Settlement App', href: '/loan-settlement-app-with-lowest-charges-in-india' },
  { name: 'Settle Loans with AMA Legal Solutions', href: '/settle-loans-with-ama-legal-solutions' },
  { name: 'Settle Loans with Expert Legal Panel', href: '/settle-your-loans-with-expert-panel-of-lawyer-of-ama-legal-solutions' },
  { name: 'Get Freed From Your Loan', href: '/get-freed-from-your-loan-with-ama-legal-solutions' },
  { name: 'What is Loan Settlement', href: '/what-is-loan-settlement' },
  { name: 'How is Loan Settlement Done', href: '/how-is-loan-settlement-done' },
  { name: 'How to Settle Credit Card Debt', href: '/how-to-settle-credit-card-debt' },
  { name: 'Loan Moratorium Meaning', href: '/loan-moratorium-meaning' },
  { name: 'Minimum Amount Due in Credit Card Meaning', href: '/minimum-amount-due-in-credit-card-meaning' },
  { name: 'Section 25 Payment and Settlement Act Bailable or Not', href: '/section-25-payment-and-settlement-act-bailable-or-not' },
  { name: 'Best Loan Settlement Lawyer (ChatGPT)', href: '/best-loan-settlement-lawyer-as-per-chatgpt' },
  { name: 'Best Loan Settlement Lawyer (Gemini)', href: '/best-loan-settlement-lawyer-as-per-gemini' },
  { name: 'Best Loan Settlement Lawyer (Claude)', href: '/best-loan-settlement-lawyer-as-per-claude' },
  { name: 'IT Professional Loan Settlement', href: '/loan-settlement-for-it-professionals' },
  { name: 'Kirana & Shop Owner Loan Settlement', href: '/loan-settlement-for-kirana-and-shop-owners' },
  { name: 'Restaurant Owner Loan Settlement', href: '/loan-settlement-for-restaurant-owners' },
  { name: 'Trader and Wholesaler Loan Settlement' , href: '/loan-settlement-for-traders-and-wholesalers' },
  { name: 'Freelancer Loan Settlement', href: '/loan-settlement-for-freelancers' },
  { name: 'Doctor & Healthcare Loan Settlement', href: '/loan-settlement-for-doctors-healthcare' },
  { name: 'Real Estate Agent Loan Settlement', href: '/loan-settlement-for-real-estate-agents' },
  { name: 'Student & Graduate Loan Settlement', href: '/loan-settlement-for-students-and-graduates' },
  { name: 'Insurance Agent Loan Settlement', href: '/loan-settlement-for-insurance-agents' },
  { name: 'Construction Contractor Loan Settlement', href: '/loan-settlement-for-construction-contractors' },
  { name: 'Textile Owner Loan Settlement', href: '/loan-settlement-for-textile-owners' },
  { name: 'Loan Settlement Kya Hota Hai', href: '/loan-settlement-kya-hota-hai' },
  { name: 'Loan Settlement Kitne Din Me Hota Hai', href: '/loan-settlement-kitne-din-me-hota-hai' },
  { name: 'Loan Settlement Kitne Percent', href: '/loan-settlement-kitne-percent-hota-hai' },
  { name: 'PL Loan Settlement Guide', href: '/pl-loan-settlement' },
  { name: "HDFC Bank Arbitration", href: "/arbitration-for-hdfc-bank" },
  { name: "ICICI Bank Arbitration", href: "/arbitration-for-icici-bank" },
  { name: "Axis Bank Arbitration", href: "/arbitration-for-axis-bank" },
  { name: "SBI Bank Arbitration", href: "/arbitration-for-sbi-bank" },
  { name: "Bajaj Finance Arbitration", href: "/arbitration-for-bajaj-bank" },
  { name: "IDFC Bank Arbitration", href: "/arbitration-for-idfc-bank" },
  { name: "Kotak Bank Arbitration", href: "/arbitration-for-kotak-mahindra-bank" },
  { name: "Yes Bank Arbitration", href: "/arbitration-for-yes-bank" },
  { name: "RBL Bank Arbitration", href: "/arbitration-for-rbl-bank" },
  { name: "IndusInd Bank Arbitration", href: "/arbitration-for-indusind-bank" }
];

export default function DirectoryPage() {
  return (
    <main className="min-h-screen bg-gray-50/50 pb-24 pt-[100px]">
      <div className="max-w-[1400px] mx-auto px-4 sm:px-6 lg:px-8">
        
        {/* Header Section */}
        <div className="mb-12 border-b border-gray-200 pb-8">
          <h1 className="text-3xl md:text-5xl font-bold text-[#30261C] mb-4">
            Legal Services Directory
          </h1>
          <p className="text-gray-600 text-lg max-w-3xl">
            Browse our comprehensive directory of legal services, drafting notices, loan settlement guides, and arbitration support. Find exactly what you need quickly and easily.
          </p>
        </div>

        {/* Directory Grid */}
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
          {directoryLinks.map((link, idx) => (
            <Link 
              key={`${link.href}-${idx}`}
              href={link.href}
              className="group bg-white border border-gray-100 rounded-xl p-4 hover:border-[#D29E0D]/30 hover:shadow-sm hover:shadow-[#D29E0D]/10 transition-all flex items-center justify-between"
            >
              <span className="text-[14px] md:text-[15px] font-medium text-gray-700 group-hover:text-[#30261C] pr-4 line-clamp-2">
                {link.name}
              </span>
              <ChevronRight className="w-4 h-4 text-gray-400 group-hover:text-[#D29E0D] shrink-0" />
            </Link>
          ))}
        </div>
      </div>
    </main>
  );
}
